import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createGame,SAVE_KEY} from './engine.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const url=process.env.ZORK_URL||'http://127.0.0.1:8135/web/136-zork.html?test=1';
const world=JSON.parse(fs.readFileSync(new URL('./world.json',import.meta.url)));
const results=[],errors=[],external=[];
function fixture(room,pos=[0,0]){const g=createGame(world);g.enter('LROOM');for(const id of ['LAMP','KNIFE']){g.s.inventory.push(id);g.s.locations[id]='inventory'}g.s.lights.LAMP=true;g.checkpoint();g.enter(room);g.s.pos=pos;return g;}
async function pageFor(g,options={}){const context=await browser.newContext({viewport:{width:1440,height:900},...options});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8135/'))external.push(r.url())});if(g)await p.addInitScript(({key,saved})=>localStorage.setItem(key,saved),{key:SAVE_KEY,saved:g.serialize()});await p.goto(url);await p.locator('#begin:enabled').waitFor();return p;}
const snap=p=>p.evaluate(()=>zorkTest());
async function hold(p,key,ms){await p.keyboard.down(key);await p.waitForTimeout(ms);await p.keyboard.up(key)}
try{
 let p=await pageFor(fixture('CELLA'));await p.locator('#begin').click();assert(await p.evaluate(()=>!!document.pointerLockElement));await p.waitForTimeout(200);await p.screenshot({path:'/tmp/zork-lit.png'});await p.keyboard.press('KeyL');await p.waitForTimeout(200);assert(!(await snap(p)).lit);await p.screenshot({path:'/tmp/zork-dark.png'});await hold(p,'KeyW',7000);await p.waitForTimeout(400);assert.equal((await snap(p)).state.room,'LROOM');assert.equal(await p.locator('#roomname').innerText(),'起居室');results.push('lamp blackout, dark movement death, checkpoint scene restore');await p.context().close();
 p=await pageFor(fixture('CELLA'));await p.locator('#begin').click();await hold(p,'KeyW',6000);assert((await snap(p)).state.pos[1]>-14.9);assert((await snap(p)).state.pos[1]<-14);results.push('underground outer wall blocks continuous walking');await p.context().close();
 const flooded=fixture('MAINT');flooded.s.drown=44.8;p=await pageFor(flooded);await p.locator('#begin').click();await p.waitForTimeout(800);assert.equal((await snap(p)).state.room,'LROOM');assert.equal(await p.locator('#roomname').innerText(),'起居室');results.push('flood death swaps rendered chunk and restores checkpoint inventory');await p.context().close();
 p=await pageFor(fixture('MTROL',[1,-2.8]));await p.locator('#begin').click();await p.keyboard.down('KeyR');await p.waitForTimeout(2200);await p.keyboard.up('KeyR');let q=await snap(p);assert(q.state.hp<100&&q.state.hp>=92);assert.equal(q.actors[0].mode,'chase');for(let i=0;i<4;i++){await p.keyboard.press('Space');await p.waitForTimeout(650)}q=await snap(p);assert(q.state.flags['TROLL-FLAG']);assert(q.state.dead.includes('TROLL'));results.push('enemy senses/chases, guard reduces damage, four melee strikes defeat troll');await p.context().close();
 p=await pageFor(fixture('MTROL'));await p.locator('#begin').click();await p.waitForTimeout(900);assert.equal((await snap(p)).actors[0].mode,'chase');await p.keyboard.press('KeyL');await p.keyboard.down('ShiftLeft');await hold(p,'KeyS',2200);await p.keyboard.up('ShiftLeft');await p.waitForTimeout(3000);q=await snap(p);assert.equal(q.actors[0].mode,'search');await p.waitForTimeout(4300);assert.equal((await snap(p)).actors[0].mode,'patrol');results.push('enemy loses unlit fleeing target, searches, returns to patrol');await p.context().close();
 p=await pageFor(null,{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});await p.screenshot({path:'/tmp/zork-mobile-title.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#begin').tap();assert(await p.locator('#touch').isVisible());await p.locator('#touchI').tap();assert(await p.locator('#modal').isVisible());await p.locator('#closeModal').tap();await p.screenshot({path:'/tmp/zork-mobile-play.png'});results.push('390×844 mobile title, touch controls, inventory and no horizontal overflow');await p.context().close();
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(new URL('./checks-verification.json',import.meta.url),JSON.stringify({completed:new Date().toISOString(),results,errors,externalRequests:external},null,2));console.log('PASS',results);
}catch(e){console.error(e);for(const c of browser.contexts())for(const p of c.pages()){await p.screenshot({path:'/tmp/zork-check-failure.png'});console.log(await snap(p))}process.exitCode=1}finally{await browser.close()}
