// 開發用：看兵線交戰與技能特效
import { mkdirSync } from 'node:fs';
import { open } from './lib.mjs';
const a = process.argv.slice(2), w = +(a[0] || 1440), h = +(a[1] || 900), hero = a[2] || 'homura';
const out = 'dist/shots'; mkdirSync(out, { recursive: true });
const { browser, page, log } = await open('../../web/198-ki-lanes.html', { w, h });
const raf = () => page.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(r)))));
const shot = async (n) => { await raf(); await page.screenshot({ path: `${out}/f-${hero}-${n}.png` }); };
const ev = (fn, arg) => page.evaluate(fn, arg);
await ev((id) => window.__ki.start(id, 1), hero);
await ev(() => { const k = window.__ki; k.fastForward(22); k.teleport(-12, 12); });
await ev(() => window.__ki.fastForward(8));
await page.waitForTimeout(500); await shot('1-lane');
console.log(JSON.stringify(await ev(() => window.__ki.state().heroes)));
await ev(() => { const k = window.__ki; k.setLevel(6); k.learnAll(); k.give({ ki: 500 }); k.freezeAI(true); });
const e = await ev(() => { const k = window.__ki; const id = k.spawnEnemyHeroNear(5); return k.enemyHero(); });
await ev((e) => window.__ki.cast('Q', e.x, e.z), e);
await page.waitForTimeout(160); await shot('2-q');
await ev((e) => window.__ki.cast('W', e.x, e.z), e);
await page.waitForTimeout(250); await shot('3-w');
await page.waitForTimeout(600);
const e2 = await ev(() => window.__ki.enemyHero());
await ev((e) => window.__ki.cast('E', e.x, e.z), e2);
await page.waitForTimeout(120); await shot('4-e');
await page.waitForTimeout(500);
const e3 = await ev(() => window.__ki.enemyHero());
await ev((e) => window.__ki.cast('R', e.x, e.z), e3);
await page.waitForTimeout(500); await shot('5-r-intro');
await page.waitForTimeout(900); await shot('6-r-fire');
await page.waitForTimeout(1500); await shot('7-after');
console.log(JSON.stringify((await ev(() => window.__ki.state())).player));
console.log('gpu', log.gpu, 'errors', log.pageerrors, log.errors.slice(0, 5));
await browser.close();
