// 開發用：手機尺寸下的技能特效、大招演出、商店與結算畫面。node tools/mobile-fx.mjs [英雄] [w] [h]
import { mkdirSync } from 'node:fs';
import { open } from './lib.mjs';
const [hero = 'goku', w = '390', h = '844'] = process.argv.slice(2);
const out = 'dist/shots'; mkdirSync(out, { recursive: true });
const tag = `mf-${hero}-${w}x${h}`;
const { browser, page, log } = await open('../../web/198-ki-lanes.html', { w: +w, h: +h, touch: true });
const raf = () => page.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(r)))));
const shot = async (n) => { await raf(); await page.screenshot({ path: `${out}/${tag}-${n}.png` }); };
const ev = (fn, arg) => page.evaluate(fn, arg);
await page.waitForTimeout(800);
await ev((id) => window.__ki.start(id, 1), hero);
await ev(() => { const k = window.__ki; k.fastForward(22); k.teleport(-12, 12); k.fastForward(8); });
await page.waitForTimeout(400); await shot('1-lane');
await ev(() => { const k = window.__ki; k.setLevel(6); k.learnAll(); k.give({ ki: 500 }); k.freezeAI(true); });
const e = await ev(() => { const k = window.__ki; k.spawnEnemyHeroNear(5); return k.enemyHero(); });
await ev((e) => window.__ki.cast('Q', e.x, e.z), e); await page.waitForTimeout(160); await shot('2-q');
await page.waitForTimeout(500);
const e3 = await ev(() => window.__ki.enemyHero());
await ev((e) => window.__ki.cast('R', e.x, e.z), e3);
await page.waitForTimeout(450); await shot('3-r-intro');
await page.waitForTimeout(900); await shot('4-r-fire');
await page.waitForTimeout(1200); await shot('5-after');
await ev(() => { const k = window.__ki; k.setGold(3000); });
await page.keyboard.press('KeyP'); await page.waitForTimeout(400); await shot('6-shop');
await page.tap('.shopX').catch(() => {}); await page.waitForTimeout(300);
await ev(() => window.__ki.win()); await page.waitForTimeout(4500); await shot('7-win');
const sw = await ev(() => [document.documentElement.scrollWidth, innerWidth]);
console.log(tag, 'scroll', sw, 'errors', log.pageerrors, log.errors.slice(0, 4));
await browser.close();
