// 地圖角色：16×16，四方向 × 三幀（0 站立、1 / 2 左右腳交替）。
// 頭與身體用字元格手繪（每個角色各自的輪廓），腿與手臂依方向與幀數程式化擺動，
// 最後自動補上一像素的加深色描邊。left 由 right 左右翻轉而來。

import { C } from './palette';
import { Canvas } from './raster';

export type CharDir = 'up' | 'down' | 'left' | 'right';

interface CharSpec {
  /** 字元 → 色盤索引（會與共用 legend 合併）。 */
  legend: Record<string, number>;
  down: string;
  up: string;
  right: string;
  /** 手臂：袖子顏色、手的顏色、起始列、袖長、正面時左右手的 x。 */
  arm: { sleeve: number; sleeveShade: number; hand: number; y: number; len: number; x: [number, number]; big?: boolean };
  /** 腿：由上到下每一列的顏色（最後一列是鞋），腿的起始列，正面時左右腿的 x（各 2 像素寬）。 */
  legs: { rows: number[]; shade: number[]; y: number; x: [number, number] };
}

const BASE: Record<string, number> = {
  k: C.skin, K: C.skinShade, e: C.ink, w: C.paper, W: C.mist, m: C.rose,
};

/** 把樣板字串拆成列；第一個換行之後才開始算第 0 列。 */
const rows = (s: string): string[] => s.replace(/^\n/, '').replace(/\n\s*$/, '').split('\n').map((r) => r.trimEnd());

const SPECS: Record<string, CharSpec> = {
  // 主角：芥黃鴨舌帽、敞開的苔綠外套、斜背的皮包、紅色球鞋
  player: {
    legend: { a: C.gold, A: C.ochre, h: C.bark, H: C.soil, t: C.moss, T: C.forest, b: C.wood, c: C.wood, B: C.bark },
    down: `
................
.....aaaaaa.....
....aaaaaaaa....
...aaaawwaaaa...
..AAAAAAAAAAAA..
...hhhkkkkhhh...
...hkekkkkekh...
...kkekkkkekk...
....kkkkkkkk....
....tbwwwwtt....
....ttbwwwtt....
....TTTbTccT....
.........cB.....`,
    up: `
................
.....aaaaaa.....
....aaaaaaaa....
...aaaaaaaaaa...
...aaaaaaaaaa...
...hAAAwAAAAh...
...hhhhhhhhhh...
...hhhhhhhhhh...
....HhhhhhhH....
....tttttbtt....
....ttttbttt....
....TTTbTTTT....
.....cB.........`,
    right: `
................
....aaaaaa......
...aaaaaaaa.....
...aaaaaaawa....
...aaaaaAAAAAA..
...hhhhhkkkk....
...hhhKkkkek....
...hhhkkkkek....
....hhkkkkk.....
.....ttwwt......
....cttwwt......
....BTTTTT......`,
    arm: { sleeve: C.moss, sleeveShade: C.forest, hand: C.skin, y: 9, len: 2, x: [3, 12] },
    legs: { rows: [C.denim, C.denim, C.ember], shade: [C.navy, C.navy, C.emberDark], y: 12, x: [5, 9] },
  },
  // 禾老師：寬邊草帽、白鬍子、及踝的褐色長袍、苔綠腰帶
  tutor: {
    legend: { a: C.straw, A: C.sand, b: C.ember, h: C.mist, H: C.ash, t: C.wood, T: C.bark, s: C.moss },
    down: `
................
.....aaaaaa.....
....aaaaaaaa....
....bbbbbbbb....
.aaaaaaaaaaaaaa.
..AAAAAAAAAAAA..
...hkekkkkekh...
...hkkkKKkkkh...
....hhhhhhhh....
....thhhhhht....
....tthhhhtt....
....ssssssss....
....tttttttt....
....TTTTTTTT....`,
    up: `
................
.....aaaaaa.....
....aaaaaaaa....
....bbbbbbbb....
.aaaaaaaaaaaaaa.
..AAAAAAAAAAAA..
...hhhhhhhhhh...
...hhhhhhhhhh...
....HhhhhhhH....
....tttttttt....
....tttttttt....
....ssssssss....
....tttttttt....
....TTTTTTTT....`,
    right: `
................
.....aaaaa......
....aaaaaaa.....
....bbbbbbb.....
.aaaaaaaaaaaaa..
..AAAAAAAAAAAA..
....hhkkkkek....
....hhkkkkkkk...
.....hhhhhhh....
.....tthhhh.....
.....tttth......
.....ssssss.....
.....tttttt.....
.....TTTTTT.....`,
    arm: { sleeve: C.wood, sleeveShade: C.bark, hand: C.skin, y: 9, len: 2, x: [3, 12] },
    legs: { rows: [C.bark, C.bark, C.sand], shade: [C.soil, C.soil, C.wood], y: 12, x: [5, 9] },
  },
  // 蘇護士：白色護士帽（玫瑰色葉紋）、深褐包頭、白洋裝、粉紅衣領與圍裙帶
  healer: {
    legend: { h: C.bark, H: C.soil, l: C.wood, p: C.rose, P: C.berry },
    down: `
................
.....wwwwww.....
....wwwppwww....
...hwwwwwwwwh...
...hhhhhhhhhh...
...hhhkkkkhhh...
...hkekkkkekh...
...hkekkkkekh...
...hhkkkkkkhh...
....wppppppw....
....wwwppwww....
....wwwwwwww....
...wwwwwwwwww...`,
    up: `
................
.....wwwwww.....
....wwwwwwww....
...hwwwwwwwwh...
...hhhhhhhhhh...
...hhhhHHhhhh...
...hhhHllHhhh...
...hhhHlHHhhh...
...hhhhHHhhhh...
....wwwwwwww....
....wwwppwww....
....wwppppww....
...wwwwwwwwww...`,
    right: `
................
....wwwwww......
...wwwwwpww.....
..hwwwwwwww.....
.lhhhhhhhhh.....
.hlhhhhkkkk.....
.hh.hhkkkek.....
....hhkkkek.....
....hhkkkk......
.....wpppw......
.....wwwww......
....pwwwww......
....wwwwwww.....`,
    arm: { sleeve: C.paper, sleeveShade: C.mist, hand: C.skin, y: 9, len: 2, x: [3, 12] },
    legs: { rows: [C.paper, C.mist, C.rose], shade: [C.mist, C.ash, C.berry], y: 12, x: [5, 9] },
  },
  // 阿良：黑髮綁米色頭巾、寬肩、藍襯衫外罩米色圍裙
  shopkeeper: {
    legend: { h: C.slate, H: C.ink, a: C.straw, A: C.sand, t: C.denim, T: C.navy, c: C.paper, C: C.mist, b: C.wood },
    down: `
................
................
....hhhhhhhh....
...hhhhhhhhhh...
...aaaaaaaaaa...
...hhhkkkkhhh...
...hkekkkkekh...
...kkekkkkekk...
....kkkKKkkk....
...ttccccccttt..
...ttccbbcctt...
...TTccccccTT...
....cccccccc....
....CCCCCCCC....`,
    up: `
................
................
....hhhhhhhh....
...hhhhhhhhhh...
...aaaaaaaaaa...
...hhhhaahhhh...
...hhhhaAhhhh...
...hhhhhhhhhh...
....HhhhhhhH....
...tttttttttt...
...ttttccttttt..
...tttcttcttt...
....TTTTTTTT....`,
    right: `
................
................
....hhhhhhh.....
...hhhhhhhhh....
...aaaaaaaaaa...
.aAhhhhkkkk.....
..Ahhhkkkkek....
...hhhkkkkek....
....hhkkkkkK....
....ttttcccc....
....tttccccc....
....TTTccccc....
.......cccc.....
.......CCCC.....`,
    arm: { sleeve: C.denim, sleeveShade: C.navy, hand: C.skin, y: 9, len: 2, x: [2, 13] },
    legs: { rows: [C.bark, C.bark, C.soil], shade: [C.soil, C.soil, C.ink], y: 12, x: [5, 9] },
  },
  // 小楓：比大人矮兩格、楓紅色刺刺頭、芥黃 T 恤、短褲露出膝蓋
  kid: {
    legend: { h: C.flame, H: C.ember, l: C.glow, t: C.gold, T: C.ochre },
    down: `
................
................
.....h..h..h....
....hhhhhhhhh...
...hhhlhhhhhhh..
...hhhhhhhhhh...
...hhkkkkkkhh...
...hkekkkkekh...
...kkekkkkekk...
....kkmkkmkk....
....tttttttt....
....TTTTTTTT....`,
    up: `
................
................
.....h..h..h....
....hhhhhhhhh...
...hhhhhhhhhhh..
...hhhhhhhhhh...
...hhhhhhhhhh...
...hhhhhhhhhh...
...hhhhhhhhhh...
....HhhhhhhH....
....tttttttt....
....TTTTTTTT....`,
    right: `
................
................
....h..h.h......
...hhhhhhhh.....
..hhhhhhlhhh....
..hhhhhhhhhh....
...hhhhkkkkk....
...hhhkkkkek....
...hhhkkkkek....
....hhkkkkm.....
.....ttttt......
.....TTTTT......`,
    arm: { sleeve: C.gold, sleeveShade: C.ochre, hand: C.skin, y: 10, len: 1, x: [3, 12] },
    legs: { rows: [C.denim, C.skin, C.paper], shade: [C.navy, C.skinShade, C.mist], y: 12, x: [5, 9] },
  },
  // 旅人：莓紅毛線帽、灰外套、比人還寬的背包，頂端綁著睡袋
  traveler: {
    legend: { a: C.berry, A: C.wine, h: C.sand, H: C.wood, t: C.stone, T: C.slate, c: C.wood, C: C.bark, b: C.soil, l: C.moss, L: C.forest, g: C.gold },
    down: `
.......ww.......
.....aaaaaa.....
....aaaaaaaa....
...AAAAAAAAAA...
...hhhkkkkhhh...
...hkekkkkekh...
...kkekkkkekk...
....kkkkkkkk....
..lltttttttll...
..c.btttttb.c...
..c.btttttb.c...
..C.TTTTTTT.C...`,
    up: `
.......ww.......
.....aaaaaa.....
....aaaaaaaa....
..llllllllllll..
..lLLLLLLLLLLl..
..cccccccccccc..
..cCCCCCCCCCCc..
..cccccccccccc..
..cccccggccccc..
..cccccccccccc..
..cccccccccccc..
..CCCCCCCCCCCC..`,
    right: `
.......ww.......
.....aaaaa......
....aaaaaaa.....
....AAAAAAA.....
.ll.hhkkkkk.....
lLLlhhkkkek.....
cccchhkkkek.....
ccccCbkkkk......
ccccbtttt.......
ccgcbtttt.......
cccc.tttt.......
CCCC.TTTT.......`,
    arm: { sleeve: C.stone, sleeveShade: C.slate, hand: C.skin, y: 8, len: 2, x: [3, 12] },
    legs: { rows: [C.bark, C.bark, C.bark, C.soil], shade: [C.soil, C.soil, C.soil, C.ink], y: 11, x: [5, 9] },
  },
  // 巡林員：歪戴的墨綠貝雷帽（金色徽章）、橘色領巾、橄欖綠制服、卡其褲
  warden: {
    legend: { a: C.forest, A: C.forestDark, b: C.gold, h: C.wood, H: C.bark, t: C.moss, T: C.forest, c: C.flame, C: C.ember },
    down: `
................
................
.....aaaaaaa....
...aaaaaaaaaaa..
...abaaaaaaaaaa.
...AAAAAAAAAAA..
...hkekkkkekh...
...hkekkkkekh...
....kkkkkkkk....
....tccccccT....
....ttCcccTt....
....tttCctTT....`,
    up: `
................
................
....aaaaaaa.....
..aaaaaaaaaaa...
.aaaaaaaaaaaa...
..AAAAAAAAAAA...
...hhhhhhhhhh...
...hhhhhhhhhh...
....hhhhhhhh....
....tccccccT....
....ttccccTt....
....tttccTTT....`,
    right: `
................
................
....aaaaaa......
...aaaaaaaaa....
..aaaaaaaaba....
...AAAAAAAAA....
...hhhkkkkek....
...hhhkkkkek....
....hhkkkkk.....
....cctttcc.....
...cc.tttt......
......ttTT......`,
    arm: { sleeve: C.moss, sleeveShade: C.forest, hand: C.skin, y: 9, len: 2, x: [3, 12] },
    legs: { rows: [C.sand, C.sand, C.bark], shade: [C.wood, C.wood, C.soil], y: 12, x: [5, 9] },
  },
  // 守林人・朔：深藍黑長髮高馬尾、深綠斗篷披到膝、金色葉形扣
  ranger: {
    legend: { h: C.navy, H: C.ink, l: C.denim, a: C.forest, A: C.forestDark, b: C.gold, t: C.sand, T: C.wood },
    down: `
................
.....hhhhhh.....
....hhhhhhhh....
...hhhhhhhhhh...
...hlhhhhhhhh...
...hhhhkkkkhh...
...hkekkkkekh...
...hkekkkkekh...
...hhkkkkkkhh...
..aahhttbthhaa..
..aaaatttaaaa...
..aaaattttaaaa..
..AAAA....AAAA..`,
    up: `
................
.....hhhhhh.....
....hhhhhhhh....
...hhhhhhhhhh...
...hHhhhhhhhh...
...hhhhbbhhhh...
...hhhhlhhhhh...
...hHhhlhhhHh...
...hhhhlhhhhh...
..aaaaalhaaaaa..
..aaaaalhaaaaa..
..aaaaaahaaaaa..
..AAAAAAAAAAAA..`,
    right: `
................
....hhhhhh......
...hhhhhhhh.....
..hhhhhhhhhh....
.hbhhhhhhhhh....
hhhhhhhlkkkh....
hh.hhhkkkkek....
hh..hhkkkkek....
h...hhkkkkk.....
...aaaattbt.....
..aaaaatttt.....
.aaaaaatttt.....
.AAAAA..........`,
    arm: { sleeve: C.forest, sleeveShade: C.forestDark, hand: C.skin, y: 9, len: 2, x: [3, 12] },
    legs: { rows: [C.slate, C.slate, C.bark], shade: [C.ink, C.ink, C.soil], y: 12, x: [5, 9] },
  },
  // 石門衛：灰石頭盔＋紅纓、面甲縫中的眼睛、寬肩甲、長矛
  gatekeeper: {
    legend: { a: C.ash, A: C.stone, S: C.slate, b: C.ember, B: C.flame, l: C.mist, t: C.ash, T: C.stone, u: C.mist, s: C.wood, p: C.paper },
    down: `
.......bB.......
......bBbb......
....aaabbaaa....
...aaaaaaaaaa..p
...alaaaaaaaa..s
...SSSSSSSSSS..s
...aSeSSSSeSa..s
...aakkkkkkaa..s
....akkkkkka...s
..tttttttttttt.s
..TTuuuuuuuuTT.s
...TuuullluuT..s
...TTTTTTTTTT..s`,
    up: `
.......bB.......
......bBbb......
....aaabbaaa....
p..aaaaaaaaaa...
s..aaaaaaaaaa...
s..aaaaaaaaaa...
s..aAaaaaaaAa...
s..aaaaaaaaaa...
s...AAAAAAAA....
s.tttttttttttt..
s.TTttttttttTT..
s..TttttttttT...
s..TTTTTTTTTT...`,
    right: `
....bBb.........
...bbBBb........
....aaaaaa......
...aaaaaaaa.....
...alaaaaaaa.p..
...aaSSSSSSS.s..
...aaaaSSeSS.s..
...aaaakkkkk.s..
....aaakkkk..s..
...tttttttt..s..
...TTuuuuu...s..
....Tuuuuu...s..
....TTTTTT...s..`,
    arm: { sleeve: C.stone, sleeveShade: C.slate, hand: C.ash, y: 10, len: 1, x: [2, 13] },
    legs: { rows: [C.slate, C.stone, C.slate], shade: [C.ink, C.slate, C.ink], y: 13, x: [5, 9] },
  },
  // 場主・嵐：往上炸開的銀白亂髮、深藍長大衣（金扣、開衩下擺）、青色圍巾
  boss: {
    legend: { h: C.mist, H: C.ash, l: C.paper, t: C.navy, T: C.ink, b: C.gold, s: C.tide, S: C.sea },
    down: `
...h..h..h..h...
...hh.hh.hhhh...
..hhhhhhlhhhhh..
...hhhhhhhhhh...
..hhhhhhhhhhhh..
...hHhkkkkhHh...
...heekkkkeeh...
...hkkkkkkkkh...
....kkkKKkkk....
...ssssssssss...
...tsStbbtsSt...
...tsttbbttst...
...ttttbbtttt...
...TTTT..TTTT...`,
    up: `
...h..h..h..h...
...hh.hh.hhhh...
..hhhhhhhhhhhh..
..hhhhhhhhhhhh..
..hhhhhhhhhhhh..
...hhhhhhhhhh...
...hhhhhhhhhh...
....hHhhhhHh....
...ssssssssss...
...tttSsttttt...
...ttttSsttt....
...tttttSstt....
...ttttttttt....
...TTTT..TTTT...`,
    right: `
....h..h.h......
...hhhhhhh.h....
.hhhhhhhlhhh....
hhhhhhhhhhhh....
.hhhhhhhkkkh....
..hhhhhkkkeh....
...hhhkkkkek....
....hhkkkkkk....
.ss.ssskkkk.....
ssssstttttb.....
.....tttttb.....
....tttttt......
...TTTTTTT......
..TTT...........`,
    arm: { sleeve: C.navy, sleeveShade: C.ink, hand: C.skin, y: 10, len: 1, x: [2, 13] },
    legs: { rows: [C.navy, C.slate, C.ink], shade: [C.ink, C.ink, C.ink], y: 12, x: [5, 9] },
  },
  // 觀眾：淡紫雙馬尾、橘色頭帶、紅白條紋衫、兩手的彩球
  fan: {
    legend: { h: C.lilac, H: C.dusk, a: C.flame, t: C.ember, T: C.emberDark, u: C.paper },
    down: `
................
......hhhh......
....hhhhhhhh....
...aaaaaaaaaa...
.hhhhhhhhhhhhhh.
hh.hhhkkkkhhh.hh
hh.hkekkkkekh.hh
.h.kkekkkkekk.h.
....kmkkkkmk....
....tttttttt....
....uuuuuuuu....
....tttttttt....`,
    up: `
................
......hhhh......
....hhhhhhhh....
...aaaaaaaaaa...
.hhhhhhhhhhhhhh.
hh.hhhhhhhhhh.hh
hh.hhhhhhhhhh.hh
.h.hhhhhhhhhh.h.
....HhhhhhhH....
....tttttttt....
....uuuuuuuu....
....tttttttt....`,
    right: `
................
.....hhhh.......
....hhhhhhh.....
...aaaaaaaaa....
..hhhhhhhhhh....
.hhhhhhkkkkk....
.hh.hhkkkkek....
..h.hhkkkkek....
.....hkkkkm.....
.....tttttt.....
.....uuuuuu.....
.....tttttt.....`,
    arm: { sleeve: C.ember, sleeveShade: C.emberDark, hand: C.spark, y: 9, len: 2, x: [3, 12], big: true },
    legs: { rows: [C.denim, C.denim, C.paper], shade: [C.navy, C.navy, C.mist], y: 12, x: [5, 9] },
  },
};

export const CHARACTER_IDS = Object.keys(SPECS);

function drawLegsFront(c: Canvas, s: CharSpec, frame: number): void {
  const { rows: cols, shade, y, x } = s.legs;
  const n = cols.length;
  x.forEach((lx, side) => {
    // 幀 1：右腳（side 1）抬起；幀 2：左腳抬起。抬起的腳整條短一格。
    const lifted = (frame === 1 && side === 1) || (frame === 2 && side === 0);
    for (let i = lifted ? 1 : 0; i < n; i++) {
      const row = lifted ? y + i - 1 : y + i;
      c.set(lx, row, cols[i]).set(lx + 1, row, i === n - 1 ? cols[i] : shade[i]);
    }
  });
}

function drawLegsSide(c: Canvas, s: CharSpec, frame: number): void {
  const { rows: cols, shade, y } = s.legs;
  const n = cols.length;
  const leg = (offsets: number[], colors: number[], shoeDx: number) => {
    for (let i = 0; i < n; i++) {
      const lx = 7 + offsets[i];
      if (i === n - 1) {
        c.set(lx, y + i, colors[i]).set(lx + 1, y + i, colors[i]).set(lx + shoeDx, y + i, colors[i]);
      } else c.set(lx, y + i, colors[i]).set(lx + 1, y + i, colors[i]);
    }
  };
  const spread = (sign: number) => Array.from({ length: n }, (_, i) => Math.round((sign * i * 2) / (n - 1)));
  if (frame === 0) {
    leg(new Array(n).fill(0), cols, 2);
    return;
  }
  // 幀 1：近側腳在前；幀 2：近側腳在後。遠側腳用暗色。
  const nearFwd = frame === 1;
  leg(spread(nearFwd ? -1 : 1), shade, 2);
  leg(spread(nearFwd ? 1 : -1), cols, 2);
}

function drawArmsFront(c: Canvas, s: CharSpec, frame: number): void {
  const a = s.arm;
  a.x.forEach((ax, side) => {
    // 抬起的腳對側的手往前擺（手低一格），同側的手往後（手高一格）
    let dy = 0;
    if (frame === 1) dy = side === 0 ? 1 : -1;
    if (frame === 2) dy = side === 1 ? 1 : -1;
    const len = Math.max(1, a.len + dy);
    for (let i = 0; i < len; i++) c.set(ax, a.y + i, i === len - 1 && len > 1 ? a.sleeveShade : a.sleeve);
    const hy = a.y + len;
    c.set(ax, hy, a.hand);
    if (a.big) c.set(side === 0 ? ax - 1 : ax + 1, hy, a.hand).set(ax, hy + 1, a.hand).set(side === 0 ? ax - 1 : ax + 1, hy - 1, a.hand);
  });
}

function drawArmSide(c: Canvas, s: CharSpec, frame: number): void {
  const a = s.arm;
  const x0 = 7;
  // 幀 0：垂在身側；幀 1：往後擺；幀 2：往前擺
  const dx = frame === 0 ? 0 : frame === 1 ? -1 : 1;
  for (let i = 0; i < a.len; i++) c.set(x0 + (i === a.len - 1 ? dx : 0), a.y + i, i === 0 ? a.sleeve : a.sleeveShade);
  const hx = x0 + dx * 2, hy = a.y + a.len - (frame === 0 ? 0 : 0);
  c.set(hx, hy, a.hand);
  if (a.big) c.set(hx + (dx || 1), hy, a.hand).set(hx, hy + 1, a.hand).set(hx + (dx || 1), hy + 1, a.hand);
}

export function drawCharacter(id: string, dir: CharDir, frame: number): Canvas {
  const s = SPECS[id];
  if (!s) throw new Error(`no art for character ${id}`);
  if (dir === 'left') return drawCharacter(id, 'right', frame).flipX();
  const c = new Canvas(16, 16);
  const legend = { ...BASE, ...s.legend };
  if (dir === 'right') {
    drawLegsSide(c, s, frame);
    c.stamp(0, 0, rows(s.right), legend);
    drawArmSide(c, s, frame);
  } else {
    drawLegsFront(c, s, frame);
    c.stamp(0, 0, rows(dir === 'down' ? s.down : s.up), legend);
    drawArmsFront(c, s, frame);
  }
  return c.outline();
}
