import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=fileURLToPath(new URL('../../../',import.meta.url));
const output=fileURLToPath(new URL('../test-results/',import.meta.url));fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript':file.endsWith('.jpg')?'image/jpeg':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true});
try {
 for(const viewport of [{width:1440,height:900},{width:390,height:844}]){
 const page=await browser.newPage({viewport});const errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.addInitScript(()=>{const NativeWorker=window.Worker;window.testWorkers=[];window.Worker=class extends NativeWorker{constructor(...args){super(...args);window.testWorkers.push(this);}};});
 await page.goto(origin+'/web/150-brick-rts.html');await page.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const waitNotice=pattern=>page.waitForFunction(p=>new RegExp(p).test(document.querySelector('#notice').textContent),pattern);
 const initial=await page.locator('#hash').innerText();
 assert.equal(await page.locator('#map').getAttribute('data-renderer'),'webgl2');
 const initialScene=await page.locator('#map').screenshot();await page.locator('#zoom-in').click();await page.locator('#zoom-in').click();await page.locator('#rotate-view').click();assert.equal(await page.locator('#hash').innerText(),initial);assert.notDeepEqual(await page.locator('#map').screenshot(),initialScene);await page.screenshot({path:output+`view-close-${viewport.width}.png`,fullPage:true});await page.locator('#reset-view').click();
 await page.locator('[data-unit="2"]').click();assert.equal(await page.locator('[data-unit="2"]').getAttribute('aria-pressed'),'true');
 await page.locator('#move').click();await waitNotice('已排入');assert.match(await page.locator('#notice').innerText(),/已排入/);
 await page.locator('#step').click();await page.waitForFunction(()=>document.querySelector('#tick').textContent==='1');assert.equal(await page.locator('#tick').innerText(),'1');assert.notEqual(await page.locator('#hash').innerText(),initial);
 await page.locator('#save').click();await waitNotice('已儲存');const saved=await page.locator('#hash').innerText();await page.locator('#step').click();await page.locator('#load').click();await waitNotice('已恢復');assert.equal(await page.locator('#hash').innerText(),saved);
 await page.locator('#replay').click();await waitNotice('重播一致');assert.match(await page.locator('#notice').innerText(),/重播一致/);
 await page.locator('#pause').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>4);await page.locator('#pause').click();const paused=await page.locator('#tick').innerText();await page.waitForTimeout(150);assert.equal(await page.locator('#tick').innerText(),paused);
 await page.evaluate(()=>localStorage.setItem('brick-rts:sandbox:1','broken'));await page.locator('#load').click();await waitNotice('讀取失敗');assert.match(await page.locator('#notice').innerText(),/讀取失敗/);assert.equal(await page.locator('#tick').innerText(),paused);
 await page.locator('#seed').fill('7');await page.locator('#restart').click();await waitNotice('已建立新沙盒');assert.equal(await page.locator('#tick').innerText(),'0');assert.notEqual(await page.locator('#hash').innerText(),initial);
 await page.locator('#map').scrollIntoViewIfNeeded();const map=await page.locator('#map').boundingBox();const mapScale=map.height/(2*Math.max(10.5,12/(map.width/map.height)));await page.mouse.click(map.x+map.width*.5-Math.SQRT2*mapScale,map.y+map.height*.5+mapScale);await waitNotice('指令已排入');assert.match(await page.locator('#notice').innerText(),/指令已排入/);
 await page.locator('summary').click();await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/驗證通過/);
 await page.locator('#exact').check();await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/版本/);await page.locator('#exact').uncheck();
 await page.locator('#rules-json').fill('{bad');await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/JSON 格式錯誤/);
 await page.locator('#reset-rules').click();const r=JSON.parse(await page.locator('#rules-json').inputValue());r.entries[0].cost.food=-1;await page.locator('#rules-json').fill(JSON.stringify(r));await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/成本/);
 await page.locator('#reset-rules').click();const downloadEvent=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadEvent;assert.equal(download.suggestedFilename(),'brick-rts-rules.json');
 await page.locator('summary').click();await page.locator('#seed').fill('260925');await page.locator('#restart').click();await waitNotice('已建立新沙盒');assert.equal(await page.locator('#hash').innerText(),initial);
 await page.locator('#move').click();await waitNotice('已排入');await page.locator('#step').click();await page.waitForFunction(()=>document.querySelector('#tick').textContent==='1');
 await page.locator('#restart').click();await waitNotice('已建立新沙盒');
 await page.locator('#target-x').fill('4');await page.locator('#target-y').fill('5');await page.locator('#move').click();await waitNotice('占地');assert.equal(await page.locator('#hash').innerText(),initial);
 await page.locator('#target-x').fill('3.5');await page.locator('#target-y').fill('3');await page.locator('#move').click();await waitNotice('已排入');
 await page.evaluate(()=>{window.routeSamples=[];new MutationObserver(()=>{const m=document.querySelector('#position').textContent.match(/\(([\d.]+), ([\d.]+)\)/);if(m)window.routeSamples.push([Number(m[1]),Number(m[2])]);}).observe(document.querySelector('#position'),{childList:true});});
 await page.locator('#pause').click();await page.waitForFunction(()=>document.querySelector('#position').textContent.includes('(3.5, 3.0)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:25000});await page.locator('#pause').click();
 const samples=await page.evaluate(()=>window.routeSamples);assert.ok(samples.length>30);assert.ok(samples.some(([x])=>x<2.6||x>5.6));assert.ok(samples.every(([x,y])=>!(x>=2.6&&x<=5.6&&y>=3.6&&y<=6.4)));
 await page.screenshot({path:output+`house-route-${viewport.width}.png`,fullPage:true});
 await page.locator('#replay').click();await waitNotice('重播一致');
 const beforeFailure=await page.locator('#hash').innerText();
 await page.evaluate(()=>window.testWorkers.at(-1).dispatchEvent(new ErrorEvent('error',{message:'injected worker transport failure',cancelable:true})));
 await page.locator('#worker-retry').waitFor({state:'visible'});assert.equal(await page.locator('#move').isDisabled(),true);
 await page.locator('#worker-retry').click();await waitNotice('模擬已連線');assert.equal(await page.locator('#hash').innerText(),beforeFailure);assert.equal(await page.locator('#move').isEnabled(),true);
 await page.locator('#replay').click();await waitNotice('重播一致');
 await page.locator('#restart').click();await waitNotice('已建立新沙盒');
 await page.screenshot({path:output+`desktop-${viewport.width}.png`,fullPage:true});
 if(viewport.width===1440){await page.evaluate(()=>scrollTo(0,0));const shot=(await page.screenshot({type:'png'})).toString('base64');const thumb=await page.evaluate(async src=>{const img=new Image();img.src='data:image/png;base64,'+src;await img.decode();const c=document.createElement('canvas');c.width=640;c.height=400;const g=c.getContext('2d');g.imageSmoothingQuality='high';g.drawImage(img,0,0,640,400);return c.toDataURL('image/jpeg',.85).split(',')[1];},shot);fs.writeFileSync(root+'thumbs/150.jpg',Buffer.from(thumb,'base64'));}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.close();console.log(`PASS ${viewport.width}: movement, ticks, save/load, replay, JSON validation, export, layout, errors, network`);
 }
 const fogPage=await browser.newPage({viewport:{width:1440,height:900}});
 await fogPage.addInitScript(()=>{const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{constructor(...args){super(...args);this.addEventListener('message',event=>{if(event.data.ok)window.lastFogView=event.data;});}};});
 await fogPage.goto(origin+'/web/150-brick-rts.html');await fogPage.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');
 const fogUnits=()=>fogPage.evaluate(()=>Array.from(new Int32Array(window.lastFogView.positions)).filter((_,i)=>i%7===0));
 assert.deepEqual(await fogUnits(),[1,2,3]);await fogPage.screenshot({path:output+'fog-unexplored.png',fullPage:true});
 await fogPage.locator('#target-x').fill('11');await fogPage.locator('#target-y').fill('9');await fogPage.locator('#move').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已排入'));await fogPage.locator('#pause').click();await fogPage.waitForFunction(()=>document.querySelector('#position').textContent.includes('(11.0, 9.0)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:30000});await fogPage.locator('#pause').click();
 assert.ok((await fogUnits()).includes(4));assert.ok(await fogPage.evaluate(()=>window.lastFogView.known.some(k=>k.obstacle.red)));await fogPage.screenshot({path:output+'fog-enemy-visible.png',fullPage:true});
 await fogPage.locator('#target-x').fill('3.5');await fogPage.locator('#target-y').fill('7');await fogPage.locator('#move').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已排入'));await fogPage.locator('#pause').click();await fogPage.waitForFunction(()=>document.querySelector('#position').textContent.includes('(3.5, 7.0)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:30000});await fogPage.locator('#pause').click();
 assert.deepEqual(await fogUnits(),[1,2,3]);assert.ok(await fogPage.evaluate(()=>window.lastFogView.fog.includes(1)&&window.lastFogView.known.some(k=>k.obstacle.red&&k.lastSeenTick<window.lastFogView.tick)));await fogPage.screenshot({path:output+'fog-retreated.png',fullPage:true});
 await fogPage.locator('#save').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已儲存'));const fogHash=await fogPage.locator('#hash').innerText();await fogPage.locator('#load').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已恢復'));assert.equal(await fogPage.locator('#hash').innerText(),fogHash);await fogPage.locator('#replay').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('重播一致'));await fogPage.close();console.log('PASS fog exploration + enemy reveal + retreat hides unit + frozen building memory + save/replay');
 const fault=await browser.newPage();
 await fault.addInitScript(()=>{const RealWorker=window.Worker;let first=true;window.dropAdvance=false;window.Worker=class extends RealWorker{constructor(...args){if(first){first=false;throw Error('injected startup failure');}super(...args);}postMessage(...args){if(window.dropAdvance&&args[0]?.operation?.kind==='advance')return;super.postMessage(...args);}};});
 await fault.goto(origin+'/web/150-brick-rts.html');await fault.locator('#worker-retry').waitFor({state:'visible'});assert.equal(await fault.locator('#step').isDisabled(),true);
 await fault.locator('#worker-retry').click();await fault.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');
 const checkpoint=await fault.locator('#hash').innerText();await fault.evaluate(()=>window.dropAdvance=true);await fault.locator('#step').click();
 await fault.locator('#worker-retry').waitFor({state:'visible',timeout:8000});assert.equal(await fault.locator('#step').isDisabled(),true);assert.equal(await fault.locator('#hash').innerText(),checkpoint);
 await fault.evaluate(()=>window.dropAdvance=false);await fault.locator('#worker-retry').click();await fault.locator('#worker-retry').waitFor({state:'hidden'});assert.equal(await fault.locator('#hash').innerText(),checkpoint);
 await fault.locator('#step').click();await fault.waitForFunction(()=>document.querySelector('#tick').textContent==='1');
 await fault.close();console.log('PASS Worker constructor failure + transport timeout + recovery + resumed tick');
 const models=await browser.newPage({viewport:{width:1200,height:900}});const modelErrors=[];models.on('pageerror',e=>modelErrors.push(e.message));await models.goto(origin+'/web/150-brick-rts-models.html');await models.waitForFunction(()=>document.querySelector('#stats').textContent.includes('Draw calls'));for(let i=0;i<4;i++){await models.screenshot({path:output+`model-angle-${i}.png`,fullPage:true});await models.locator('#turn').click();}await models.locator('#near').click();await models.locator('#near').click();await models.screenshot({path:output+'model-near.png',fullPage:true});await models.locator('#reset').click();await models.locator('#far').click();await models.screenshot({path:output+'model-far.png',fullPage:true});console.log('MODEL',await models.locator('#stats').innerText());assert.deepEqual(modelErrors,[]);await models.close();
 const loss=await browser.newPage();await loss.goto(origin+'/web/150-brick-rts.html');await loss.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');await loss.evaluate(()=>document.querySelector('#map').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await loss.locator('#boot-error').waitFor({state:'visible'});assert.equal(await loss.locator('#move').isDisabled(),true);assert.equal(await loss.locator('#save').isEnabled(),true);await loss.locator('#save').click();await loss.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已儲存'));await loss.close();console.log('PASS model viewer and real WebGL context loss preserves save access');
 const unavailable=await browser.newPage();await unavailable.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return kind==='webgl2'?null:original.call(this,kind,...args);};});await unavailable.goto(origin+'/web/150-brick-rts.html');await unavailable.locator('#boot-error').waitFor({state:'visible'});assert.match(await unavailable.locator('#boot-error').innerText(),/WebGL2/);assert.equal(await unavailable.locator('#move').isDisabled(),true);await unavailable.close();console.log('PASS WebGL2 unavailable reports error and disables simulation input');
 const page=await browser.newPage();await page.goto(origin+'/index.html');await page.locator('[data-kind="web"]').click();await page.locator('[data-cat="遊戲敘事"]').click();await page.locator('#q').fill('Brick RTS');await page.waitForTimeout(100);assert.equal(await page.locator('[data-open="150"]').count()>0,true);console.log('PASS catalog search + game category');await page.close();
 console.log('Browser:',browser.version());console.log('Screenshots:',output);
}finally{await browser.close();server.close();}
