import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
async function menu(p){if(await p.locator('#menu').isHidden())await p.locator('#menu-open').click();return p;}
const root=fileURLToPath(new URL('../../../',import.meta.url));
const output=fileURLToPath(new URL('../test-results/',import.meta.url));fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript':file.endsWith('.jpg')?'image/jpeg':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true});
try {
 for(const viewport of [{width:1440,height:900},{width:390,height:844}]){
 const page=await browser.newPage({viewport});const errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.addInitScript(()=>{const NativeWorker=window.Worker;window.testWorkers=[];window.Worker=class extends NativeWorker{constructor(...args){super(...args);window.testWorkers.push(this);}};});
 await page.goto(origin+'/web/150-brick-rts.html?debug=1');await page.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 // First-use 007: run controls sit above the scene inside the first screen, no scrolling needed.
 {const run=await page.locator('#pause').boundingBox(),scene=await page.locator('#map').boundingBox();assert.ok(run.y+run.height<=scene.y&&run.y+run.height<=viewport.height,JSON.stringify({run,scene}));}
 const waitNotice=pattern=>page.waitForFunction(p=>new RegExp(p).test(document.querySelector('#notice').textContent),pattern);
 await page.locator('#fog-debug summary').click();assert.equal(await page.locator('.fog-grid span').count(),256);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.match(await page.locator('.fog-cell-info').textContent(),/目前可見/);await page.locator('#fog-debug summary').click();
 const initial=await page.locator('#hash').innerText();
 assert.equal(await page.locator('#map').getAttribute('data-renderer'),'webgl2');
 const initialScene=await page.locator('#map').screenshot();await page.locator('#zoom-in').click();await page.locator('#zoom-in').click();await page.locator('#rotate-view').click();assert.equal(await page.locator('#hash').innerText(),initial);assert.notDeepEqual(await page.locator('#map').screenshot(),initialScene);await page.screenshot({path:output+`view-close-${viewport.width}.png`,fullPage:true});await page.locator('#reset-view').click();
 await page.locator('[data-unit="2"]').click();assert.equal(await page.locator('[data-unit="2"]').getAttribute('aria-pressed'),'true');
 await page.locator('#move').click();await waitNotice('已排入');assert.match(await page.locator('#notice').innerText(),/已排入/);
 await page.locator('#step').click();await page.waitForFunction(()=>document.querySelector('#tick').textContent==='1');assert.equal(await page.locator('#tick').innerText(),'1');assert.notEqual(await page.locator('#hash').innerText(),initial);
 await (await menu(page)).locator('#save').click();await waitNotice('已儲存');const saved=await page.locator('#hash').innerText();await page.locator('#step').click();await (await menu(page)).locator('#load').click();await waitNotice('已恢復');assert.equal(await page.locator('#hash').innerText(),saved);
 await (await menu(page)).locator('#replay').click();await waitNotice('重播一致');assert.match(await page.locator('#notice').innerText(),/重播一致/);
 await page.locator('#pause').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>4);await page.locator('#pause').click();const paused=await page.locator('#tick').innerText();await page.waitForTimeout(150);assert.equal(await page.locator('#tick').innerText(),paused);
 await page.evaluate(()=>localStorage.setItem('brick-rts:sandbox:1','broken'));await (await menu(page)).locator('#load').click();await waitNotice('讀取失敗');assert.match(await page.locator('#notice').innerText(),/讀取失敗/);assert.equal(await page.locator('#tick').innerText(),paused);
 await (await menu(page)).locator('#seed').fill('7');await (await menu(page)).locator('#restart').click();await waitNotice('已建立新沙盒');assert.equal(await page.locator('#tick').innerText(),'0');assert.notEqual(await page.locator('#hash').innerText(),initial);
 await page.locator('#map').scrollIntoViewIfNeeded();const map=await page.locator('#map').boundingBox();const mapScale=map.height/(2*Math.max(10.5,12/(map.width/map.height)));await page.mouse.click(map.x+map.width*.5-Math.SQRT2*mapScale,map.y+map.height*.5+mapScale,{button:'right'});await waitNotice('指令已排入');assert.match(await page.locator('#notice').innerText(),/指令已排入/);
 await page.locator('#rules-inspector summary').click();await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/驗證通過/);
 await page.locator('#exact').check();await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/版本/);await page.locator('#exact').uncheck();
 await page.locator('#rules-json').fill('{bad');await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/JSON 格式錯誤/);
 await page.locator('#reset-rules').click();const r=JSON.parse(await page.locator('#rules-json').inputValue());r.entries[0].cost.food=-1;await page.locator('#rules-json').fill(JSON.stringify(r));await page.locator('#validate').click();assert.match(await page.locator('#validation').innerText(),/成本/);
 await page.locator('#reset-rules').click();const downloadEvent=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadEvent;assert.equal(download.suggestedFilename(),'brick-rts-rules.json');
 await page.locator('#rules-inspector summary').click();await (await menu(page)).locator('#seed').fill('260925');await (await menu(page)).locator('#restart').click();await waitNotice('已建立新沙盒');assert.equal(await page.locator('#hash').innerText(),initial);
 await page.locator('#move').click();await waitNotice('已排入');await page.locator('#step').click();await page.waitForFunction(()=>document.querySelector('#tick').textContent==='1');
 await (await menu(page)).locator('#restart').click();await waitNotice('已建立新沙盒');
 // A move exactly into a pier is accepted: the villager walks to the nearest open node (no fog-revealing refusal).
 await page.locator('#target-x').fill('3');await page.locator('#target-y').fill('4.5');await page.locator('#move').click();await waitNotice('已排入');await (await menu(page)).locator('#restart').click();await waitNotice('已建立新沙盒');assert.equal(await page.locator('#hash').innerText(),initial);
 await page.locator('#target-x').fill('3.5');await page.locator('#target-y').fill('3');await page.locator('#move').click();await waitNotice('已排入');
 await page.evaluate(()=>{window.routeSamples=[];new MutationObserver(()=>{const m=document.querySelector('#position').textContent.match(/\(([\d.]+), ([\d.]+)\)/);if(m)window.routeSamples.push([Number(m[1]),Number(m[2])]);}).observe(document.querySelector('#position'),{childList:true});});
 await page.locator('#pause').click();await page.waitForFunction(()=>document.querySelector('#position').textContent.includes('(3.5, 3.0)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:25000});await page.locator('#pause').click();
 const samples=await page.evaluate(()=>window.routeSamples);// Route crosses the town-center gate on its centre line and never enters a hall pier.
 assert.ok(samples.length>30);assert.ok(samples.some(([x,y])=>x===4&&y>=5&&y<=5.25));assert.ok(samples.every(([x,y])=>!(y>=3.6&&y<=5.2&&((x>=2.7&&x<=3.35)||(x>=4.65&&x<=5.3)))));
 await page.screenshot({path:output+`town-center-route-${viewport.width}.png`,fullPage:true});
 await (await menu(page)).locator('#replay').click();await waitNotice('重播一致');
 const beforeFailure=await page.locator('#hash').innerText();
 await page.evaluate(()=>window.testWorkers.at(-1).dispatchEvent(new ErrorEvent('error',{message:'injected worker transport failure',cancelable:true})));
 await page.locator('#worker-retry').waitFor({state:'visible'});assert.equal(await page.locator('#move').isDisabled(),true);
 await page.locator('#worker-retry').click();await waitNotice('模擬已連線');assert.equal(await page.locator('#hash').innerText(),beforeFailure);assert.equal(await page.locator('#move').isEnabled(),true);
 await (await menu(page)).locator('#replay').click();await waitNotice('重播一致');
 await (await menu(page)).locator('#restart').click();await waitNotice('已建立新沙盒');
 await page.screenshot({path:output+`desktop-${viewport.width}.png`,fullPage:true});
 // The portfolio thumbnail is taken from the normal (non-debug) game screen in tests/first-use-hud.mjs.
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.close();console.log(`PASS ${viewport.width}: movement, ticks, save/load, replay, JSON validation, export, layout, errors, network`);
 }
 const fogPage=await browser.newPage({viewport:{width:1440,height:900}});
 await fogPage.addInitScript(()=>{const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{constructor(...args){super(...args);this.addEventListener('message',event=>{if(event.data.ok)window.lastFogView=event.data;});}};});
 await fogPage.goto(origin+'/web/150-brick-rts.html?debug=1');await fogPage.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');
 // UNIT_STRIDE in packages/sim/protocol.ts (locked by tests/worker.test.ts).
 const fogUnits=()=>fogPage.evaluate(()=>Array.from(new Int32Array(window.lastFogView.positions)).filter((_,i)=>i%15===0));
 await fogPage.locator('#fog-debug summary').click();await fogPage.locator('[name="fog-x"]').fill('11');await fogPage.locator('[name="fog-y"]').fill('4');assert.doesNotMatch(await fogPage.locator('.fog-memories').textContent(),/紅方/);
 assert.deepEqual(await fogUnits(),[1,2,3]);await fogPage.screenshot({path:output+'fog-unexplored.png',fullPage:true});
 await fogPage.locator('#target-x').fill('11');await fogPage.locator('#target-y').fill('9');await fogPage.locator('#move').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已排入'));await fogPage.locator('#pause').click();await fogPage.waitForFunction(()=>document.querySelector('#position').textContent.includes('(11.0, 9.0)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:30000});await fogPage.locator('#pause').click();
 assert.ok((await fogUnits()).includes(4));assert.ok(await fogPage.evaluate(()=>window.lastFogView.known.some(k=>k.obstacle.red)));assert.match(await fogPage.locator('.fog-memories').textContent(),/紅方/);await fogPage.screenshot({path:output+'fog-enemy-visible.png',fullPage:true});
 await fogPage.locator('#target-x').fill('3.5');await fogPage.locator('#target-y').fill('7');await fogPage.locator('#move').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已排入'));await fogPage.locator('#pause').click();await fogPage.waitForFunction(()=>document.querySelector('#position').textContent.includes('(3.5, 7.0)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:30000});await fogPage.locator('#pause').click();
 assert.deepEqual(await fogUnits(),[1,2,3]);assert.ok(await fogPage.evaluate(()=>window.lastFogView.fog.includes(1)&&window.lastFogView.known.some(k=>k.obstacle.red&&k.lastSeenTick<window.lastFogView.tick)));assert.match(await fogPage.locator('.fog-cell-info').textContent(),/已探索／目前不可見/);const remembered=await fogPage.locator('.fog-memories').textContent();await fogPage.locator('#step').click();await fogPage.waitForFunction(()=>document.querySelector('.fog-cell-info').textContent.includes('tick '+document.querySelector('#tick').textContent));assert.equal((await fogPage.locator('.fog-memories').textContent()).match(/紅方[^；]+/)[0],remembered.match(/紅方[^；]+/)[0]);await fogPage.screenshot({path:output+'fog-retreated.png',fullPage:true});
 await (await menu(fogPage)).locator('#save').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已儲存'));const fogHash=await fogPage.locator('#hash').innerText();await (await menu(fogPage)).locator('#load').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已恢復'));assert.equal(await fogPage.locator('#hash').innerText(),fogHash);await (await menu(fogPage)).locator('#replay').click();await fogPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('重播一致'));await fogPage.close();console.log('PASS fog exploration + enemy reveal + retreat hides unit + frozen building memory + save/replay');
 const terrainPage=await browser.newPage({viewport:{width:1440,height:900}});const terrainErrors=[];terrainPage.on('pageerror',e=>terrainErrors.push(e.message));await terrainPage.addInitScript(()=>{const NativeWorker=window.Worker;window.terrainWorkers=[];window.Worker=class extends NativeWorker{constructor(...args){super(...args);window.terrainWorkers.push(this);}};});
 await terrainPage.goto(origin+'/web/150-brick-rts.html?debug=1');await terrainPage.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');await (await menu(terrainPage)).locator('#layout').selectOption('acceptance');await (await menu(terrainPage)).locator('#restart').click();await terrainPage.waitForFunction(()=>document.querySelector('#world-label').textContent.includes('高地'));
 await terrainPage.locator('#map').scrollIntoViewIfNeeded();const terrainRect=await terrainPage.locator('#map').boundingBox(),terrainScale=terrainRect.height/(2*Math.max(10.5,12/(terrainRect.width/terrainRect.height)));await terrainPage.mouse.click(terrainRect.x+terrainRect.width/2-9/Math.SQRT2*terrainScale,terrainRect.y+terrainRect.height/2+(1-1/Math.SQRT2)*terrainScale,{button:'right'});await terrainPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已排入'));await terrainPage.locator('#pause').click();await terrainPage.waitForFunction(()=>document.querySelector('#position').textContent.includes('(4.5, 13.5)')&&document.querySelector('#position').textContent.includes('待命'),{},{timeout:30000});await terrainPage.locator('#pause').click();await terrainPage.screenshot({path:output+'playable-highland.png',fullPage:true});
 await (await menu(terrainPage)).locator('#save').click();await terrainPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已儲存'));const terrainHash=await terrainPage.locator('#hash').innerText();await (await menu(terrainPage)).locator('#layout').selectOption('coast');await (await menu(terrainPage)).locator('#restart').click();await terrainPage.waitForFunction(()=>document.querySelector('#world-label').textContent.includes('海岸'));await terrainPage.locator('#target-x').fill('8');await terrainPage.locator('#target-y').fill('14');await terrainPage.locator('#move').click();/* a land unit ordered into the sea walks to the shore instead of being refused */await terrainPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已排入'));
 await (await menu(terrainPage)).locator('#load').click();await terrainPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已恢復'));assert.equal(await terrainPage.locator('#layout').inputValue(),'acceptance');assert.equal(await terrainPage.locator('#hash').innerText(),terrainHash);
 await terrainPage.evaluate(()=>window.terrainWorkers.at(-1).dispatchEvent(new ErrorEvent('error',{message:'terrain recovery check',cancelable:true})));await terrainPage.locator('#worker-retry').waitFor({state:'visible'});await terrainPage.locator('#worker-retry').click();await terrainPage.locator('#worker-retry').waitFor({state:'hidden'});assert.equal(await terrainPage.locator('#hash').innerText(),terrainHash);await (await menu(terrainPage)).locator('#replay').click();await terrainPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('重播一致'));assert.deepEqual(terrainErrors,[]);await terrainPage.close();console.log('PASS playable highland ground picking + ascent + sea order stops at the shore + map restore + Worker recovery');
 const fault=await browser.newPage();
 await fault.addInitScript(()=>{const RealWorker=window.Worker;let first=true;window.dropAdvance=false;window.Worker=class extends RealWorker{constructor(...args){if(first){first=false;throw Error('injected startup failure');}super(...args);}postMessage(...args){if(window.dropAdvance&&args[0]?.operation?.kind==='advance')return;super.postMessage(...args);}};});
 await fault.goto(origin+'/web/150-brick-rts.html?debug=1');await fault.locator('#worker-retry').waitFor({state:'visible'});assert.equal(await fault.locator('#step').isDisabled(),true);
 await fault.locator('#worker-retry').click();await fault.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');
 const checkpoint=await fault.locator('#hash').innerText();await fault.evaluate(()=>window.dropAdvance=true);await fault.locator('#step').click();
 await fault.locator('#worker-retry').waitFor({state:'visible',timeout:8000});assert.equal(await fault.locator('#step').isDisabled(),true);assert.equal(await fault.locator('#hash').innerText(),checkpoint);
 await fault.evaluate(()=>window.dropAdvance=false);await fault.locator('#worker-retry').click();await fault.locator('#worker-retry').waitFor({state:'hidden'});assert.equal(await fault.locator('#hash').innerText(),checkpoint);
 await fault.locator('#step').click();await fault.waitForFunction(()=>document.querySelector('#tick').textContent==='1');
 await fault.close();console.log('PASS Worker constructor failure + transport timeout + recovery + resumed tick');
 const models=await browser.newPage({viewport:{width:1200,height:900}});const modelErrors=[];models.on('pageerror',e=>modelErrors.push(e.message));await models.goto(origin+'/web/150-brick-rts-models.html');await models.waitForFunction(()=>document.querySelector('#stats').textContent.includes('Draw calls'));for(let i=0;i<4;i++){await models.screenshot({path:output+`model-angle-${i}.png`,fullPage:true});await models.locator('#turn').click();}await models.locator('#near').click();await models.locator('#near').click();await models.screenshot({path:output+'model-near.png',fullPage:true});await models.locator('#reset').click();await models.locator('#far').click();await models.screenshot({path:output+'model-far.png',fullPage:true});console.log('MODEL',await models.locator('#stats').innerText());await models.locator('#reset').click();const meadowImage=await models.locator('#scene').screenshot();for(const layout of ['coast','acceptance']){await models.locator('#layout').selectOption(layout);assert.notDeepEqual(await models.locator('#scene').screenshot(),meadowImage);await models.screenshot({path:output+`map-${layout}.png`,fullPage:true});assert.match(await models.locator('#layout-note').innerText(),/不執行對局/);}await models.locator('#layout').selectOption('meadow');assert.deepEqual(await models.locator('#scene').screenshot(),meadowImage);await models.locator('#focus-unit').click();for(const [pose,tool] of [['work','axe'],['work','pick'],['work','sickle'],['work','hammer'],['carry','basket'],['attack','sword'],['hit','none'],['death','none']]){await models.locator('#pose').selectOption(pose);await models.locator('#tool').selectOption(tool);await models.screenshot({path:output+`rig-${pose}-${tool}.png`,fullPage:true});}await models.locator('#pose').selectOption('walk');await models.locator('#animate').check();const movingRig=await models.screenshot();await models.waitForTimeout(170);assert.notDeepEqual(await models.screenshot(),movingRig);await models.locator('#animate').uncheck();await models.locator('#pose').selectOption('idle');await models.locator('#tool').selectOption('none');assert.deepEqual(modelErrors,[]);await models.close();console.log('PASS jointed rig + tool sockets + pose previews + motion playback');console.log('PASS coastal + hand-built map viewer switching and meadow restoration');
 const loss=await browser.newPage();await loss.goto(origin+'/web/150-brick-rts.html?debug=1');await loss.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');await loss.evaluate(()=>document.querySelector('#map').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await loss.locator('#boot-error').waitFor({state:'visible'});assert.equal(await loss.locator('#move').isDisabled(),true);assert.equal(await loss.locator('#save').isEnabled(),true);await (await menu(loss)).locator('#save').click();await loss.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已儲存'));await loss.close();console.log('PASS model viewer and real WebGL context loss preserves save access');
 const renderFault=await browser.newPage();const renderErrors=[];renderFault.on('pageerror',error=>renderErrors.push(error.message));await renderFault.goto(origin+'/web/150-brick-rts.html?debug=1');await renderFault.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');await renderFault.locator('#pause').click();await renderFault.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>3);
 await renderFault.locator('#map').evaluate(canvas=>{const gl=canvas.getContext('webgl2');for(const method of ['drawElements','drawArrays','drawElementsInstanced','drawArraysInstanced'])gl[method]=()=>{throw Error('injected sandbox render failure');};});
 await renderFault.locator('#boot-error').waitFor({state:'visible'});assert.match(await renderFault.locator('#boot-error').textContent(),/injected sandbox render failure/);assert.equal(await renderFault.locator('#pause').getAttribute('aria-pressed'),'false');assert.equal(await renderFault.locator('#move').isDisabled(),true);assert.equal(await renderFault.locator('#save').isEnabled(),true);
 // Let an already admitted Worker advance finish, then require the paused tick to stay fixed.
 await renderFault.waitForTimeout(150);const stoppedTick=await renderFault.locator('#tick').textContent();await renderFault.waitForTimeout(150);assert.equal(await renderFault.locator('#tick').textContent(),stoppedTick);
 await (await menu(renderFault)).locator('#save').click();await renderFault.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已儲存'));const savedHash=await renderFault.locator('#hash').textContent();await renderFault.screenshot({path:output+'sandbox-render-failure.png',fullPage:true});assert.deepEqual(renderErrors,[]);
 await renderFault.reload();await renderFault.waitForFunction(()=>document.querySelector('#hash').textContent!=='—');await (await menu(renderFault)).locator('#load').click();await renderFault.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已恢復'));assert.equal(await renderFault.locator('#hash').textContent(),savedHash);assert.equal(await renderFault.locator('#tick').textContent(),stoppedTick);await (await menu(renderFault)).locator('#replay').click();await renderFault.waitForFunction(()=>document.querySelector('#notice').textContent.includes('重播一致'));await renderFault.locator('#step').click();await renderFault.waitForFunction(t=>Number(document.querySelector('#tick').textContent)>Number(t),stoppedTick);await renderFault.close();console.log('PASS render exception pauses simulation, preserves save, reload/load/replay and resume');
 const unavailable=await browser.newPage();await unavailable.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return kind==='webgl2'?null:original.call(this,kind,...args);};});await unavailable.goto(origin+'/web/150-brick-rts.html?debug=1');await unavailable.locator('#boot-error').waitFor({state:'visible'});assert.match(await unavailable.locator('#boot-error').innerText(),/WebGL2/);assert.equal(await unavailable.locator('#move').isDisabled(),true);await unavailable.close();console.log('PASS WebGL2 unavailable reports error and disables simulation input');
 const page=await browser.newPage();await page.goto(origin+'/index.html');await page.locator('[data-kind="web"]').click();await page.locator('[data-cat="遊戲敘事"]').click();await page.locator('#q').fill('Brick RTS');await page.waitForTimeout(100);assert.equal(await page.locator('[data-open="150"]').count()>0,true);console.log('PASS catalog search + game category');await page.close();
 console.log('Browser:',browser.version());console.log('Screenshots:',output);
}finally{await browser.close();server.close();}
