// The encyclopedia's prose (「百科」): text only, no imports and no numbers that packages/content/rules.ts or
// packages/sim/stats.ts already hold (the page computes those). Civilization texts are paraphrased from aoetw.com's
// civ and unit pages (HD / UserPatch-era encyclopedia, github.com/webrsb/aoetw, read 2026-09-30) and trimmed to what
// this game has; the Settlers are this game's own. History years are prose, not rules.
export type CivProse={summary:string;strategy:string;sources:readonly string[]};
export const codexIntro='文明資料整理自 aoetw.com（世紀帝國 II 的繁體中文百科，內容以 HD／UserPatch 時代為準），數值已換算成本作的比例。本作是一對一對戰，團隊加成只作用在擁有者自己身上。標示「尚未實作」的項目目前不在遊戲裡。';
// Architecture groups of the reference's civilization list (they also order the list).
export const architectureLabel:Readonly<Record<string,string>>={west:'西歐',central:'中歐',mideast:'中東',eastasia:'東亞',neutral:'本作原創'};
export const civProse:Readonly<Record<string,CivProse>>={
 settlers:{summary:'拓荒者是本作原創的基準文明：沒有文明加成、特殊單位，也不能建造城堡，科技樹就是本作完整的通用版本。',
  strategy:'適合熟悉基本操作，或當作對照組比較各文明加成的效果。雙方都是拓荒者時，勝負只取決於運營與操作。',sources:[]},
 britons:{summary:'不列顛是西歐的弓兵文明，代表中世紀的英格蘭人與盎格魯－諾曼人。相傳英格蘭一度只准百姓練習射箭，弓術因而冠絕一時，牧羊也是他們的專長。長弓兵射得比其他弓兵都遠，但馬廄與修道院的科技有缺口。',
  strategy:'前期以靶場的弓手搭配長槍兵施壓，靶場的效率加成讓弓兵補得快。射程加成要到第三時代才生效，長弓兵要站在近戰部隊後方輸出，別讓陣型被衝散。對手用騎兵繞後時，以長槍兵與箭塔護住弓兵。',sources:['civs/Britons','units/Longbowman']},
 celts:{summary:'塞爾特是西歐的步兵與攻城器文明，以蘇格蘭、愛爾蘭與威爾士人為原型。他們以木工與冶金見長，伐木快、攻城器精良；菘藍武士取材自臉塗藍漆、來去如風的戰士。弓兵與騎兵的科技缺口大，是典型、也容易被針對的步兵文明。',
  strategy:'步兵從第二時代起就跑得比別人快，適合早早用民兵系與長槍兵騷擾。攻城器攻擊更快，第四時代的塞爾特狂熱再讓它更耐打，攻城槌配步兵是主要的推進方式。菘藍武士適合繞後拆建築、追殺攻城器，但護甲薄，別正面撞上成群弓兵或已布好的防線。',sources:['civs/Celts','units/Woad_Raider']},
 franks:{summary:'法蘭克源自古稱高盧的地區，歷經墨洛溫與卡洛林王朝，是日後法蘭西王國與神聖羅馬帝國的前身。遊戲中是西歐的騎兵文明：馬廄單位更耐打，城堡也蓋得便宜。步兵科技完整，弓兵則是整個科技樹最弱的一環。',
  strategy:'採漿果快、磨坊的農田科技免費，前期經濟穩，適合第二時代用斥候騷擾、第三時代轉出騎士。便宜的城堡可以提早蓋在前線控制地圖，大量出騎士時再研究騎士精神。遇上長槍兵海就改用擲斧兵與步兵應對，不要硬走弓兵路線。',sources:['civs/Franks','units/Throwing_Axeman']},
 goths:{summary:'哥德泛指東日耳曼諸部族，以西元 476 年終結西羅馬帝國聞名；東哥德後來落腳義大利，西哥德則在伊比利半島立國。遊戲中是中歐的步兵文明，步兵便宜又量產得快，防禦設施卻是全文明最弱的。進攻時兇猛，一旦轉為守勢就相當吃力。',
  strategy:'步兵隨時代越來越便宜，第二時代就能用民兵系與長槍兵大量施壓。第三時代以哥德衛隊專打弓兵與建築，長槍兵負責擋騎兵；研究無政府狀態後兵營也能訓練哥德衛隊。缺步兵板甲，怕條頓武士、日本武士這類強力近戰步兵，最好的防守就是持續進攻。',sources:['civs/Goths','units/Huskarl']},
 teutons:{summary:'條頓源自日耳曼的一支，民族大遷徙後定居今日德國一帶，遊戲中代表神聖羅馬帝國；條頓武士取材自歷史上的條頓騎士團。他們在防禦、經濟與進攻上都有加成，箭塔與城鎮中心能進駐更多人、農田便宜，配上砲門垛口的城堡殺傷力居各文明之冠。',
  strategy:'箭塔能進駐加倍的單位，第二時代的塔攻很有威脅；便宜的農田替前期省下木材。步兵與騎兵在第三、第四時代近戰護甲逐步提高，適合打正面消耗戰。條頓武士又慢又怕遠程單位，要有騎士或攻城槌掩護才接近得了目標；沒有輕騎兵，後期欠缺快速騷擾的手段。',sources:['civs/Teutons','units/Teutonic_Knight']},
 vikings:{summary:'維京人在八至十一世紀劫掠並殖民歐洲沿岸與不列顛群島，遊戲中是步兵與海軍文明。陸戰以狂戰士為核心，步兵生命隨時代成長；升時代時免費得到手推車與手拉車，前中期經濟特別順。騎兵與僧侶的科技殘缺，後期相對吃虧。',
  strategy:'省下的經濟科技可以換成更早的兵力，第二到第三時代是施壓的好時機。狂戰士會自己回血、對付長槍兵與輕騎兵很有效，適合來回騷擾；研究酋長後全體步兵也能反制騎兵。本作還沒有海戰，維京的戰船加成與維京大戰船暫時派不上用場。',sources:['civs/Vikings','units/Berserk']},
 byzantines:{summary:'拜占庭即東羅馬帝國，以君士坦丁堡為中心，靠著雙重城牆守住歐亞交界上千年；遊戲中建築隨時代越來越堅固，升第四時代也比較便宜。以便宜的長槍兵、散兵這類「垃圾兵」為骨幹，科技樹幾乎完整，路線多變；拜占庭聖騎兵是專剋步兵的重騎兵。',
  strategy:'長槍兵與散兵的折扣讓第二時代就能以低成本大量反制騎兵與弓兵。便宜的第四時代適合穩守之後快速升級，僧侶的治療也更快。拜占庭聖騎兵與它的升級都昂貴，等資源充足再大量生產，對以步兵為主的對手有毀滅性。',sources:['civs/Byzantines','units/Cataphract']},
 persians:{summary:'波斯是歷史悠久的古國，到了中世紀仍深刻影響著中亞。遊戲中是中東的騎兵文明：經濟強、騎兵科技完整，戰象近乎無敵。代價是步兵在全文明中最弱，而且非常依賴黃金。',
  strategy:'城鎮中心的工作速度隨時代加快，開局資源也較多，村民補得快。騎士與戰象是主力；戰象又慢又怕長槍兵與僧侶轉化，需要弓兵或騎兵掩護。步兵後期明顯落後，別把太多資源投進步兵打長期戰。',sources:['civs/Persians','units/War_Elephant']},
 saracens:{summary:'「薩拉森」是歐洲人對穆斯林的泛稱，歷史上並沒有這個名字的帝國；遊戲中綜合了阿拉伯哈里發、倭馬亞、阿拔斯與阿尤布等勢力。定位為駱駝與海軍文明，科技樹相當完整，阿拉伯奴隸兵擅長剋制騎兵。',
  strategy:'弓兵對建築有額外攻擊，適合以弓手壓制並拆掉對手的前線建築。阿拉伯奴隸兵機動性高、對騎兵有加成，能應付多數騎兵與步兵，但怕長槍兵系與條頓武士。修道院科技幾乎齊全，穆斯林學墊讓陣亡的僧侶退回部分黃金，僧侶戰術值得一試。',sources:['civs/Saracens','units/Mameluke']},
 turks:{summary:'土耳其源自突厥烏古斯人建立的塞爾柱，其後的鄂圖曼帝國滅亡了東羅馬，並把君士坦丁堡改名伊斯坦堡。遊戲中是中東的火藥文明，火藥單位更耐打、採金更快；土耳其火槍兵在第三時代就能訓練，這在火藥單位中相當少見。',
  strategy:'常見打法是第二時代用斥候騷擾，進入第三時代時免費升級輕騎兵立刻轉強，接著以土耳其火槍兵為主力。缺長矛兵與精銳散兵，反制騎兵與弓兵的兵種都不完整，一旦陷入被動就會損失慘重，最好主動出擊。火槍兵很吃黃金，後期要靠採金加成撐住經濟。',sources:['civs/Turks','units/Janissary']},
 chinese:{summary:'中國是遊戲中最古老的文明之一，擅長弓、弩與火器。作為東亞的弓兵文明，開局多幾名村民卻少了食物與木材，起步不易；各時代研究科技都有折扣，完整發揮後後期非常強。步兵與弓兵的科技齊全，樣樣能做、樣樣不專精。',
  strategy:'開局食物吃緊，先研究織布機並引野豬回城鎮中心，讓城鎮中心一直生產村民。前期怕快攻，要及早用箭塔與建築圍好基地。連弩兵一次射出多支箭，成群時能迅速拆掉攻城槌，但射程短，適合防守；第四時代的火箭技術再提高它的攻擊。',sources:['civs/Chinese','units/Chu_Ko_Nu']},
 japanese:{summary:'日本的封建制度約在十一世紀才成形，軍隊歷來以步兵為主，是東亞的步兵文明。步兵的攻擊速度隨時代加快，經濟建築便宜，箭塔火力出眾；代價是騎兵孱弱。',
  strategy:'伐木場、採礦場與磨坊便宜，前期經濟起得快，適合第二時代以步兵快攻、盡量在前期取勝。第三時代研究射箭孔後，箭塔是可靠的守家手段。日本武士專剋特殊單位，對手依賴特殊單位時才值得大量生產；平時長劍士、弩手與長矛兵的組合更實用。',sources:['civs/Japanese','units/Samurai']},
 mongols:{summary:'蒙古帝國由鐵木真（成吉思汗）在 1206 年建立，鼎盛時是歷史上連續版圖最遼闊的國家。遊戲中以馬弓騎兵與攻城器見長，擅長游擊與快速破壞，輕騎兵也更耐打。弱點在防守，箭塔的升級有限。',
  strategy:'打獵特別快，靠獵物迅速進入第二時代，再用斥候騷擾對手的村民。蒙古突騎射速快、對攻城器有加成，適合襲擊村民與僧侶，也能在中距離擊毀攻城槌。游牧讓基地被偷襲時保住人口上限，鑿岩機讓攻城槌推進得更快；避開長槍兵系與成群的輕騎兵。',sources:['civs/Mongols','units/Mangudai']},
};
// One line per unique unit (the entry id is the unit kind).
export const uniqueUnitText:Readonly<Record<string,string>>={
 longbowman:'射程最遠的徒步弓兵，成群時火力致命，但生命低，怕騎兵與攻城器近身。',
 'woad-raider':'跑得最快的步兵之一，對建築有加成，擅長游擊與追殺攻城器，但護甲薄。',
 'throwing-axeman':'從遠處擲出斧頭的步兵，傷害算近戰，對建築有加成；能壓制長槍兵與攻城槌，怕重騎兵與打帶跑的弓兵。',
 huskarl:'遠程護甲極高、幾乎不怕箭矢的步兵，專打弓兵與建築；缺近戰護甲，怕騎士與強力近戰步兵。',
 'teutonic-knight':'又慢又硬的重步兵，攻擊與近戰護甲都高，對建築有加成；怕遠程單位打帶跑與僧侶轉化。',
 berserk:'會自己回血的步兵，擅長對付長槍兵與輕騎兵，適合騷擾；怕弓兵與對步兵有加成的單位。',
 cataphract:'對步兵有大量加成傷害的重騎兵，研究後勤後還會踐踏目標周圍的敵兵；遠程護甲偏低，造價昂貴。',
 'war-elephant':'笨重緩慢卻近乎無敵的騎兵，對建築有加成；怕長槍兵系與僧侶轉化。',
 mameluke:'騎著駱駝、從短距離擲出彎刀的近戰單位，對騎兵有加成，機動性高但昂貴。',
 janissary:'第三時代就能訓練的火藥步兵，攻擊高、射程遠，但生命偏低；怕弓兵與騎兵。',
 'chu-ko-nu':'一次射出多支箭的連弩手，只有第一支是完整傷害；成群時能迅速拆掉攻城槌，但射程短。',
 samurai:'攻擊速度極快的步兵，對所有特殊單位有額外傷害；怕弓兵與騎士。',
 mangudai:'射速極快、對攻城器有加成的馬弓騎兵，適合襲擊村民與僧侶；怕長槍兵系與成群的輕騎兵。',
 longboat:'在碼頭建造的維京戰船，一次射出好幾支箭，只有第一支是完整傷害；比同時代的戰船快又便宜，怕火船與岸上的箭塔。',
};
// Reference items a civilization also lacks there but this game does not have at all (civDefs missingLater), named
// as aoetw.com names them.
export const referenceOnlyNames:Readonly<Record<string,string>>={
 hussar:'匈牙利輕騎兵',paladin:'遊俠',cavalier:'重裝騎士','siege-ram':'重型衝撞車','thumb-ring':'拇指環','parthian-tactics':'安息人戰術',bloodlines:'品種',
 camel:'駱駝騎兵','heavy-scorpion':'重型弩砲','bombard-cannon':'火砲','elite-cannon-galleon':'精銳火砲戰船',missionary:'傳教士',arbalest:'強弩兵',
 architecture:'建築學',keep:'大型箭塔','guard-tower':'防禦箭塔','bombard-tower':'火砲塔','heated-shot':'火箭（燒熱彈）',shipwright:'造船員',
 'hand-cannoneer':'火槍兵',squires:'護衛技術',husbandry:'耕種技術',sappers:'工兵',arson:'縱火','siege-engineers':'攻城工程師','imperial-camel':'帝王駱駝騎兵','herbal-medicine':'草藥治療','fire-ship':'火戰船',guilds:'公會制度','dry-dock':'船塢','two-handed-swordsman':'雙手劍兵',champion:'劍兵勇士',
};
// Unit and bonus classes as the panels name them.
export const classLabel:Readonly<Record<string,string>>={infantry:'步兵',cavalry:'騎兵',archer:'弓兵',spear:'長槍兵',skirmisher:'散兵',building:'建築',siege:'攻城器',
 unique:'特殊單位',gunpowder:'火藥單位','cavalry-archer':'馬弓騎兵',elephant:'戰象',monk:'僧侶',villager:'村民',animal:'動物',camel:'駱駝騎兵',petard:'炸藥桶',
 ship:'船隻',warship:'戰艦',galley:'戰船系',fishing:'漁船',transport:'運輸船',trade:'貿易單位',fire:'火船',demolition:'自爆船',
 // The 遊戲元素 round's armor classes (aoetw.com 防禦類型).
 'fishing-ship':'漁船',ram:'衝撞車',mameluke:'阿拉伯奴隸兵','standard-building':'標準建築','stone-defense':'石造防禦','wall-gate':'城牆與城門',castle:'城堡'};

// ── Category 單位 ──────────────────────────────────────────────────────────────────────────────────────────────────
// aoetw.com's unit catalog (pages/units/*.vue of github.com/webrsb/aoetw, read 2026-10-01): every unit page except the
// animals, heroes and map-editor units, with the site's names, categories, training building, owning civilization,
// the unit it upgrades from and its 垃圾兵 (trash unit) flag. id: this game's unit kind or line-upgrade id where the
// game has the unit, else a slug-derived id. Text only; every number on the page comes from the simulation.
export const unitsIntro='單位資料整理自 aoetw.com（世紀帝國 II 的繁體中文百科，內容以 HD／UserPatch 到早期決定版為準）。本作的數值是依本作比例自訂的 design_default，不是原作數據：射程與視野以本作的地圖格計算，原作的射程大約折半再加上一段基礎距離，視野格數大致照搬，攻擊間隔換成模擬刻。海軍單位在碼頭建造、只能在水上航行，要選「湖畔」這類有大片水域的地圖；火槍兵、火砲與火砲戰船在第四時代於學院研究化學後解鎖。';
// The footnote of every unit page.
export const unitsNote='單位資料整理自 aoetw.com（HD／UserPatch 到早期決定版），說明已改用本作的單位、建築與時代名稱；數值一律取自本作的模擬，是 design_default，不是原作數據。標示「尚未實作」的單位目前不在遊戲裡。';
export type UnitCategoryDef={id:string;label:string;short:string;text:string};
// The site's seven unit types in its order, its 垃圾兵 page as a tag, and the units it files under none of them.
export const unitCategories:readonly UnitCategoryDef[]=[
 {id:'infantry',label:'步兵單位',short:'步兵',text:'徒步作戰的近戰主力，便宜、好量產、早早就能訓練，多半出自兵營。普遍怕弓兵、騎兵與僧侶，但長槍兵系專門用來反制騎兵。'},
 {id:'ranged',label:'遠距離單位',short:'遠程',text:'靶場訓練的射手與馬弓騎兵，生命與護甲偏低，卻能在遠處集火，擅長收拾步兵與村民；怕散兵、投石車，以及用攻城槌掩護推進的部隊。'},
 {id:'cavalry',label:'騎兵單位',short:'騎兵',text:'馬廄訓練的高速部隊，生命高，正面衝鋒能擊潰弓兵、步兵與攻城器，但普遍昂貴又吃黃金；長槍兵、駱駝與僧侶是主要剋星。'},
 {id:'naval',label:'海軍單位',short:'海軍',text:'碼頭建造、只能在水上行動的船隻，速度快、遠程護甲高，能打帶跑並攻擊岸邊建築；怕攻城器、僧侶與防禦建築。'},
 {id:'siege',label:'攻城器單位',short:'攻城器',text:'第三時代起出現的昂貴機械，專門拆建築，或以範圍傷害對付成群的步兵與弓兵；多半不能被僧侶治療。'},
 {id:'unique',label:'特殊單位',short:'特殊',text:'各文明專屬的兵種，大多在城堡訓練；少數能在城堡以外生產，讓每個文明發展出自己的打法。'},
 {id:'gunpowder',label:'火藥單位',short:'火藥',text:'以火藥發射彈丸的後期單位，一般要先在學院研究化學；文明專屬的火藥兵可以提早在第三時代出現。攻擊強，但命中與射速較差。'},
 {id:'other',label:'其他單位',short:'其他',text:'aoetw 沒有歸入上述類型的單位：負責經濟的村民、負責宗教的僧侶，以及跑貿易的貿易車隊。'},
];
// The site's trash-unit page: units that cost no gold, made in numbers to stall or counter a specific enemy.
export const trashText='垃圾兵指不需要黃金、可以大量生產的廉價兵種（長槍兵系、散兵系、斥候系等），適合長期戰與黃金耗盡之後。';
// Why a reference unit is not in this game yet (picked by the page model from the unit's categories and civilization).
export const unitPendingReasons={civ:'本作只有 13 個原版文明',expansion:'原版 13 文明沒有這個單位'} as const;
// The site's other unit lists, counted from its page folders; the encyclopedia names them only in a footnote.
export const aoetwUnitExtras={animals:30,heroes:123,editor:23} as const;
export type AoetwUnit={id:string;slug:string;name:string;nameEn:string;categories:readonly string[];at:string;civ:string|null;from:string|null;trash:boolean};
export const aoetwUnits:readonly AoetwUnit[]=[
{id:'arambai',slug:'Arambai',name:'飛鏢騎兵',nameEn:'Arambai',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'緬甸',from:null,trash:false},
 {id:'arbalest',slug:'Arbalester',name:'強弩兵',nameEn:'Arbalester',categories:['遠距離單位'],at:'射箭場',civ:null,from:'crossbowman',trash:false},
 {id:'archer',slug:'Archer',name:'弓兵',nameEn:'Archer',categories:['遠距離單位'],at:'射箭場',civ:null,from:null,trash:false},
 {id:'ballista-elephant',slug:'Ballista_Elephant',name:'弩砲象',nameEn:'Ballista Elephant',categories:['騎兵單位','攻城器單位','特殊單位'],at:'城堡',civ:'高棉',from:null,trash:false},
 {id:'ram',slug:'Battering_Ram',name:'輕型衝撞車',nameEn:'Battering Ram',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:null,trash:false},
 {id:'battle-elephant',slug:'Battle_Elephant',name:'矛象伕',nameEn:'Battle Elephant',categories:['騎兵單位'],at:'馬廄',civ:null,from:null,trash:false},
 {id:'berserk',slug:'Berserk',name:'狂戰士',nameEn:'Berserk',categories:['步兵單位','特殊單位'],at:'城堡',civ:'維京',from:null,trash:false},
 {id:'bombard-cannon',slug:'Bombard_Cannon',name:'火砲',nameEn:'Bombard Cannon',categories:['攻城器單位','火藥單位'],at:'攻城器製造所',civ:null,from:null,trash:false},
 {id:'boyar',slug:'Boyar',name:'貴族鐵騎',nameEn:'Boyar',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'斯拉夫',from:null,trash:false},
 {id:'camel-archer',slug:'Camel_Archer',name:'駱駝弓騎兵',nameEn:'Camel Archer',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'柏柏',from:null,trash:false},
 {id:'camel',slug:'Camel_Rider',name:'駱駝騎兵',nameEn:'Camel Rider',categories:['騎兵單位'],at:'馬廄',civ:null,from:null,trash:false},
 {id:'cannon-galleon',slug:'Cannon_Galleon',name:'火砲戰船',nameEn:'Cannon Galleon',categories:['海軍單位','火藥單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'capped-ram',slug:'Capped_Ram',name:'裝甲衝撞車',nameEn:'Capped Ram',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:'ram',trash:false},
 {id:'caravel',slug:'Caravel',name:'卡拉維爾戰船',nameEn:'Caravel',categories:['海軍單位','特殊單位'],at:'碼頭',civ:'葡萄牙',from:null,trash:false},
 {id:'cataphract',slug:'Cataphract',name:'拜占庭聖騎兵',nameEn:'Cataphract',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'拜占庭',from:null,trash:false},
 {id:'cavalier',slug:'Cavalier',name:'重裝騎士',nameEn:'Cavalier',categories:['騎兵單位'],at:'馬廄',civ:null,from:'knight',trash:false},
 {id:'cavalry-archer',slug:'Cavalry_Archer',name:'馬弓騎兵',nameEn:'Cavalry Archer',categories:['遠距離單位'],at:'射箭場',civ:null,from:null,trash:false},
 {id:'champion',slug:'Champion',name:'劍兵勇士',nameEn:'Champion',categories:['步兵單位'],at:'軍營',civ:null,from:'two-handed-swordsman',trash:false},
 {id:'chu-ko-nu',slug:'Chu_Ko_Nu',name:'連弩兵',nameEn:'Chu Ko Nu',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'中國',from:null,trash:false},
 {id:'condottiero',slug:'Condottiero',name:'傭兵',nameEn:'Condottiero',categories:['步兵單位','特殊單位'],at:'軍營',civ:'義大利',from:null,trash:false},
 {id:'conquistador',slug:'Conquistador',name:'西班牙征服者',nameEn:'Conquistador',categories:['遠距離單位','火藥單位','特殊單位'],at:'城堡',civ:'西班牙',from:null,trash:false},
 {id:'crossbowman',slug:'Crossbowman',name:'弩兵',nameEn:'Crossbowman',categories:['遠距離單位'],at:'射箭場',civ:null,from:'archer',trash:false},
 {id:'demolition-raft',slug:'Demolition_Raft',name:'自爆筏',nameEn:'Demolition Raft',categories:['海軍單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'demolition-ship',slug:'Demolition_Ship',name:'爆破船',nameEn:'Demolition Ship',categories:['海軍單位'],at:'碼頭',civ:null,from:'demolition-raft',trash:false},
 {id:'eagle-scout',slug:'Eagle_Scout',name:'鷹斥候',nameEn:'Eagle Scout',categories:['步兵單位'],at:'軍營',civ:null,from:null,trash:false},
 {id:'eagle-warrior',slug:'Eagle_Warrior',name:'鷹勇士',nameEn:'Eagle Warrior',categories:['步兵單位'],at:'軍營',civ:null,from:'eagle-scout',trash:false},
 {id:'elephant-archer',slug:'Elephant_Archer',name:'象弓騎兵',nameEn:'Elephant Archer',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'印度',from:null,trash:false},
 {id:'elite-battle-elephant',slug:'Elite_Battle_Elephant',name:'精銳矛象伕',nameEn:'Elite Battle Elephant',categories:['騎兵單位'],at:'馬廄',civ:null,from:'battle-elephant',trash:false},
 {id:'elite-cannon-galleon',slug:'Elite_Cannon_Galleon',name:'精銳火砲戰船',nameEn:'Elite Cannon Galleon',categories:['海軍單位','火藥單位'],at:'碼頭',civ:null,from:'cannon-galleon',trash:false},
 {id:'elite-eagle-warrior',slug:'Elite_Eagle_Warrior',name:'精銳鷹勇士',nameEn:'Elite Eagle Warrior',categories:['步兵單位'],at:'軍營',civ:null,from:'eagle-warrior',trash:false},
 {id:'elite-skirmisher',slug:'Elite_Skirmisher',name:'戰矛兵',nameEn:'Elite Skirmisher',categories:['遠距離單位'],at:'射箭場',civ:null,from:'skirmisher',trash:true},
 {id:'elite-steppe-lancer',slug:'Elite_Steppe_Lancer',name:'精銳草原騎兵',nameEn:'Elite Steppe Lancer',categories:['騎兵單位'],at:'馬廄',civ:null,from:'steppe-lancer',trash:false},
 {id:'fast-fire-ship',slug:'Fast_Fire_Ship',name:'重型火戰船',nameEn:'Fast Fire Ship',categories:['海軍單位'],at:'碼頭',civ:null,from:'fire-ship',trash:false},
 {id:'fire-galley',slug:'Fire_Galley',name:'火艨艟',nameEn:'Fire Galley',categories:['海軍單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'fire-ship',slug:'Fire_Ship',name:'火戰船',nameEn:'Fire Ship',categories:['海軍單位'],at:'碼頭',civ:null,from:'fire-galley',trash:false},
 {id:'fishing-ship',slug:'Fishing_Ship',name:'漁船',nameEn:'Fishing Ship',categories:['海軍單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'flaming-camel',slug:'Flaming_Camel',name:'火焰駱駝',nameEn:'Flaming Camel',categories:['攻城器單位','特殊單位'],at:'城堡',civ:'韃靼',from:null,trash:false},
 {id:'galleon',slug:'Galleon',name:'重型弩砲戰船',nameEn:'Galleon',categories:['海軍單位'],at:'碼頭',civ:null,from:'war-galley',trash:false},
 {id:'galley',slug:'Galley',name:'戰船',nameEn:'Galley',categories:['海軍單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'gbeto',slug:'Gbeto',name:'飛刀女獵手',nameEn:'Gbeto',categories:['步兵單位','特殊單位'],at:'城堡',civ:'馬利',from:null,trash:false},
 {id:'genitour',slug:'Genitour',name:'標槍騎兵',nameEn:'Genitour',categories:['遠距離單位','特殊單位'],at:'射箭場',civ:'柏柏',from:null,trash:true},
 {id:'genoese-crossbowman',slug:'Genoese_Crossbowman',name:'熱那亞弩手',nameEn:'Genoese Crossbowman',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'義大利',from:null,trash:false},
 {id:'halberdier',slug:'Halberdier',name:'戟兵',nameEn:'Halberdier',categories:['步兵單位'],at:'軍營',civ:null,from:'pikeman',trash:true},
 {id:'hand-cannoneer',slug:'Hand_Cannoneer',name:'火槍兵',nameEn:'Hand Cannoneer',categories:['遠距離單位','火藥單位'],at:'射箭場',civ:null,from:null,trash:false},
 {id:'heavy-camel',slug:'Heavy_Camel_Rider',name:'重裝駱駝騎兵',nameEn:'Heavy Camel Rider',categories:['騎兵單位'],at:'馬廄',civ:null,from:'camel',trash:false},
 {id:'heavy-cavalry-archer',slug:'Heavy_Cavalry_Archer',name:'重裝馬弓騎兵',nameEn:'Heavy Cavalry Archer',categories:['遠距離單位'],at:'射箭場',civ:null,from:'cavalry-archer',trash:false},
 {id:'heavy-demolition-ship',slug:'Heavy_Demolition_Ship',name:'重型爆破船',nameEn:'Heavy Demolition Ship',categories:['海軍單位'],at:'碼頭',civ:null,from:'demolition-ship',trash:false},
 {id:'heavy-scorpion',slug:'Heavy_Scorpion',name:'重型弩砲',nameEn:'Heavy Scorpion',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:'scorpion',trash:false},
 {id:'huskarl',slug:'Huskarl',name:'哥德衛隊',nameEn:'Huskarl',categories:['步兵單位','特殊單位'],at:'城堡／軍營',civ:'哥德',from:null,trash:false},
 {id:'hussar',slug:'Hussar',name:'匈牙利輕騎兵',nameEn:'Hussar',categories:['騎兵單位'],at:'馬廄',civ:null,from:'light-cavalry',trash:true},
 {id:'imperial-camel',slug:'Imperial_Camel_Rider',name:'帝王駱駝騎兵',nameEn:'Imperial Camel Rider',categories:['騎兵單位','特殊單位'],at:'馬廄',civ:'印度',from:'heavy-camel',trash:false},
 {id:'imperial-skirmisher',slug:'Imperial_Skirmisher',name:'帝王戰矛兵',nameEn:'Imperial Skirmisher',categories:['遠距離單位','特殊單位'],at:'射箭場',civ:'越南',from:'elite-skirmisher',trash:true},
 {id:'jaguar-warrior',slug:'Jaguar_Warrior',name:'豹勇士',nameEn:'Jaguar Warrior',categories:['步兵單位','特殊單位'],at:'城堡',civ:'阿茲特克',from:null,trash:false},
 {id:'janissary',slug:'Janissary',name:'土耳其火槍兵',nameEn:'Janissary',categories:['遠距離單位','火藥單位','特殊單位'],at:'城堡',civ:'土耳其',from:null,trash:false},
 {id:'kamayuk',slug:'Kamayuk',name:'槍隊長',nameEn:'Kamayuk',categories:['步兵單位','特殊單位'],at:'城堡',civ:'印加',from:null,trash:false},
 {id:'karambit-warrior',slug:'Karambit_Warrior',name:'爪刀勇士',nameEn:'Karambit Warrior',categories:['步兵單位','特殊單位'],at:'城堡',civ:'馬來',from:null,trash:false},
 {id:'keshik',slug:'Keshik',name:'怯薛',nameEn:'Keshik',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'韃靼',from:null,trash:false},
 {id:'kipchak',slug:'Kipchak',name:'欽察',nameEn:'Kipchak',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'庫曼',from:null,trash:false},
 {id:'knight',slug:'Knight',name:'騎士',nameEn:'Knight',categories:['騎兵單位'],at:'馬廄',civ:null,from:null,trash:false},
 {id:'konnik',slug:'Konnik',name:'保加利亞騎兵',nameEn:'Konnik',categories:['騎兵單位','步兵單位','特殊單位'],at:'城堡／營壘',civ:'保加利亞',from:null,trash:false},
 {id:'leitis',slug:'Leitis',name:'烈堤司',nameEn:'Leitis',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'立陶宛',from:null,trash:false},
 {id:'light-cavalry',slug:'Light_Cavalry',name:'輕騎兵',nameEn:'Light Cavalry',categories:['騎兵單位'],at:'馬廄',civ:null,from:'scout',trash:true},
 {id:'long-swordsman',slug:'Long_Swordsman',name:'長劍兵',nameEn:'Long Swordsman',categories:['步兵單位'],at:'軍營',civ:null,from:'man-at-arms',trash:false},
 {id:'longboat',slug:'Longboat',name:'維京大戰船',nameEn:'Longboat',categories:['海軍單位','特殊單位'],at:'碼頭',civ:'維京',from:null,trash:false},
 {id:'longbowman',slug:'Longbowman',name:'長弓兵',nameEn:'Longbowman',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'不列顛',from:null,trash:false},
 {id:'magyar-huszar',slug:'Magyar_Huszar',name:'馬扎爾驃騎兵',nameEn:'Magyar Huszar',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'馬扎爾',from:null,trash:true},
 {id:'mameluke',slug:'Mameluke',name:'阿拉伯奴隸兵',nameEn:'Mameluke',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'薩拉森',from:null,trash:false},
 {id:'man-at-arms',slug:'Man-at-Arms',name:'裝甲步兵',nameEn:'Man-at-Arms',categories:['步兵單位'],at:'軍營',civ:null,from:'militia',trash:false},
 {id:'mangonel',slug:'Mangonel',name:'輕型投石車',nameEn:'Mangonel',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:null,trash:false},
 {id:'mangudai',slug:'Mangudai',name:'蒙古突騎',nameEn:'Mangudai',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'蒙古',from:null,trash:false},
 {id:'militia',slug:'Militia',name:'民兵',nameEn:'Militia',categories:['步兵單位'],at:'軍營',civ:null,from:null,trash:false},
 {id:'missionary',slug:'Missionary',name:'傳教士',nameEn:'Missionary',categories:['特殊單位'],at:'修道院',civ:'西班牙',from:null,trash:false},
 {id:'monk',slug:'Monk',name:'僧侶',nameEn:'Monk',categories:[],at:'修道院',civ:null,from:null,trash:false},
 {id:'onager',slug:'Onager',name:'中型投石車',nameEn:'Onager',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:'mangonel',trash:false},
 {id:'organ-gun',slug:'Organ_Gun',name:'風琴砲',nameEn:'Organ Gun',categories:['攻城器單位','火藥單位','特殊單位'],at:'城堡',civ:'葡萄牙',from:null,trash:false},
 {id:'paladin',slug:'Paladin',name:'遊俠',nameEn:'Paladin',categories:['騎兵單位'],at:'馬廄',civ:null,from:'cavalier',trash:false},
 {id:'petard',slug:'Petard',name:'炸藥桶',nameEn:'Petard',categories:['攻城器單位'],at:'城堡',civ:null,from:null,trash:false},
 {id:'pikeman',slug:'Pikeman',name:'重裝長槍兵',nameEn:'Pikeman',categories:['步兵單位'],at:'軍營',civ:null,from:'spearman',trash:true},
 {id:'plumed-archer',slug:'Plumed_Archer',name:'羽毛箭射手',nameEn:'Plumed Archer',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'馬雅',from:null,trash:false},
 {id:'rattan-archer',slug:'Rattan_Archer',name:'藤甲弓兵',nameEn:'Rattan Archer',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'越南',from:null,trash:false},
 {id:'samurai',slug:'Samurai',name:'日本武士',nameEn:'Samurai',categories:['步兵單位','特殊單位'],at:'城堡',civ:'日本',from:null,trash:false},
 {id:'scorpion',slug:'Scorpion',name:'弩砲',nameEn:'Scorpion',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:null,trash:false},
 {id:'scout',slug:'Scout_Cavalry',name:'斥候',nameEn:'Scout Cavalry',categories:['騎兵單位'],at:'馬廄',civ:null,from:null,trash:true},
 {id:'serjeant',slug:'Serjeant',name:'薩金特衛兵',nameEn:'Serjeant',categories:['步兵單位','特殊單位'],at:'城堡／城樓',civ:'西西里',from:null,trash:false},
 {id:'shotel-warrior',slug:'Shotel_Warrior',name:'彎刀勇士',nameEn:'Shotel Warrior',categories:['步兵單位','特殊單位'],at:'城堡',civ:'衣索比亞',from:null,trash:false},
 {id:'siege-onager',slug:'Siege_Onager',name:'重型投石車',nameEn:'Siege Onager',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:'onager',trash:false},
 {id:'siege-ram',slug:'Siege_Ram',name:'重型衝撞車',nameEn:'Siege Ram',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:'capped-ram',trash:false},
 {id:'siege-tower',slug:'Siege_Tower',name:'攻城塔',nameEn:'Siege Tower',categories:['攻城器單位'],at:'攻城器製造所',civ:null,from:null,trash:false},
 {id:'skirmisher',slug:'Skirmisher',name:'矛兵',nameEn:'Skirmisher',categories:['遠距離單位'],at:'射箭場',civ:null,from:null,trash:true},
 {id:'slinger',slug:'Slinger',name:'投石手',nameEn:'Slinger',categories:['遠距離單位','特殊單位'],at:'射箭場',civ:'印加',from:null,trash:false},
 {id:'spearman',slug:'Spearman',name:'長槍兵',nameEn:'Spearman',categories:['步兵單位'],at:'軍營',civ:null,from:null,trash:true},
 {id:'steppe-lancer',slug:'Steppe_Lancer',name:'草原騎兵',nameEn:'Steppe Lancer',categories:['騎兵單位'],at:'馬廄',civ:null,from:null,trash:false},
 {id:'tarkan',slug:'Tarkan',name:'答剌罕騎兵',nameEn:'Tarkan',categories:['騎兵單位','特殊單位'],at:'城堡／馬廄',civ:'匈人',from:null,trash:false},
 {id:'teutonic-knight',slug:'Teutonic_Knight',name:'條頓武士',nameEn:'Teutonic Knight',categories:['步兵單位','特殊單位'],at:'城堡',civ:'條頓',from:null,trash:false},
 {id:'throwing-axeman',slug:'Throwing_Axeman',name:'擲斧兵',nameEn:'Throwing Axeman',categories:['步兵單位','特殊單位'],at:'城堡',civ:'法蘭克',from:null,trash:false},
 {id:'trade-cart',slug:'Trade_Cart',name:'貿易車隊',nameEn:'Trade Cart',categories:[],at:'市集',civ:null,from:null,trash:false},
 {id:'trade-cog',slug:'Trade_Cog',name:'貿易商旅',nameEn:'Trade Cog',categories:['海軍單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'transport-ship',slug:'Transport_Ship',name:'運輸船',nameEn:'Transport Ship',categories:['海軍單位'],at:'碼頭',civ:null,from:null,trash:false},
 {id:'trebuchet',slug:'Trebuchet',name:'投石機',nameEn:'Trebuchet',categories:['攻城器單位'],at:'城堡',civ:null,from:null,trash:false},
 {id:'turtle-ship',slug:'Turtle_Ship',name:'龜甲船',nameEn:'Turtle Ship',categories:['海軍單位','火藥單位','特殊單位'],at:'碼頭',civ:'朝鮮',from:null,trash:false},
 {id:'two-handed-swordsman',slug:'Two-Handed_Swordsman',name:'雙手劍兵',nameEn:'Two-Handed Swordsman',categories:['步兵單位'],at:'軍營',civ:null,from:'long-swordsman',trash:false},
 {id:'villager',slug:'Villager',name:'村民',nameEn:'Villager',categories:[],at:'城鎮中心',civ:null,from:null,trash:false},
 {id:'war-elephant',slug:'War_Elephant',name:'戰象',nameEn:'War Elephant',categories:['騎兵單位','特殊單位'],at:'城堡',civ:'波斯',from:null,trash:false},
 {id:'war-galley',slug:'War_Galley',name:'弩砲戰船',nameEn:'War Galley',categories:['海軍單位'],at:'碼頭',civ:null,from:'galley',trash:false},
 {id:'war-wagon',slug:'War_Wagon',name:'馬戰車',nameEn:'War Wagon',categories:['遠距離單位','特殊單位'],at:'城堡',civ:'朝鮮',from:null,trash:false},
 {id:'woad-raider',slug:'Woad_Raider',name:'菘藍武士',nameEn:'Woad Raider',categories:['步兵單位','特殊單位'],at:'城堡',civ:'塞爾特',from:null,trash:false},
 {id:'xolotl-warrior',slug:'Xolotl_Warrior',name:'索洛托勇士',nameEn:'Xolotl Warrior',categories:['騎兵單位'],at:'馬廄',civ:null,from:null,trash:false},
];
// One or two sentences per reference unit (paraphrased from its aoetw.com page; keyed like aoetwUnits), with this
// game's names for units, buildings and ages (the site's 矛兵 is the 散兵 here, its 城堡時代 the third age).
export const unitText:Readonly<Record<string,string>>={
 'arambai':'緬甸的城堡特殊單位，騎馬投擲飛鏢的遠程騎兵，傷害驚人、射速快又機動，但準度不佳，對衝撞車有額外傷害。能輕鬆收拾步兵、弓兵、村民與僧侶，卻怕長槍兵、駱駝騎兵、阿拉伯奴隸兵，以及哥德衛隊、鷹勇士這類耐箭單位。',
 'arbalest':'第四時代的弓兵系最終升級，擅長在遠處消耗步兵與村民。碰上散兵、投石車、弩砲、騎兵，或哥德衛隊、鷹勇士、藤甲弓兵這類耐箭單位就會吃虧。',
 'archer':'第二時代就能訓練的基礎遠程兵，血量與攻擊都偏低，但靠射程能在早期壓制步兵、獵殺村民。天敵是散兵，數量不足時也怕斥候與鷹斥候近身。',
 'ballista-elephant':'高棉的城堡特殊單位，背上架著弩砲的大象，同時算騎兵與攻城器，箭矢能貫穿成排敵人，還能射倒樹木。適合清理弓兵、步兵、建築與靠岸船艦，但怕槍隊長、戟兵、阿拉伯奴隸兵等近戰剋星，以及投石車、火砲與馬扎爾驃騎兵。',
 'ram':'無人操作的攻城衝車，專拆建築與攻城器，遠程護甲極高、幾乎不怕箭，還能載步兵提升速度與破壞力。移動非常慢、近戰防禦很差，連村民都能拆它；最怕近戰騎兵（尤其馬扎爾驃騎兵）、蒙古突騎與投石車。',
 'battle-elephant':'東南亞文明在第三時代由馬廄訓練的戰鬥大象，類似戰象但小一號，攻擊時會踐踏身旁敵人。擅長打近戰單位與建築，但走得慢、易被僧侶招降，長矛兵、槍隊長、駱駝騎兵、阿拉伯奴隸兵與弩砲都能剋制它。',
 'berserk':'維京的城堡特殊步兵，攻防兼備且會自行回血，研發酋長後對騎兵也有加成。擅長砍散兵、戟兵、駱駝、鷹勇士與建築，但遇到拜占庭聖騎兵、豹勇士、條頓武士、日本武士等更強的近戰，或火槍兵、投石手等遠程反步兵就居下風。',
 'bombard-cannon':'第四時代研發化學後才能生產的火藥攻城砲，射程長、單發傷害大。專門轟擊建築，也能點掉弩砲、投石車、巨型投石機與弓兵；一旦被近戰騎兵、馬扎爾驃騎兵或傭兵貼身就難以自保。',
 'boyar':'斯拉夫的城堡特殊重騎兵，近戰護甲極厚、攻擊也高，適合正面硬碰。能壓制散兵與多數近戰兵種，但怕長矛兵、槍隊長、駱駝騎兵、阿拉伯奴隸兵、僧侶與弓兵集火。',
 'camel-archer':'柏柏在非洲王國資料片登場的城堡特殊單位，騎駱駝射箭，對馬弓騎兵類有額外傷害。適合反制馬弓騎兵、蒙古突騎與行動遲緩的近戰部隊，但怕哥德衛隊、精銳散兵、鷹勇士與投石車。',
 'camel':'第三時代由馬廄訓練的駱駝兵，對騎兵有專屬加成。常用來反制騎士、馬弓騎兵、攻城器與散兵；遇上步兵、弓兵、拜占庭聖騎兵或防禦建築則不利。',
 'cannon-galleon':'第四時代研發對應科技後在碼頭建造的火砲船，射程長，專門從海上轟擊岸邊建築。對付其他船隻反應遲鈍，容易被戰船、火砲與僧侶解決。',
 'capped-ram':'攻城槌的強化版，拆建築與攻城器更凶、遠防依舊極高，升級也便宜，是帝王初期沒有巨型投石機時推進的好幫手。行進仍然緩慢需要護送，怕近戰單位（特別是馬扎爾驃騎兵）、蒙古突騎與投石車。',
 'caravel':'葡萄牙的第二特殊單位，第三時代在碼頭建造，射出的箭能像弩砲一樣貫穿多個目標。擅長打密集船隊、運輸船、漁船與火砲戰船，但怕火戰船、龜甲船、維京大戰船，以及岸上的箭塔、城堡與攻城器。',
 'cataphract':'拜占庭的城堡特殊重騎兵，對步兵有大量加成傷害，連長槍兵都難以招架。步兵、散兵、攻城器與輕騎兵都是它的獵物，但訓練與升級昂貴，碰上戰象、貴族鐵騎、騎士或大量弓兵就吃虧。',
 'cavalier':'騎士在第四時代的升級，仍是後期最強勢的主力之一，能碾壓步兵、弓兵、村民與攻城器。天敵依然是長槍兵系、駱駝騎兵、阿拉伯奴隸兵與僧侶，戰象、貴族鐵騎、條頓武士也能正面擋住它。',
 'cavalry-archer':'第三時代於靶場訓練的騎馬射手，速度快又能遠程攻擊，擅長邊退邊射騷擾步兵與慢速近戰；美洲三國無法訓練。怕精銳散兵、長槍兵、駱駝系與駱駝弓騎兵，熱那亞弩手、哥德衛隊、鷹勇士、投石車與弩砲也能剋它。',
 'champion':'民兵系的最高等級，第四時代於兵營升級的泛用重步兵。能砍翻散兵、戟兵、鷹勇士、駱駝、輕騎兵與建築；但弓兵、弩砲、火藥單位、投石手，以及拜占庭聖騎兵、條頓武士、豹勇士都是它的剋星。',
 'chu-ko-nu':'中國的城堡特殊弓兵，一次連射多支箭（普通三支、精銳五支），但只有第一支造成完整傷害。近距離火力密集，擅長處理步兵、建築與衝撞車；怕散兵、弩砲、投石車、騎兵、哥德衛隊、鷹勇士與標槍騎兵。',
 'condottiero':'義大利的第二特殊單位，義大利與其盟友在第四時代就能於兵營訓練，沒有精銳版。移動快、專門反火藥，火槍兵、土耳其火槍兵、西班牙征服者、火砲與攻城器都怕它；但對弓兵、弩砲與條頓武士、日本武士等重步兵很吃虧。',
 'conquistador':'西班牙在征服者入侵登場的城堡特殊單位，是騎馬的火槍手，護甲高、攻擊強、跑得快。很會屠殺步兵與衝撞車，但怕精銳散兵、長槍兵、駱駝騎兵、阿拉伯奴隸兵、傭兵、哥德衛隊、鷹勇士與投石車。',
 'crossbowman':'弓兵在第三時代的升級，能高效率消滅步兵與村民；西班牙與保加利亞沒有此單位。遇到騎士、散兵、攻城器，以及耐箭的哥德衛隊、鷹勇士、藤甲弓兵時不利。',
 'demolition-raft':'非洲王國新增的第二時代自爆小船，滿載炸藥，撞上敵船、碼頭或岸邊目標時造成大量傷害；朝鮮無法使用。能炸毀運輸船、漁船與岸邊或淺灘上的近戰部隊，但被箭塔或岸上遠程單位射擊就難以接近。',
 'demolition-ship':'第三時代的爆破船，戰船升級為弩砲戰船時由自爆筏自動升級而來，衝進敵艦或岸邊目標後引爆；朝鮮不能訓練。對運輸船、漁船、火砲戰船與岸邊近戰單位殺傷力大，但怕龜甲船、箭塔、城堡與岸上遠程單位。',
 'eagle-scout':'美洲三國專用的步兵偵察兵，失落的帝國起第二時代即可生產，開局那隻會自動探圖。能欺負散兵、斥候與弓兵，但與步兵正面交戰會落敗。',
 'eagle-warrior':'鷹斥候升級而成的美洲快速步兵，第三時代起可升級，遠防高、移動快。擅長追殺弓兵、攻城器與僧侶，但打不過其他步兵，也怕拜占庭聖騎兵、貴族鐵騎、火槍兵與投石手。',
 'elephant-archer':'印度的城堡特殊單位，騎在大象上的射手，速度慢但生命值與護甲都很高。擅長壓制慢速近戰、弓兵與建築，但被長矛兵、槍隊長、駱駝騎兵、阿拉伯奴隸兵、哥德衛隊、鷹勇士、精銳散兵、日本武士與僧侶反制。',
 'elite-battle-elephant':'矛象伕在第四時代的升級，同樣會對身旁敵人造成擴散踐踏傷害，只是範圍比戰象小。近戰單位與建築很難擋住它，但行動慢、易被招降，長槍兵系、槍隊長、阿拉伯奴隸兵、馬弓騎兵與弩砲都能剋制。',
 'elite-cannon-galleon':'火砲戰船在第四時代的升級，射程更遠、傷害更高，最適合從海上摧毀陸地建築。應付敵方船艦仍不靈活，怕戰船、火砲與僧侶。',
 'elite-eagle-warrior':'鷹斥候系的最高級，美洲三國限定。擅長獵殺弓兵、攻城器與僧侶；其他步兵、拜占庭聖騎兵、貴族鐵騎、土耳其火槍兵與投石手則是它的剋星。',
 'elite-skirmisher':'第三時代的反弓兵單位，對弓兵與馬弓騎兵都有加成，是剋制遠程部隊的廉價選擇；土耳其沒有此單位。怕近戰單位與攻城器，越南與其盟友可再升級為帝王戰矛兵。',
 'elite-steppe-lancer':'決定版加入的第四時代輕型長矛騎兵，能隔一格出手攻擊。適合獵殺村民、弓兵、散兵、攻城器與輕騎兵，但面對重騎兵、步兵與駱駝部隊不利。',
 'fast-fire-ship':'火戰船的第四時代升級（舊版譯作快速火戰船），以近距離噴火攻擊，對船隻有加成，速度足以追上重型弩砲戰船。擅長燒毀重型弩砲戰船、火砲戰船、運輸船與漁船，但怕自爆筏、龜甲船、維京大戰船、箭塔、城堡與岸上攻城器。',
 'fire-galley':'非洲王國新增的第二時代噴火船，讓早期海戰不再只有戰船互射；戰船升級為弩砲戰船時會自動變成火戰船，維京無法訓練。能剋制戰船、運輸船與漁船，但怕自爆筏、箭塔與岸邊的範圍攻擊。',
 'fire-ship':'第三時代的噴火船，必須貼近敵艦、以極高頻率噴火，對船隻有額外傷害；維京不能訓練。是弩砲戰船、火砲戰船、運輸船與漁船的剋星，但怕自爆筏、龜甲船、維京大戰船及岸上的塔、城堡與攻城器。',
 'fishing-ship':'碼頭建造的經濟船，負責捕魚或搭建海上魚網來供應食物；日本、義大利、馬來對它各有加成。完全沒有戰鬥能力，任何敵方單位都能威脅它。',
 'flaming-camel':'韃靼的第二特殊單位，第四時代研發帖木兒攻城術後才能在城堡訓練，是背著燃燒稻草的自爆駱駝。衝進敵陣或被擊殺時會爆炸，專門對付騎兵（尤其大象）與建築；步兵、弓兵、城堡、箭塔與僧侶能在它接近前處理掉它。',
 'galleon':'第四時代的主力弓箭戰艦，數量決定制海權，能快速清除敵船與碼頭；阿茲特克無法訓練。擅長打運輸船、漁船、爆破船與火砲戰船，但被火戰船、龜甲船、維京大戰船剋制，也怕箭塔、城堡與岸上攻城器。',
 'galley':'第二時代的小型快速戰船，用來偵察並獵殺漁船等弱小目標。可打運輸船、漁船與岸邊近戰單位，但怕火戰船、箭塔、城堡與岸邊的範圍攻擊。',
 'gbeto':'馬利的城堡特殊單位，會投擲飛刀的快速遠程步兵，攻擊高但射速慢、身板薄。擅長打散兵、長槍兵、步兵、馬弓騎兵與衝撞車；但怕投石車、火藥單位、投石手、羽毛箭射手、豹勇士、日本武士、重騎兵與僧侶。',
 'genitour':'柏柏與其盟友共享的特殊單位，第三時代於靶場訓練，本質是騎馬的散兵，不花黃金，第四時代可升級為精銳版（同頁介紹）。專門反制弓兵與馬弓騎兵，但怕駱駝騎兵、長矛兵、攻城器、熱那亞弩手、哥德衛隊與鷹勇士。',
 'genoese-crossbowman':'義大利在失落的帝國登場的城堡特殊單位，是對騎兵有加成的重裝弩手。能射穿騎兵、馬弓騎兵與步兵，但怕其他弓兵、弩砲、投石車、哥德衛隊、鷹勇士與日本武士。',
 'halberdier':'長槍兵系在第四時代的最終升級，專打騎兵（拜占庭聖騎兵除外），對其他目標傷害很低；不花黃金，屬於垃圾兵。怕弓兵、火藥單位、投石手、弩砲、僧侶與其他步兵。',
 'hand-cannoneer':'第四時代研發化學後於靶場訓練的火藥單位，攻擊很高但命中率與射速偏低，是步兵的剋星。怕散兵、弩砲、投石車、重騎兵、哥德衛隊與傭兵。',
 'heavy-camel':'駱駝騎兵在第四時代的升級，對騎兵保有優勢。擅長打騎兵、馬弓騎兵、攻城器與散兵，但面對步兵、弓兵、拜占庭聖騎兵與防禦建築會吃虧。',
 'heavy-cavalry-archer':'馬弓騎兵在第四時代的升級，保有高速與遠程攻擊，是騷擾與壓制步兵的好手。怕精銳散兵與長槍兵，駱駝系、槍隊長、熱那亞弩手、哥德衛隊、鷹勇士、中型投石車與弩砲也能剋它。',
 'heavy-demolition-ship':'爆破船的第四時代升級，護甲、血量與爆炸範圍都更大，可說是海上的炸藥桶。能炸毀運輸船、漁船與岸邊或淺灘上的單位，但怕箭塔與岸上遠程單位。',
 'heavy-scorpion':'弩砲的升級版，射出能貫穿一整排敵人的大型箭矢，主目標吃全額、其餘吃一半，而且不會誤傷友軍。擅長打成群的弓兵與慢速單位，但怕近戰騎兵、馬扎爾驃騎兵、蒙古突騎、投石車、鷹勇士、菘藍武士、哥德衛隊與遠程單位。',
 'huskarl':'哥德的特殊步兵，遠程護甲極高、幾乎不怕箭矢，研發無政府狀態後也能在兵營訓練。擅長打弓兵、火藥單位、弩砲、鷹勇士與建築，但怕投石車與大多數近戰單位。',
 'hussar':'斥候系在第四時代的最終升級（又稱翼騎兵），只花食物，對僧侶、遠程兵種與攻城器有加成。適合獵殺村民、弓兵、攻城器與僧侶，但正面打不過長槍兵系、槍隊長、駱駝騎兵、阿拉伯奴隸兵等近戰單位。',
 'imperial-camel':'印度限定的駱駝騎兵再升級，第四時代於馬廄生產，反騎兵能力更強；日本武士對它沒有特殊單位加成。能壓制騎兵、馬弓騎兵、攻城器與散兵，但怕長矛兵、條頓武士、熱那亞弩手與狂戰士。',
 'imperial-skirmisher':'越南與其盟友共享的特殊單位，是精銳散兵在第四時代的再升級（土耳其除外）。專門反制弓兵，也能消耗長矛兵；怕近戰單位與攻城器。',
 'jaguar-warrior':'阿茲特克的城堡特殊步兵，護甲不錯並對其他步兵有大量加成。擅長打步兵、散兵與建築，但怕弓兵、弩砲、投石車、火藥單位、投石手、騎士，以及拜占庭聖騎兵、貴族鐵騎。',
 'janissary':'土耳其的城堡特殊火槍兵，攻擊高、射程遠並帶近戰護甲，不必研發化學就能在第三時代訓練。能快速打爆步兵與建築，但怕散兵、弩砲、投石車、火砲、日本武士、哥德衛隊與傭兵。',
 'kamayuk':'印加的城堡特殊單位，手持超長槍的反騎兵步兵，能隔著一格出手。能剋騎兵、馬弓騎兵、散兵與長槍兵，但怕羽毛箭射手、投石手、火藥單位、弩砲、投石車、僧侶，以及拜占庭聖騎兵、條頓武士。',
 'karambit-warrior':'馬來的城堡特殊步兵，便宜又快，只佔半個人口，適合大量爆兵，但個體非常脆弱。可以淹沒散兵、戟兵、鷹勇士與衝撞車，卻怕弓兵、火藥單位、投石手，以及各種重步兵與重騎兵。',
 'keshik':'韃靼的城堡特殊騎兵，作戰時會緩慢賺取黃金。能對付步兵、弓兵、村民、攻城器、馬弓騎兵與輕騎兵，但怕長槍兵系、駱駝騎兵、阿拉伯奴隸兵、僧侶，以及戰象、貴族鐵騎、騎士。',
 'kipchak':'庫曼的城堡特殊單位，一次射出多支箭的馬弓騎兵（普通三發、精銳四發），只有第一發吃完整傷害與攻擊升級。擅長騷擾慢速近戰與衝撞車，但怕槍隊長、熱那亞弩手、哥德衛隊、戟兵、鷹勇士、標槍騎兵、駱駝系、藤甲弓兵與投石車、弩砲。',
 'knight':'第三時代馬廄訓練的主力重騎兵，泛用性高、是最常見的兵種之一。能壓制步兵、弓兵、村民、攻城器、馬弓騎兵與輕騎兵，但怕長槍兵系、駱駝騎兵、阿拉伯奴隸兵、僧侶，以及戰象、貴族鐵騎、條頓武士。',
 'konnik':'保加利亞的特殊騎兵，可在城堡或營壘訓練，戰馬倒下後會下馬變成步兵繼續作戰。騎乘時擅長打步兵、弓兵、村民與攻城器；騎兵狀態怕長槍兵、駱駝等反騎兵單位，下馬後則怕弓兵。',
 'leitis':'立陶宛的城堡特殊騎兵，攻擊單位時會無視對方護甲。特別適合對付條頓武士、貴族鐵騎等高甲部隊與散兵，但怕長槍兵系、槍隊長、駱駝騎兵、阿拉伯奴隸兵、熱那亞弩手、戰象、日本武士與僧侶。',
 'light-cavalry':'斥候在第三時代的升級，對僧侶與攻城器有加成，而且不花黃金。適合掠奪村民、弓兵、攻城器與僧侶，但與步兵或其他騎兵正面對戰時吃虧。',
 'long-swordsman':'民兵系在第三時代的升級，由兵營訓練的中階步兵。能對付散兵、駱駝、鷹勇士、輕騎兵與長矛兵，但怕弓兵、弩砲、火藥單位、投石手，以及拜占庭聖騎兵、豹勇士、條頓武士、貴族鐵騎。',
 'longboat':'維京的第二特殊單位，第三時代在碼頭建造，一次射出多支箭的戰船。能壓制運輸船、漁船、岸邊建築與單位，甚至勝過重型弩砲戰船與火砲戰船；但怕火戰船、龜甲船、箭塔、城堡與岸上的遠程攻城器。',
 'longbowman':'不列顛的城堡特殊弓兵，射程極遠但血量偏低。能在遠處消耗步兵與其他弓兵，但怕散兵、攻城器、騎兵、日本武士、哥德衛隊、鷹勇士與標槍騎兵。',
 'magyar-huszar':'馬扎爾的城堡特殊輕騎兵，速度快、對攻城器有加成，威力與騎士相近；研發科維尼安軍隊後不再花黃金，因此被當成垃圾兵。擅長追殺弓兵與攻城器，但怕長槍兵系、槍隊長、駱駝騎兵、阿拉伯奴隸兵、條頓武士、日本武士等。',
 'mameluke':'薩拉森的城堡特殊單位，騎駱駝、以短距離投擲攻擊（算近戰傷害），對騎兵有額外加成但造價昂貴。能打騎兵、馬弓騎兵、徒步弓兵與攻城器，但怕長矛兵、槍隊長、狂戰士、條頓武士、熱那亞弩手、駱駝騎兵與拜占庭聖騎兵。',
 'man-at-arms':'民兵在第二時代的升級，面對第二時代多數單位都佔優，常用來騷擾對手經濟。能擊敗散兵、斥候、鷹斥候、長槍兵與村民，但怕弓兵與弩砲。',
 'mangonel':'第三時代的遠程攻城器，投擲造成範圍傷害的石彈，是密集弓兵的惡夢，還能預判走位砸地；缺點是射速慢、有最小射程。能擊碎成群單位、弓兵、村民、弩砲與建築，但怕近戰騎兵、馬扎爾驃騎兵、蒙古突騎、菘藍武士、傭兵與鷹勇士突襲。',
 'mangudai':'蒙古的城堡特殊馬弓騎兵，射速與移動都很快，對攻城器有加成。擅長屠殺步兵、村民與衝撞車，但怕駱駝系、駱駝弓騎兵、槍隊長、戟兵、熱那亞弩手、哥德衛隊、鷹勇士、散兵與日本武士。',
 'militia':'第一時代唯一能生產的軍事單位，是兵營的基礎步兵與民兵系的起點。只能欺負散兵、斥候、長槍兵與村民，幾乎所有其他單位都能打敗它。',
 'missionary':'西班牙的第二特殊單位，在修道院訓練的騎馬傳教者，移動快但治療與招降能力不如僧侶，也不能撿聖物。適合招降騎士等慢速、無射程的單位及可招降的建築，但怕弓兵、輕騎兵、駱駝騎兵、戟兵、鷹勇士、熱那亞弩手與防禦建築。',
 'monk':'修道院訓練的宗教單位，本身沒有攻擊力，卻能招降敵軍、治療友軍（船隻與攻城器除外）並運送聖物，研發修道院科技後會大幅變強。天敵是對僧侶有加成的斥候系與鷹斥候系，機動性高的單位能在招降完成前把它砍倒。',
 'onager':'輕型投石車在第四時代的升級，射程更遠、範圍傷害更大，能一擊打垮成群的輕裝弓兵，還能砸樹開路；匈人與土耳其無法升級。擅長打成群單位、弓兵、村民與建築，但怕近戰騎兵、馬扎爾驃騎兵、蒙古突騎、菘藍武士、傭兵、鷹勇士與火砲。',
 'organ-gun':'葡萄牙的城堡特殊單位，第三時代就能生產的火藥攻城器，朝前方齊射造成範圍傷害，對衝撞車有加成。擅長掃蕩密集部隊、村民與散兵，但怕騎兵、日本武士、傭兵、哥德衛隊、火砲、投石車、蒙古突騎與馬扎爾驃騎兵。',
 'paladin':'騎士系的最終升級（新譯聖騎士），第四時代最強勢的兵種之一。能碾壓步兵、弓兵、村民、攻城器、馬弓騎兵與輕騎兵；但長槍兵系、駱駝騎兵、阿拉伯奴隸兵、僧侶，以及戰象、貴族鐵騎、條頓武士仍能剋制它。',
 'petard':'在城堡訓練的自爆攻城單位，比多數攻城器跑得快，一次引爆就能對城牆、建築與攻城器造成毀滅性傷害。怕弓兵、馬弓騎兵、蒙古突騎、弩砲，以及近戰單位（尤其馬扎爾驃騎兵）。',
 'pikeman':'長槍兵在第三時代的升級，專剋騎兵（拜占庭聖騎兵除外），不花黃金屬垃圾兵；土耳其沒有此單位。除騎兵以外傷害都很低，怕步兵、弓兵、弩砲、土耳其火槍兵、投石手與拜占庭聖騎兵。',
 'plumed-archer':'馬雅在征服者入侵登場的城堡特殊弓兵，速度快、護甲佳，搭配馬雅的折扣成為性價比極高的射手。擅長打步兵、其他弓兵與火槍兵，但怕散兵、弩砲、投石車、騎兵、哥德衛隊、鷹勇士、藤甲弓兵與標槍騎兵。',
 'rattan-archer':'越南在王者崛起登場的城堡特殊弓兵，遠程護甲非常高，專門反制其他射手。能打步兵與弓兵，但怕騎兵、哥德衛隊、鷹勇士與攻城器。',
 'samurai':'日本的城堡特殊步兵，攻擊速度快，對各國特殊單位有額外加成（帝王駱駝騎兵與帝王戰矛兵除外）。擅長獵殺特殊單位、鷹勇士與建築，但怕弓兵、火槍兵與騎士。',
 'scorpion':'攻城器工坊的弩砲，射出能貫穿一排敵人的大箭，不會誤傷友軍，適合在混戰中支援。能打成群弓兵、村民、慢速單位與建築，但怕近戰騎兵、馬扎爾驃騎兵、蒙古突騎、投石車、鷹勇士、菘藍武士、哥德衛隊與遠程單位。',
 'scout':'第二時代的偵察騎兵，血量與速度佔優，開局那隻會自動探路，對僧侶有加成且較難被招降；不花黃金屬垃圾兵，美洲三國無法使用。擅長騷擾村民、弓兵、攻城器與僧侶，但打不過步兵與其他騎兵。',
 'serjeant':'西西里的特殊重步兵，第二時代起即可在城樓或城堡訓練，還能自行建造城樓。能對付村民、散兵、戟兵、輕騎兵與鷹勇士，但怕弩砲、投石車、火藥單位、投石手，以及拜占庭聖騎兵、豹勇士、日本武士、烈堤司、遊俠等。',
 'shotel-warrior':'衣索比亞的城堡特殊步兵，速度快、攻擊高、訓練迅速，但血量與護甲都很薄。擅長突襲村民、散兵、長矛兵、攻城器、輕騎兵與僧侶，但怕馬弓騎兵、投石車、火槍兵、重騎兵與其他步兵。',
 'siege-onager':'中型投石車的最終升級，第四時代要花大量食物與黃金研發，只有少數文明擁有。範圍傷害極強，擅長砸毀建築、村民、弓兵與密集部隊，但怕近戰騎兵、馬扎爾驃騎兵、蒙古突騎、菘藍武士、傭兵、鷹勇士與火砲。',
 'siege-ram':'衝撞車系的最終升級（俗稱大衝車），第四時代研發，拆建築的破壞力驚人，常被視為判斷文明後期強弱的指標；駐紮步兵可提升移動速度。怕近戰單位（尤其馬扎爾驃騎兵）、蒙古突騎與投石車。',
 'siege-tower':'失落的帝國加入、非洲王國起可在攻城器工坊訓練的運兵攻城塔，本身無法攻擊，用來把部隊送過城牆。沒有擅長對付的目標，怕近戰單位、馬扎爾驃騎兵與鷹勇士。',
 'skirmisher':'第二時代於靶場訓練的散兵，不花黃金的垃圾兵，專門反制弓兵。面對近戰單位與攻城器則幾乎無力。',
 'slinger':'印加的第二特殊單位，第三時代於靶場生產，是專門反步兵的遠程單位，沒有精銳版。擅長打步兵與村民，但怕散兵、弩砲、投石車、哥德衛隊、騎兵、標槍騎兵與藤甲弓兵。',
 'spearman':'第二時代兵營訓練的長槍兵，便宜又不花黃金，是早期防範斥候的主力。專門剋制騎馬單位（拜占庭聖騎兵例外），但會被步兵、弓兵與弩砲壓制。',
 'steppe-lancer':'決定版新增、第三時代於馬廄訓練的輕型長矛騎兵，能隔著一格出手。擅長獵殺村民、弓兵、散兵、攻城器與輕騎兵，但對上重騎兵、步兵與駱駝部隊吃虧。',
 'tarkan':'匈人的城堡特殊騎兵，遠防與血量高，專長拆建築，研發掠奪者後可在馬廄訓練。能打弓兵、攻城器、輕騎兵與建築，但怕步兵、重騎兵、熱那亞弩手、阿拉伯奴隸兵與駱駝騎兵。',
 'teutonic-knight':'條頓的城堡特殊步兵，移動極慢，但攻擊、護甲與血量都非常出色，近戰幾乎難逢敵手，能解決散兵、近戰單位與建築。弓兵、火藥單位、投石手、弩砲、投石車與僧侶能從遠處剋它，拜占庭聖騎兵、豹勇士、日本武士與烈堤司也不怕它。',
 'throwing-axeman':'法蘭克的城堡特殊步兵，以擲斧做短距離攻擊，但站方不把它算作遠距離單位。能對付散兵、戟兵、鷹勇士、哥德衛隊、駱駝、輕騎兵、衝撞車與建築，但怕弓兵、火藥單位、投石手，以及豹勇士、日本武士、條頓武士等重步兵與重騎兵。',
 'trade-cart':'第二時代起於市集生產的經濟單位，往返己方與他方市集賺取黃金，距離越遠收入越多，是後期黃金的重要來源。沒有戰鬥能力，任何敵軍都能輕易擊殺，必須保護貿易路線。',
 'trade-cog':'第二時代由碼頭建造、不能攻擊的貿易船，走海路往返碼頭賺取黃金。毫無自保能力，任何敵方單位都能威脅它。',
 'transport-ship':'在碼頭建造的運兵船，能載陸軍渡海偷襲，遠防不錯但血量低，載量可靠科技提升；沉沒時船上部隊全數陣亡。本身無法攻擊，需要戰船或火戰船護航。',
 'trebuchet':'第四時代於城堡生產的巨型投石機，射程最遠、威力最強的攻城武器，能摧毀幾乎所有建築，需先組裝才能攻擊。怕近戰單位（尤其馬扎爾驃騎兵與鷹勇士）、投石車與火砲。',
 'turtle-ship':'朝鮮在征服者入侵登場的第二特殊單位，第三時代於碼頭建造，是裝甲極厚的近距離火砲船。擅長近距離擊沉船隻、轟炸岸邊建築與單位，但怕火砲、巨型投石機、城堡、箭塔與僧侶。',
 'two-handed-swordsman':'民兵系在第四時代的第四級，除波斯外各文明都能訓練。能打散兵、戟兵、駱駝、鷹勇士、輕騎兵與建築，但怕弓兵、弩砲、火藥單位、投石手，以及拜占庭聖騎兵、豹勇士、條頓武士、貴族鐵騎。',
 'villager':'第一時代就能在城鎮中心訓練，是唯一能採集資源與建造建築的核心單位，也負責修理攻城器與建築。戰鬥力很弱，幾乎任何軍隊都能輕易擊殺，但能拆衝撞車系與巨型投石機。',
 'war-elephant':'波斯的城堡特殊單位，緩慢卻破壞力驚人的大象騎兵，會踐踏周圍敵人並對建築有加成，同成本下甚至能擊敗遊俠。能壓垮大部分近戰單位、散兵、火砲與建築，但怕長槍兵系、槍隊長、阿拉伯奴隸兵、駱駝騎兵、熱那亞弩手與僧侶。',
 'war-galley':'戰船在第三時代的升級，攻擊只打單一目標、沒有貫穿效果。擅長清除運輸船、漁船與岸邊單位，但怕火戰船、龜甲船、維京大戰船、箭塔、城堡與岸上攻城器。',
 'war-wagon':'朝鮮的城堡特殊單位，屬於馬弓騎兵類的戰車，遠防與血量都很高。擅長壓制步兵與弓兵，但怕騎兵、長槍兵、駱駝騎兵、槍隊長、精銳散兵、日本武士、鷹勇士、投石車與僧侶。',
 'woad-raider':'塞爾特的城堡特殊步兵，跑得極快、生產迅速，對建築有高攻擊。擅長偷襲攻城器、散兵、戟兵、鷹勇士、哥德衛隊與建築，但怕大量弓兵、火藥單位、投石手、重騎兵，以及日本武士、條頓武士等重步兵。',
 'xolotl-warrior':'決定版加入的美洲騎兵，數值與騎士相同，只有阿茲特克與印加能靠招降敵方馬廄來訓練。能擊敗步兵、弓兵、村民、攻城器與輕騎兵，但怕長槍兵系、駱駝騎兵、阿拉伯奴隸兵、僧侶與戰象等。',
};
// What each of this game's units is good and bad against, naming only units the game has (keyed by unit kind).
// Units whose reference page belongs to an upgrade of another line under another name: the War Galley research turns
// fire galleys into fire ships and demolition rafts into demolition ships (step id on the card: the site's unit id).
export const stepAliases:Readonly<Record<string,Readonly<Record<string,string>>>>={'fire-galley':{'war-galley':'fire-ship'},'demolition-raft':{'war-galley':'demolition-ship'}};
export const unitCounters:Readonly<Record<string,{strong:string;weak:string}>>={
 villager:{strong:'採集、建造與修理；敵軍來襲時可以躲進城鎮中心一起射箭。',weak:'幾乎所有軍隊，尤其是斥候系與馬弓騎兵的騷擾。'},
 militia:{strong:'早期的建築與村民，升級到後期後也能正面硬拚散兵、長槍兵與攻城器。',weak:'弓兵系與騎兵；行動慢，容易被放風箏。'},
 spearman:{strong:'騎兵與駱駝，戰象與騎士都怕它。',weak:'弓兵系、民兵系，以及專剋步兵的拜占庭聖騎兵。'},
 archer:{strong:'步兵、長槍兵與村民，成群時能遠遠集火。',weak:'散兵、斥候系與騎士衝鋒，以及投石車的範圍傷害。'},
 skirmisher:{strong:'弓兵系與長槍兵，遠程護甲高，便宜又不吃黃金。',weak:'騎兵、民兵系與攻城器；對其他單位傷害很低。'},
 'cavalry-archer':{strong:'步兵、長槍兵與村民，能邊退邊射。',weak:'散兵、駱駝與輕騎兵追擊，也怕弩砲與投石車。'},
 scout:{strong:'村民、僧侶、攻城器與零散的弓兵；跑得快，適合偵察與騷擾。',weak:'長槍兵系與駱駝，也打不過騎士正面交鋒。'},
 knight:{strong:'弓兵、散兵、攻城器與多數步兵，正面衝鋒最可靠。',weak:'長槍兵系、駱駝與僧侶轉化；昂貴又吃黃金。'},
 camel:{strong:'騎士系與其他騎兵，也能追殺馬弓騎兵。',weak:'長槍兵系、弓兵與民兵系；打步兵與建築都不擅長。'},
 ram:{strong:'建築，幾乎不怕箭塔、城堡與弓兵的箭。',weak:'近戰步兵與騎兵；本身不能攻擊單位。'},
 mangonel:{strong:'成群的弓兵與步兵，一發石彈就能打中整團。',weak:'騎兵與民兵系近身；目標太近時無法開火。'},
 scorpion:{strong:'成串站位的步兵與弓兵，弩箭會穿過目標繼續傷人；對戰象也有加成。',weak:'騎兵近身與投石車；目標太近時無法開火。'},
 trebuchet:{strong:'城堡、箭塔與所有建築，射程遠到能在防線外開火。',weak:'任何近身的單位；架設與收起都要時間，不能攻擊單位。'},
 petard:{strong:'城門、箭塔與城堡，以及停在一起的攻城器。',weak:'接近目標前就被射倒；炸完即消耗。'},
 monk:{strong:'轉化騎士、戰象、攻城器這類昂貴單位，並治療友軍。',weak:'斥候系與快速騎兵，也怕成群弓兵集火。'},
 longbowman:{strong:'步兵與長槍兵，射程長，能在防線後方輸出。',weak:'散兵、騎兵衝鋒與投石車。'},
 'woad-raider':{strong:'建築、攻城器與弓兵，跑得快適合偷襲。',weak:'騎士系、弓兵集火與強力近戰步兵。'},
 'throwing-axeman':{strong:'長槍兵、步兵與攻城槌，能在短距離外出手。',weak:'騎士系與弓兵打帶跑。'},
 huskarl:{strong:'弓兵系與建築，幾乎不怕箭。',weak:'騎士系、條頓武士與日本武士這類近戰單位。'},
 'teutonic-knight':{strong:'步兵、騎兵與建築的正面消耗戰。',weak:'弓兵系打帶跑、散兵與僧侶轉化；移動非常慢。'},
 berserk:{strong:'長槍兵、斥候系與其他步兵，受傷後自己回血。',weak:'弓兵系、騎士系與日本武士。'},
 cataphract:{strong:'所有步兵，尤其是長槍兵系；後勤讓它還能踐踏周圍敵兵。',weak:'弓兵系、駱駝與僧侶轉化。'},
 'war-elephant':{strong:'近戰部隊與建築，生命極高。',weak:'長槍兵系、僧侶轉化與攻城器；移動非常慢。'},
 mameluke:{strong:'騎士系、駱駝與其他騎兵，能在短距離外出手。',weak:'長槍兵系、弓兵與條頓武士。'},
 janissary:{strong:'步兵、騎兵與攻城器，攻擊高、射程遠。',weak:'弓兵系、散兵、騎兵衝鋒與投石車；射速慢。'},
 'chu-ko-nu':{strong:'步兵與攻城槌，一次射出好幾支箭。',weak:'散兵、騎兵衝鋒與投石車；射程較短。'},
 samurai:{strong:'所有特殊單位，攻擊速度極快。',weak:'弓兵系與騎士系。'},
 mangudai:{strong:'攻城器、村民與僧侶，射速快又機動。',weak:'散兵、長槍兵系與成群的輕騎兵。'},
 'hand-cannoneer':{strong:'步兵與長槍兵，一發就打掉一大截生命。',weak:'散兵、弓兵與騎兵衝鋒，也怕投石車；射速慢，近身就難以自保。'},
 'bombard-cannon':{strong:'城堡、箭塔與所有建築，也能點掉投石車、弩砲這類攻城器。',weak:'任何貼身的騎兵與步兵；移動慢，要有部隊護送。'},
 'fishing-ship':{strong:'捕撈深水魚群、搭建並採集魚網，把食物送回碼頭。',weak:'所有戰船與岸邊的弓兵；沒有任何攻擊能力。'},
 'transport-ship':{strong:'載著陸軍渡湖，從對手沒防備的岸邊登陸。',weak:'戰船、火船與自爆船；沉沒時船上的部隊全數陣亡。'},
 'trade-cog':{strong:'在己方與對手的碼頭之間往返，為後期提供黃金。',weak:'任何敵方戰船；不能攻擊，航線要有護航。'},
 'trade-cart':{strong:'在己方與對手的市集之間往返，距離越遠收入越多。',weak:'斥候系與任何騎兵；不能攻擊，商路要有部隊保護。'},
 galley:{strong:'漁船、運輸船與其他船隻，也能射擊岸邊的單位與建築。',weak:'火船近身噴火、自爆船與岸邊的箭塔、城堡。'},
 'fire-galley':{strong:'戰船系與其他船隻，貼近後以極快的頻率噴火。',weak:'自爆船與岸上的箭塔、城堡；射程很短，打建築與陸地單位都不擅長。'},
 'demolition-raft':{strong:'擠在一起的船隊、碼頭與岸邊建築，一次爆炸波及整片範圍。',weak:'戰船在遠處把它射沉；炸完即消耗。'},
 'cannon-galleon':{strong:'岸邊的建築與攻城器，射程遠到能在箭塔射程外開火。',weak:'戰船、火船與自爆船；貼近的目標打不到，射速也慢。'},
 longboat:{strong:'漁船、運輸船與其他戰船，一次射出好幾支箭。',weak:'火船近身噴火、自爆船與岸上的箭塔、城堡。'},
};

// ── Category 科技 ──────────────────────────────────────────────────────────────────────────────────────────────────
// aoetw.com's technology pages (pages/techs/*.vue of github.com/webrsb/aoetw, read 2026-10-01): every technology with
// the site's names, its research building (the site's), age and owning civilization. Text only; costs, times and
// effects on the page come from rules.ts, civ.ts and the effect tables.
export const techsIntro='科技資料整理自 aoetw.com（世紀帝國 II 的繁體中文百科，內容約在 HD／UserPatch 到早期決定版之間）。卡片上的價格、時間與效果都取自本作的模擬，是依本作比例自訂的 design_default，不是原作數據。';
// Why some of the site's technologies are not in this game (the overview's second paragraph).
export const techsMissingText='aoetw 收錄、本作沒有的科技各附原因：市集的製圖學、鑄幣術與銀行制度是給盟友共享視野與進貢用的，一對一沒有盟友；本作每一發都會命中，彈道學與拇指環的命中效果沒有對應；箭塔沒有最短射程，近射孔沒有作用；追蹤技術在 aoetw 的版本已併入第二時代；也沒有弒君模式，間諜與叛徒不收錄。';
// The footnote of every technology page.
export const techsNote='科技資料整理自 aoetw.com（HD／UserPatch 到早期決定版），說明已改用本作的單位、建築與時代名稱；價格、時間與效果一律取自本作的模擬，是 design_default，不是原作數據。標示「尚未實作」的科技目前不在遊戲裡。';
// What each building researches (paraphrased from the site's building groups; keyed by this game's building id).
export const techBuildingText:Readonly<Record<string,string>>={
 'town-center':'研究村民的生存力、搬運量與建築視野，也是升級時代的地方。',
 'lumber-camp':'研究加快村民伐木的科技。','mining-camp':'研究加快村民採金與採石的科技。','mill':'研究增加農田食物的科技。',
 barracks:'研究步兵相關科技：移動速度、民兵系的造價，以及拆除建築的能力。','archery-range':'研究強化弓兵與馬弓騎兵作戰能力的科技。',
 stable:'研究提升騎兵與駱駝騎兵生命與移動速度的科技。',blacksmith:'研究所有軍事單位的攻擊與護甲升級。',
 monastery:'研究強化僧侶轉化、生存與機動的宗教科技，以及抵抗敵方轉化的科技。',
 university:'研究建築防禦、攻城器與化學、箭塔與城牆的升級，以及火砲塔。',
 castle:'研究各文明的特殊科技，以及徵兵技術、兵工學、圍牆這些第四時代的通用科技。',
 market:'研究加快貿易單位與降低買賣手續費的經濟科技。',dock:'研究船隻護甲、航速、造船成本與漁船效率等海軍科技，以及各船系的升級。',
};
// Why an aoetw technology is not in this game (the page model picks one per technology; greek-fire's comes from civs.ts).
export const techPendingReasons={allies:'本作是一對一對戰，沒有盟友可以共享視野或進貢',accuracy:'本作每一發都會命中，沒有命中率可以提升',
 minRange:'本作的箭塔與城堡沒有最短射程',tracking:'aoetw 收錄的版本已把它併入第二時代，升時代就自動生效',
 regicide:'本作是一對一對戰，也沒有弒君模式',civ:'本作只有 13 個原版文明'} as const;
export const techPendingKind:Readonly<Record<string,keyof typeof techPendingReasons>>={tracking:'tracking',
 cartography:'allies',coinage:'allies',banking:'allies',spies:'regicide',treason:'regicide',ballistics:'accuracy','murder-holes':'minRange'};
// Parts of a reference technology this game leaves out although the technology itself is here.
export const techPartials:Readonly<Record<string,string>>={
 loom:'原作還讓村民的近戰與遠程護甲提高',wheelbarrow:'原作還讓村民走得更快',
 'hand-cart':'原作還讓村民再走快一些','thumb-ring':'原作還讓弓兵對靜止目標百發百中；本作每一發都會命中',
 fletching:'原作也加強城鎮中心、箭塔與城堡的箭；本作只作用在單位（弓兵與戰艦）上',
 'bodkin-arrow':'原作也加強城鎮中心、箭塔與城堡的箭；本作只作用在單位（弓兵與戰艦）上',
 bracer:'原作也加強城鎮中心、箭塔與城堡的箭；本作只作用在單位（弓兵與戰艦）上',
};
// page: the site's path (null: no page of its own).
export type AoetwTech={id:string;name:string;nameEn:string;at:string;age:number;kind:'generic'|'unique'|'age';civ:string|null;page:string|null};
export const aoetwTechs:readonly AoetwTech[]=[
 {id:'tracking',name:'追蹤技術',nameEn:'Tracking',at:'軍營',age:2,kind:'generic',civ:null,page:'techs/Tracking'},
 {id:'supplies',name:'供給',nameEn:'Supplies',at:'軍營',age:2,kind:'generic',civ:null,page:'techs/Supplies'},
 {id:'squires',name:'護衛技術',nameEn:'Squires',at:'軍營',age:3,kind:'generic',civ:null,page:'techs/Squires'},
 {id:'arson',name:'縱火',nameEn:'Arson',at:'軍營',age:3,kind:'generic',civ:null,page:'techs/Arson'},
 {id:'thumb-ring',name:'拇指環',nameEn:'Thumb Ring',at:'射箭場',age:3,kind:'generic',civ:null,page:'techs/Thumb_Ring'},
 {id:'parthian-tactics',name:'安息人戰術',nameEn:'Parthian Tactics',at:'射箭場',age:4,kind:'generic',civ:null,page:'techs/Parthian_Tactics'},
 {id:'bloodlines',name:'品種',nameEn:'Bloodlines',at:'馬廄',age:2,kind:'generic',civ:null,page:'techs/Bloodlines'},
 {id:'husbandry',name:'耕種技術',nameEn:'Husbandry',at:'馬廄',age:3,kind:'generic',civ:null,page:'techs/Husbandry'},
 {id:'loom',name:'織布技術',nameEn:'Loom',at:'城鎮中心',age:1,kind:'generic',civ:null,page:'techs/Loom'},
 {id:'wheelbarrow',name:'輪軸技術',nameEn:'Wheelbarrow',at:'城鎮中心',age:2,kind:'generic',civ:null,page:'techs/Wheelbarrow'},
 {id:'hand-cart',name:'手推車',nameEn:'Hand Cart',at:'城鎮中心',age:3,kind:'generic',civ:null,page:'techs/Hand_Cart'},
 {id:'town-watch',name:'城鎮瞭望',nameEn:'Town Watch',at:'城鎮中心',age:2,kind:'generic',civ:null,page:'techs/Town_Watch'},
 {id:'town-patrol',name:'城鎮巡邏',nameEn:'Town Patrol',at:'城鎮中心',age:3,kind:'generic',civ:null,page:'techs/Town_Patrol'},
 {id:'redemption',name:'神聖思想',nameEn:'Redemption',at:'修道院',age:3,kind:'generic',civ:null,page:'techs/Redemption'},
 {id:'atonement',name:'救贖思想',nameEn:'Atonement',at:'修道院',age:3,kind:'generic',civ:null,page:'techs/Atonement'},
 {id:'herbal-medicine',name:'草藥治療',nameEn:'Herbal Medicine',at:'修道院',age:3,kind:'generic',civ:null,page:'techs/Herbal_Medicine'},
 {id:'heresy',name:'異端邪說',nameEn:'Heresy',at:'修道院',age:3,kind:'generic',civ:null,page:'techs/Heresy'},
 {id:'sanctity',name:'聖潔虔誠',nameEn:'Sanctity',at:'修道院',age:3,kind:'generic',civ:null,page:'techs/Sanctity'},
 {id:'fervor',name:'宗教狂熱',nameEn:'Fervor',at:'修道院',age:3,kind:'generic',civ:null,page:'techs/Fervor'},
 {id:'faith',name:'忠誠信仰',nameEn:'Faith',at:'修道院',age:4,kind:'generic',civ:null,page:'techs/Faith'},
 {id:'illumination',name:'啟示思想',nameEn:'Illumination',at:'修道院',age:4,kind:'generic',civ:null,page:'techs/Illumination'},
 {id:'block-printing',name:'印刷技術',nameEn:'Block Printing',at:'修道院',age:4,kind:'generic',civ:null,page:'techs/Block_Printing'},
 {id:'theocracy',name:'神權統治',nameEn:'Theocracy',at:'修道院',age:4,kind:'generic',civ:null,page:'techs/Theocracy'},
 {id:'cartography',name:'製圖學',nameEn:'Cartography',at:'市集',age:2,kind:'generic',civ:null,page:'techs/Cartography'},
 {id:'caravan',name:'商隊',nameEn:'Caravan',at:'市集',age:3,kind:'generic',civ:null,page:'techs/Caravan'},
 {id:'coinage',name:'鑄幣術',nameEn:'Coinage',at:'市集',age:3,kind:'generic',civ:null,page:'techs/Coinage'},
 {id:'banking',name:'銀行制度',nameEn:'Banking',at:'市集',age:4,kind:'generic',civ:null,page:'techs/Banking'},
 {id:'guilds',name:'公會制度',nameEn:'Guilds',at:'市集',age:4,kind:'generic',civ:null,page:'techs/Guilds'},
 {id:'spies',name:'間諜',nameEn:'Spies',at:'城堡',age:4,kind:'generic',civ:null,page:'techs/Spies'},
 {id:'treason',name:'叛徒',nameEn:'Treason',at:'城堡',age:4,kind:'generic',civ:null,page:null},
 {id:'hoardings',name:'圍牆',nameEn:'Hoardings',at:'城堡',age:4,kind:'generic',civ:null,page:'techs/Hoardings'},
 {id:'sappers',name:'兵工學',nameEn:'Sappers',at:'城堡',age:4,kind:'generic',civ:null,page:'techs/Sappers'},
 {id:'conscription',name:'徵兵技術',nameEn:'Conscription',at:'城堡',age:4,kind:'generic',civ:null,page:'techs/Conscription'},
 {id:'careening',name:'航海技術',nameEn:'Careening',at:'碼頭',age:3,kind:'generic',civ:null,page:'techs/Careening'},
 {id:'dry-dock',name:'船塢',nameEn:'Dry Dock',at:'碼頭',age:4,kind:'generic',civ:null,page:'techs/Dry_Dock'},
 {id:'shipwright',name:'造船員',nameEn:'Shipwright',at:'碼頭',age:4,kind:'generic',civ:null,page:'techs/Shipwright'},
 {id:'gillnets',name:'流刺網',nameEn:'Gillnets',at:'碼頭',age:3,kind:'generic',civ:null,page:'techs/Gillnets'},
 {id:'masonry',name:'磚瓦技術',nameEn:'Masonry',at:'學院',age:3,kind:'generic',civ:null,page:'techs/Masonry'},
 {id:'ballistics',name:'彈道學',nameEn:'Ballistics',at:'學院',age:3,kind:'generic',civ:null,page:'techs/Ballistics'},
 {id:'heated-shot',name:'火箭',nameEn:'Heated Shot',at:'學院',age:3,kind:'generic',civ:null,page:'techs/Heated_Shot'},
 {id:'murder-holes',name:'近射孔',nameEn:'Murder Holes',at:'學院',age:3,kind:'generic',civ:null,page:'techs/Murder_Holes'},
 {id:'treadmill-crane',name:'磨坊水車',nameEn:'Treadmill Crane',at:'學院',age:3,kind:'generic',civ:null,page:'techs/Treadmill_Crane'},
 {id:'architecture',name:'建築學',nameEn:'Architecture',at:'學院',age:4,kind:'generic',civ:null,page:'techs/Architecture'},
 {id:'chemistry',name:'化學',nameEn:'Chemistry',at:'學院',age:4,kind:'generic',civ:null,page:'techs/Chemistry'},
 {id:'siege-engineers',name:'攻城工程師',nameEn:'Siege Engineers',at:'學院',age:4,kind:'generic',civ:null,page:'techs/Siege_Engineers'},
 {id:'arrowslits',name:'箭狹槽',nameEn:'Arrowslits',at:'學院',age:4,kind:'generic',civ:null,page:'techs/Arrowslits'},
 {id:'padded-archer-armor',name:'弓兵護甲',nameEn:'Padded Archer Armor',at:'兵工廠',age:2,kind:'generic',civ:null,page:'techs/Padded_Archer_Armor'},
 {id:'leather-archer-armor',name:'弓兵皮甲',nameEn:'Leather Archer Armor',at:'兵工廠',age:3,kind:'generic',civ:null,page:'techs/Leather_Archer_Armor'},
 {id:'ring-archer-armor',name:'弓兵鏈甲',nameEn:'Ring Archer Armor',at:'兵工廠',age:4,kind:'generic',civ:null,page:'techs/Ring_Archer_Armor'},
 {id:'fletching',name:'絕世好箭',nameEn:'Fletching',at:'兵工廠',age:2,kind:'generic',civ:null,page:'techs/Fletching'},
 {id:'bodkin-arrow',name:'羽箭',nameEn:'Bodkin Arrow',at:'兵工廠',age:3,kind:'generic',civ:null,page:'techs/Bodkin_Arrow'},
 {id:'bracer',name:'強力護腕',nameEn:'Bracer',at:'兵工廠',age:4,kind:'generic',civ:null,page:'techs/Bracer'},
 {id:'forging',name:'鍛造技術',nameEn:'Forging',at:'兵工廠',age:2,kind:'generic',civ:null,page:'techs/Forging'},
 {id:'iron-casting',name:'鑄造技術',nameEn:'Iron Casting',at:'兵工廠',age:3,kind:'generic',civ:null,page:'techs/Iron_Casting'},
 {id:'blast-furnace',name:'鼓風爐',nameEn:'Blast Furnace',at:'兵工廠',age:4,kind:'generic',civ:null,page:'techs/Blast_Furnace'},
 {id:'scale-barding-armor',name:'鱗鎧甲',nameEn:'Scale Barding Armor',at:'兵工廠',age:2,kind:'generic',civ:null,page:'techs/Scale_Barding_Armor'},
 {id:'chain-barding-armor',name:'鏈鎧甲',nameEn:'Chain Barding Armor',at:'兵工廠',age:3,kind:'generic',civ:null,page:'techs/Chain_Barding_Armor'},
 {id:'plate-barding-armor',name:'鐵鎧甲',nameEn:'Plate Barding Armor',at:'兵工廠',age:4,kind:'generic',civ:null,page:'techs/Plate_Barding_Armor'},
 {id:'scale-mail-armor',name:'步兵鱗甲',nameEn:'Scale Mail Armor',at:'兵工廠',age:2,kind:'generic',civ:null,page:'techs/Scale_Mail_Armor'},
 {id:'chain-mail-armor',name:'步兵鏈甲',nameEn:'Chain Mail Armor',at:'兵工廠',age:3,kind:'generic',civ:null,page:'techs/Chain_Mail_Armor'},
 {id:'plate-mail-armor',name:'步兵板甲',nameEn:'Plate Mail Armor',at:'兵工廠',age:4,kind:'generic',civ:null,page:'techs/Plate_Mail_Armor'},
 {id:'gold-mining',name:'採金技術',nameEn:'Gold Mining',at:'採礦營地',age:2,kind:'generic',civ:null,page:'techs/Gold_Mining'},
 {id:'stone-mining',name:'採石技術',nameEn:'Stone Mining',at:'採礦營地',age:2,kind:'generic',civ:null,page:'techs/Stone_Mining'},
 {id:'gold-shaft-mining',name:'採金裝置',nameEn:'Gold Shaft Mining',at:'採礦營地',age:3,kind:'generic',civ:null,page:'techs/Gold_Shaft_Mining'},
 {id:'stone-shaft-mining',name:'採石裝置',nameEn:'Stone Shaft Mining',at:'採礦營地',age:3,kind:'generic',civ:null,page:'techs/Stone_Shaft_Mining'},
 {id:'double-bit-axe',name:'雙面斧',nameEn:'Double-Bit Axe',at:'伐木場',age:2,kind:'generic',civ:null,page:'techs/Double-Bit_Axe'},
 {id:'bow-saw',name:'弓形鋸',nameEn:'Bow Saw',at:'伐木場',age:3,kind:'generic',civ:null,page:'techs/Bow_Saw'},
 {id:'two-man-saw',name:'雙人鋸',nameEn:'Two-Man Saw',at:'伐木場',age:4,kind:'generic',civ:null,page:'techs/Two-Man_Saw'},
 {id:'horse-collar',name:'獸耕技術',nameEn:'Horse Collar',at:'磨坊',age:2,kind:'generic',civ:null,page:'techs/Horse_Collar'},
 {id:'heavy-plow',name:'重型耕犁',nameEn:'Heavy Plow',at:'磨坊',age:3,kind:'generic',civ:null,page:'techs/Heavy_Plow'},
 {id:'crop-rotation',name:'輪耕制度',nameEn:'Crop Rotation',at:'磨坊',age:4,kind:'generic',civ:null,page:'techs/Crop_Rotation'},
 {id:'fortified-wall',name:'垛牆',nameEn:'Fortified Wall',at:'學院',age:3,kind:'generic',civ:null,page:'building/Fortified_Wall'},
 {id:'guard-tower',name:'防禦箭塔',nameEn:'Guard Tower',at:'學院',age:3,kind:'generic',civ:null,page:'building/Guard_Tower'},
 {id:'keep',name:'大型箭塔',nameEn:'Keep',at:'學院',age:4,kind:'generic',civ:null,page:'building/Keep'},
 {id:'bombard-tower-tech',name:'火砲塔',nameEn:'Bombard Tower',at:'學院',age:4,kind:'generic',civ:null,page:'building/Bombard_Tower'},
 {id:'atlatl',name:'擲矛器',nameEn:'Atlatl',at:'城堡',age:3,kind:'unique',civ:'阿茲特克',page:'techs/Atlatl'},
 {id:'kasbah',name:'聚居堡壘',nameEn:'Kasbah',at:'城堡',age:3,kind:'unique',civ:'柏柏',page:'techs/Kasbah'},
 {id:'yeomen',name:'義勇騎兵',nameEn:'Yeomen',at:'城堡',age:3,kind:'unique',civ:'不列顛',page:'techs/Yeomen'},
 {id:'howdah',name:'象轎',nameEn:'Howdah',at:'城堡',age:3,kind:'unique',civ:'緬甸',page:'techs/Howdah'},
 {id:'greek-fire',name:'希臘之火',nameEn:'Greek Fire',at:'城堡',age:3,kind:'unique',civ:'拜占庭',page:'techs/Greek_Fire'},
 {id:'stronghold',name:'堡壘',nameEn:'Stronghold',at:'城堡',age:3,kind:'unique',civ:'塞爾特',page:'techs/Stronghold'},
 {id:'great-wall',name:'長城',nameEn:'Great Wall',at:'城堡',age:3,kind:'unique',civ:'中國',page:'techs/Great_Wall'},
 {id:'royal-heirs',name:'皇族血脈',nameEn:'Royal Heirs',at:'城堡',age:3,kind:'unique',civ:'衣索比亞',page:'techs/Royal_Heirs'},
 {id:'chivalry',name:'騎士精神',nameEn:'Chivalry',at:'城堡',age:3,kind:'unique',civ:'法蘭克',page:'techs/Chivalry'},
 {id:'anarchy',name:'無政府狀態',nameEn:'Anarchy',at:'城堡',age:3,kind:'unique',civ:'哥德',page:'techs/Anarchy'},
 {id:'marauders',name:'掠奪者',nameEn:'Marauders',at:'城堡',age:3,kind:'unique',civ:'匈人',page:'techs/Marauders'},
 {id:'andean-sling',name:'安地斯彈弓',nameEn:'Andean Sling',at:'城堡',age:3,kind:'unique',civ:'印加',page:'techs/Andean_Sling'},
 {id:'sultans',name:'蘇丹',nameEn:'Sultans',at:'城堡',age:3,kind:'unique',civ:'印度',page:'techs/Sultans'},
 {id:'pavise',name:'巨盾',nameEn:'Pavise',at:'城堡',age:3,kind:'unique',civ:'義大利',page:'techs/Pavise'},
 {id:'yasama',name:'射箭孔',nameEn:'Yasama',at:'城堡',age:3,kind:'unique',civ:'日本',page:'techs/Yasama'},
 {id:'tusk-swords',name:'象牙劍',nameEn:'Tusk Swords',at:'城堡',age:3,kind:'unique',civ:'高棉',page:'techs/Tusk_Swords'},
 {id:'eupseong',name:'邑城',nameEn:'Eupseong',at:'城堡',age:3,kind:'unique',civ:'朝鮮',page:'techs/Eupseong'},
 {id:'corvinian-army',name:'科維尼安軍隊',nameEn:'Corvinian Army',at:'城堡',age:3,kind:'unique',civ:'馬扎爾',page:'techs/Corvinian_Army'},
 {id:'thalassocracy',name:'海上霸主',nameEn:'Thalassocracy',at:'城堡',age:3,kind:'unique',civ:'馬來',page:'techs/Thalassocracy'},
 {id:'tigui',name:'部落領袖',nameEn:'Tigui',at:'城堡',age:3,kind:'unique',civ:'馬利',page:'techs/Tigui'},
 {id:'nomads',name:'游牧',nameEn:'Nomads',at:'城堡',age:3,kind:'unique',civ:'蒙古',page:'techs/Nomads'},
 {id:'kamandaran',name:'波斯弓兵',nameEn:'Kamandaran',at:'城堡',age:3,kind:'unique',civ:'波斯',page:'techs/Kamandaran'},
 {id:'carrack',name:'克拉克帆船',nameEn:'Carrack',at:'城堡',age:3,kind:'unique',civ:'葡萄牙',page:'techs/Carrack'},
 {id:'madrasah',name:'穆斯林學墊',nameEn:'Madrasah',at:'城堡',age:3,kind:'unique',civ:'薩拉森',page:'techs/Madrasah'},
 {id:'orthodoxy',name:'東正教',nameEn:'Orthodoxy',at:'城堡',age:3,kind:'unique',civ:'斯拉夫',page:'techs/Orthodoxy'},
 {id:'inquisition',name:'異端審判',nameEn:'Inquisition',at:'城堡',age:3,kind:'unique',civ:'西班牙',page:'techs/Inquisition'},
 {id:'ironclad',name:'鋼鐵甲',nameEn:'Ironclad',at:'城堡',age:3,kind:'unique',civ:'條頓',page:'techs/Ironclad'},
 {id:'sipahi',name:'采邑騎兵',nameEn:'Sipahi',at:'城堡',age:3,kind:'unique',civ:'土耳其',page:'techs/Sipahi'},
 {id:'chatras',name:'恰特拉傘',nameEn:'Chatras',at:'城堡',age:3,kind:'unique',civ:'越南',page:'techs/Chatras'},
 {id:'chieftains',name:'酋長',nameEn:'Chieftains',at:'城堡',age:3,kind:'unique',civ:'維京',page:'techs/Chieftains'},
 {id:'stirrups',name:'馬鐙',nameEn:'Stirrups',at:'城堡',age:3,kind:'unique',civ:'保加利亞',page:'techs/Stirrups'},
 {id:'steppe-husbandry',name:'大草原耕種技術',nameEn:'Steppe Husbandry',at:'城堡',age:3,kind:'unique',civ:'庫曼',page:'techs/Steppe_Husbandry'},
 {id:'hill-forts',name:'山城堡',nameEn:'Hill Forts',at:'城堡',age:3,kind:'unique',civ:'立陶宛',page:'techs/Hill_Forts'},
 {id:'silk-armor',name:'絲護甲',nameEn:'Silk Armor',at:'城堡',age:3,kind:'unique',civ:'韃靼',page:'techs/Silk_Armor'},
 {id:'garland-wars',name:'榮冠戰爭',nameEn:'Garland Wars',at:'城堡',age:4,kind:'unique',civ:'阿茲特克',page:'techs/Garland_Wars'},
 {id:'maghrabi-camels',name:'馬格拉比駱駝',nameEn:'Maghrabi Camels',at:'城堡',age:4,kind:'unique',civ:'柏柏',page:'techs/Maghrabi_Camels'},
 {id:'warwolf',name:'戰狼號',nameEn:'Warwolf',at:'城堡',age:4,kind:'unique',civ:'不列顛',page:'techs/Warwolf'},
 {id:'manipur-cavalry',name:'曼尼普爾騎兵',nameEn:'Manipur Cavalry',at:'城堡',age:4,kind:'unique',civ:'緬甸',page:'techs/Manipur_Cavalry'},
 {id:'logistica',name:'後勤',nameEn:'Logistica',at:'城堡',age:4,kind:'unique',civ:'拜占庭',page:'techs/Logistica'},
 {id:'furor-celtica',name:'塞爾特狂熱',nameEn:'Furor Celtica',at:'城堡',age:4,kind:'unique',civ:'塞爾特',page:'techs/Furor_Celtica'},
 {id:'rocketry',name:'火箭技術',nameEn:'Rocketry',at:'城堡',age:4,kind:'unique',civ:'中國',page:'techs/Rocketry'},
 {id:'torsion-engines',name:'扭力彈射器',nameEn:'Torsion Engines',at:'城堡',age:4,kind:'unique',civ:'衣索比亞',page:'techs/Torsion_Engines'},
 {id:'bearded-axe',name:'倒鉤斧',nameEn:'Bearded Axe',at:'城堡',age:4,kind:'unique',civ:'法蘭克',page:'techs/Bearded_Axe'},
 {id:'perfusion',name:'井噴',nameEn:'Perfusion',at:'城堡',age:4,kind:'unique',civ:'哥德',page:'techs/Perfusion'},
 {id:'atheism',name:'無神論',nameEn:'Atheism',at:'城堡',age:4,kind:'unique',civ:'匈人',page:'techs/Atheism'},
 {id:'fabric-shields',name:'織物盾',nameEn:'Fabric Shields',at:'城堡',age:4,kind:'unique',civ:'印加',page:'techs/Fabric_Shields'},
 {id:'shatagni',name:'印度火銃',nameEn:'Shatagni',at:'城堡',age:4,kind:'unique',civ:'印度',page:'techs/Shatagni'},
 {id:'silk-road',name:'絲綢之路',nameEn:'Silk Road',at:'城堡',age:4,kind:'unique',civ:'義大利',page:'techs/Silk_Road'},
 {id:'kataparuto',name:'彈射器',nameEn:'Kataparuto',at:'城堡',age:4,kind:'unique',civ:'日本',page:'techs/Kataparuto'},
 {id:'double-crossbow',name:'雙弩箭',nameEn:'Double Crossbow',at:'城堡',age:4,kind:'unique',civ:'高棉',page:'techs/Double_Crossbow'},
 {id:'shinkichon',name:'投擲器',nameEn:'Shinkichon',at:'城堡',age:4,kind:'unique',civ:'朝鮮',page:'techs/Shinkichon'},
 {id:'recurve-bow',name:'反曲弓',nameEn:'Recurve Bow',at:'城堡',age:4,kind:'unique',civ:'馬扎爾',page:'techs/Recurve_Bow'},
 {id:'forced-levy',name:'強制徵兵',nameEn:'Forced Levy',at:'城堡',age:4,kind:'unique',civ:'馬來',page:'techs/Forced_Levy'},
 {id:'farimba',name:'驃悍精神',nameEn:'Farimba',at:'城堡',age:4,kind:'unique',civ:'馬利',page:'techs/Farimba'},
 {id:'el-dorado',name:'黃金國',nameEn:'El Dorado',at:'城堡',age:4,kind:'unique',civ:'馬雅',page:'techs/El_Dorado'},
 {id:'drill',name:'鑿岩機',nameEn:'Drill',at:'城堡',age:4,kind:'unique',civ:'蒙古',page:'techs/Drill'},
 {id:'mahouts',name:'象伕',nameEn:'Mahouts',at:'城堡',age:4,kind:'unique',civ:'波斯',page:'techs/Mahouts'},
 {id:'arquebus',name:'火繩槍',nameEn:'Arquebus',at:'城堡',age:4,kind:'unique',civ:'葡萄牙',page:'techs/Arquebus'},
 {id:'zealotry',name:'狂熱',nameEn:'Zealotry',at:'城堡',age:4,kind:'unique',civ:'薩拉森',page:'techs/Zealotry'},
 {id:'druzhina',name:'王家侍從',nameEn:'Druzhina',at:'城堡',age:4,kind:'unique',civ:'斯拉夫',page:'techs/Druzhina'},
 {id:'supremacy',name:'霸權',nameEn:'Supremacy',at:'城堡',age:4,kind:'unique',civ:'西班牙',page:'techs/Supremacy'},
 {id:'crenellations',name:'砲門垛口',nameEn:'Crenellations',at:'城堡',age:4,kind:'unique',civ:'條頓',page:'techs/Crenellations'},
 {id:'artillery',name:'砲兵',nameEn:'Artillery',at:'城堡',age:4,kind:'unique',civ:'土耳其',page:'techs/Artillery'},
 {id:'paper-money',name:'紙幣',nameEn:'Paper Money',at:'城堡',age:4,kind:'unique',civ:'越南',page:'techs/Paper_Money'},
 {id:'berserkergang',name:'狂戰士幫',nameEn:'Berserkergang',at:'城堡',age:4,kind:'unique',civ:'維京',page:'techs/Berserkergang'},
 {id:'bagains',name:'協議',nameEn:'Bagains',at:'城堡',age:4,kind:'unique',civ:'保加利亞',page:'techs/Bagains'},
 {id:'cuman-mercenaries',name:'庫曼傭兵',nameEn:'Cuman Mercenaries',at:'城堡',age:4,kind:'unique',civ:'庫曼',page:'techs/Cuman_Mercenaries'},
 {id:'tower-shields',name:'塔盾',nameEn:'Tower Shields',at:'城堡',age:4,kind:'unique',civ:'立陶宛',page:'techs/Tower_Shields'},
 {id:'timurid-siegecraft',name:'帖木兒攻城術',nameEn:'Timurid Siegecraft',at:'城堡',age:4,kind:'unique',civ:'韃靼',page:'techs/Timurid_Siegecraft'},
 {id:'hulche-javelineers',name:'胡爾切擲矛兵',nameEn:"Hul'che Javelineers",at:'城堡',age:3,kind:'unique',civ:'馬雅',page:null},
 {id:'burgundian-vineyards',name:'勃根地葡萄園',nameEn:'Burgundian Vineyards',at:'城堡',age:3,kind:'unique',civ:'勃根地',page:null},
 {id:'first-crusade',name:'第一次十字軍東征',nameEn:'First Crusade',at:'城堡',age:3,kind:'unique',civ:'西西里',page:'techs/First_Crusade'},
 {id:'flemish-revolution',name:'佛萊明革命',nameEn:'Flemish Revolution',at:'城堡',age:4,kind:'unique',civ:'勃根地',page:null},
 {id:'scutage',name:'兵役免除稅',nameEn:'Scutage',at:'城堡',age:4,kind:'unique',civ:'西西里',page:null},
 {id:'dark-age',name:'黑暗時代',nameEn:'Dark Age',at:'城鎮中心',age:1,kind:'age',civ:null,page:'techs/age/Dark_Age'},
 {id:'feudal-age',name:'封建時代',nameEn:'Feudal Age',at:'城鎮中心',age:2,kind:'age',civ:null,page:'techs/age/Feudal_Age'},
 {id:'castle-age',name:'城堡時代',nameEn:'Castle Age',at:'城鎮中心',age:3,kind:'age',civ:null,page:'techs/age/Castle_Age'},
 {id:'imperial-age',name:'帝王時代',nameEn:'Imperial Age',at:'城鎮中心',age:4,kind:'age',civ:null,page:'techs/age/Imperial_Age'},
];
// One or two sentences per aoetw technology (paraphrased from its page; keyed like aoetwTechs), with this game's names
// for units, buildings and ages.
export const techText:Readonly<Record<string,string>>={
 'tracking':'升上第二時代後自動生效，讓步兵看得更遠；決定版起不必另外研究，屬於隨時代附帶的免費強化。',
 'supplies':'降低民兵系的食物花費，讓大量生產劍兵更省資源；以步兵為主力或打民兵快攻時值得優先研究。',
 'squires':'加快所有步兵的移動速度，讓行動緩慢的步兵更容易追上弓兵、趕赴戰場；步兵為主力時幾乎必點。',
 'arson':'強化步兵拆除一般建築的能力，適合用步兵深入敵方城鎮、清除民居與生產建築時研究。',
 'thumb-ring':'讓弓箭類單位射得更快，是弓兵主力的重要升級；原作還讓它們對靜止目標百發百中。',
 'parthian-tactics':'大幅強化馬弓騎兵的護甲，並讓它們更能剋制長槍兵；後期以馬弓騎兵為主力時是關鍵升級。',
 'bloodlines':'增加所有騎乘單位的生命值，讓斥候與騎士更耐打；以騎兵為核心的打法應盡早研究。',
 'husbandry':'加快騎乘單位的移動速度，對打帶跑的馬弓騎兵、或需要追擊對方機動部隊的騎兵尤其重要。',
 'loom':'提高村民的生命，讓他們不易被野獸或早期騷擾擊殺；高手多半在升第二時代前才研究，獵野豬有風險時可以提早。',
 'wheelbarrow':'讓村民每趟搬更多資源，全面提升採集效率；通常在前期採集科技點完、村民規模成形後研究。',
 'hand-cart':'手推車的進階版，再增加村民的搬運量；村民數量接近後期規模時研究最划算。',
 'town-watch':'擴大所有建築的視野，及早察覺來犯的敵軍；成本低廉，擔心被偷襲時可以研究。',
 'town-patrol':'城鎮瞭望的延伸，再次擴大建築視野，讓防守方更早掌握敵人動向。',
 'redemption':'讓僧侶能轉化大部分建築，以僧侶搭配軍隊時很有價值，最好先補上聖潔。',
 'atonement':'讓僧侶能轉化敵方僧侶，在雙方大量使用僧侶的對局中往往是勝負關鍵。',
 'herbal-medicine':'大幅加快進駐建築內單位的回血，讓受傷部隊躲進城堡或箭塔養傷後再出擊，適合以防守為主的局面。',
 'heresy':'讓被敵方轉化的單位直接陣亡，避免敵人藉此壯大；雖然昂貴，對手大量使用僧侶時幾乎必須研究。',
 'sanctity':'增加僧侶的生命值，讓他們多撐一發投石車攻擊、爭取完成轉化的時間；以僧侶作戰時相當關鍵。',
 'fervor':'加快僧侶的移動速度，方便他們追上目標、搶撿聖物與及時撤退。',
 'faith':'讓自己的單位更難被轉化；花費高昂，但面對以僧侶為主力的對手時值得研究。',
 'illumination':'縮短僧侶轉化後恢復信仰所需的時間，讓他們能更頻繁地出手；走僧侶戰術時，升上第四時代應優先研究。',
 'block-printing':'延長僧侶的轉化距離，讓他們能在攻城器逼近前就出手，是第四時代最重要的僧侶科技之一。',
 'theocracy':'一群僧侶合力轉化成功後，只有一位需要休息恢復，非常適合大批僧侶集體轉化的打法，而且價格便宜。',
 'cartography':'共享所有盟友的視野，而且完全免費，團隊戰中應盡早研究。',
 'caravan':'加快陸上與海上貿易單位的移動速度，等於提高貿易收入並降低被截殺的風險；後期仰賴貿易取得黃金時必點。',
 'coinage':'降低進貢資源給盟友時的手續費，團隊需要互相支援資源時很有用，也是銀行制度的前置科技。',
 'banking':'完全免除進貢手續費，讓盟友之間互送資源毫無損耗；有頻繁進貢需求時強烈建議研究。',
 'guilds':'降低在市集買賣資源的手續費；後期地圖資源枯竭、必須靠市集換取資源時特別有用。',
 'spies':'讓玩家持續看見所有敵人的視野；價格隨敵方村民等單位數量而定，最適合在敵人經濟已被摧毀、準備收尾時研究。',
 'treason':'僅在弒君模式出現，研究後能短暫看到敵方國王所在的位置，方便找出並狙殺國王。',
 'hoardings':'強化城堡的耐久度，搭配磚瓦技術與建築學讓城堡更難攻破；以城堡防守或在前線築城時值得研究。',
 'sappers':'讓村民拆除建築的能力大增，可以用來清掉蓋在自家資源旁的敵方箭塔或採集建築；屬於特定情況才需要的科技。',
 'conscription':'加快兵營、靶場、馬廄與城堡的生產速度，讓後期補兵與大量集結更有效率，幾乎是第四時代的必點科技。',
 'careening':'提升船隻的遠程護甲並增加運輸船載量，對海戰與跨海運兵都有幫助；也是船塢的前置科技。',
 'dry-dock':'加快所有船隻的航行速度並再擴充運輸船載量，讓艦隊調度與登陸作戰更迅速。',
 'shipwright':'降低船隻的木材造價並加快造船速度，大規模海戰時能更快補充艦隊。',
 'gillnets':'提升漁船捕魚與建造漁網的效率，在以海洋為主要食物來源的地圖上很划算。',
 'masonry':'提升建築的生命與護甲，讓城鎮更經得起攻擊；也是建築學的前置科技。',
 'ballistics':'讓弓兵、船隻與防禦建築能命中移動中的目標，使敵人無法再靠走位閃箭；遠程部隊的核心科技，一般比拇指環更優先。',
 'heated-shot':'強化箭塔與城堡對船隻的傷害，適合在海圖上需要守住海岸時研究。',
 'murder-holes':'消除箭塔與城堡貼身時的射擊死角；實戰中多半改用交叉火力或近戰單位掩護，很少有人研究。',
 'treadmill-crane':'加快村民建造建築的速度，大量興建城堡、箭塔或生產建築時特別有幫助。',
 'architecture':'磚瓦技術的進階版，再強化建築的生命與護甲，第四時代面對重型攻城器時能讓防線更穩固。',
 'chemistry':'提升弓兵與投射攻城器的攻擊，並解鎖火藥單位；想使用火槍兵與火砲必須先研究。',
 'siege-engineers':'延長攻城器的射程並提高對建築的傷害，第四時代以攻城部隊推進時非常重要。',
 'arrowslits':'提升箭塔的攻擊力，讓以箭塔防守或塔攻的打法更具威脅。',
 'padded-archer-armor':'增加弓兵與馬弓騎兵的護甲，讓遠程部隊更耐打；第二時代弓兵對射時的基本升級。',
 'leather-archer-armor':'第二級弓兵護甲，延續強化弓兵與馬弓騎兵的防禦。',
 'ring-archer-armor':'最高一級弓兵護甲，讓後期遠程部隊的耐打度大幅提升。',
 'fletching':'提高弓兵的攻擊與射程；走弓兵路線時，是第一個該研究的攻擊升級。',
 'bodkin-arrow':'第二級遠程攻擊升級，繼續提升弓兵的攻擊與射程。',
 'bracer':'最高一級遠程攻擊升級，讓後期弓兵的火力與射程更上一層樓。',
 'forging':'提升步兵與騎兵的近戰攻擊，是第二時代近戰部隊交戰時的基本升級。',
 'iron-casting':'第二級近戰攻擊升級，讓步兵與騎兵造成更多傷害。',
 'blast-furnace':'最高一級近戰攻擊升級，後期以步兵或騎兵為主力時不可或缺。',
 'scale-barding-armor':'增加騎兵護甲，讓斥候等騎兵在第二時代更耐打。',
 'chain-barding-armor':'第二級騎兵護甲，是第三時代騎士等重騎兵的重要防禦升級。',
 'plate-barding-armor':'最高一級騎兵護甲，讓後期騎兵面對近戰與弓箭都更堅固。',
 'scale-mail-armor':'增加步兵護甲，讓民兵與長槍兵在第二時代更耐打。',
 'chain-mail-armor':'第二級步兵護甲，持續強化步兵對近戰與弓箭的抵抗力。',
 'plate-mail-armor':'最高一級步兵護甲，後期步兵面對大量弓兵時尤其需要。',
 'gold-mining':'加快村民採金的速度，需要大量黃金訓練部隊或升級時代時研究。',
 'stone-mining':'加快村民採石的速度，打算塔攻、蓋城堡或大量建造城牆時值得研究。',
 'gold-shaft-mining':'第二級採金升級，進一步提升黃金產量，適合仰賴黃金單位的中後期。',
 'stone-shaft-mining':'第二級採石升級，需要持續興建城堡或防禦工事時才有必要。',
 'double-bit-axe':'加快村民伐木，是第二時代最重要的經濟科技之一，通常一升第二時代就研究；快速上城堡的打法可延到升第三時代之後。',
 'bow-saw':'第二級伐木升級，再次提高木材產量；條件允許時，升第三時代後應立即研究。',
 'two-man-saw':'最後一級伐木升級，效益不如前兩級，可以等後期經濟寬裕時再研究。',
 'horse-collar':'增加新農田的食物總量，減少重新播種的木材開銷；開始以農田為主要食物來源後就該研究。',
 'heavy-plow':'進一步增加農田產量，並讓農夫每趟多帶一些食物，提高食物經濟的效率。',
 'crop-rotation':'最高一級農田升級，讓農田更持久，後期靠大量農夫支撐軍隊時很划算。',
 'fortified-wall':'把石牆升級為更厚實的垛牆，城門也一併強化，讓城牆更難被攻破；以城牆防守時值得研究。',
 'guard-tower':'把箭塔升級為防禦箭塔，提升塔的耐久與火力，以箭塔防守或塔攻時研究。',
 'keep':'把防禦箭塔再升級為大型箭塔，成為第四時代更強悍的防禦塔。',
 'bombard-tower-tech':'解鎖火砲塔的建造，能有效打擊船隻與攻城器；必須先研究化學。',
 'atlatl':'提升散兵系與標槍騎兵的攻擊與射程，強化阿茲特克反弓兵部隊的壓制力。',
 'kasbah':'加快全隊城堡的生產與研究速度，方便柏柏與盟友大量產出特殊單位。',
 'yeomen':'讓徒步弓兵射得更遠並強化箭塔火力，進一步放大不列顛的長射程弓兵優勢。',
 'howdah':'提升矛象伕的護甲，讓緬甸的戰象部隊在前線更耐打。',
 'greek-fire':'延長火戰船的射程，讓拜占庭在海戰中更容易壓制敵方船隊。',
 'stronghold':'加快城堡與箭塔的射速，強化塞爾特的防守與塔攻能力。',
 'great-wall':'增加城牆與箭塔的耐久度；效果偏向被動防守，實戰中很少被優先研究。',
 'royal-heirs':'大幅縮短彎刀勇士的訓練時間，讓衣索比亞能迅速補充大量特殊單位。',
 'chivalry':'加快馬廄的工作速度，讓法蘭克能更快量產騎士，強化騎兵海戰術。',
 'anarchy':'讓哥德衛隊可以在兵營訓練，不必再依賴城堡，方便配合哥德的步兵海戰術大量生產。',
 'marauders':'讓答剌罕騎兵可以在馬廄訓練，能在短時間內大量生產，用來拆除敵方建築。',
 'andean-sling':'取消散兵與投石手的最小射程，讓印加的遠程步兵被貼身時仍能還擊。',
 'sultans':'提升採礦、貿易與聖物帶來的黃金收入，強化印度的黃金經濟。',
 'pavise':'提升徒步弓兵與傭兵的護甲，讓義大利的弓兵與熱那亞弩兵更耐打。',
 'yasama':'讓箭塔每次多射出幾支箭，強化日本的箭塔防守。',
 'tusk-swords':'提高矛象伕的攻擊力，強化高棉戰象的正面衝擊力。',
 'eupseong':'延長箭塔系的射程，讓朝鮮的箭塔防線涵蓋更大的範圍。',
 'corvinian-army':'讓馬扎爾驃騎兵不再需要黃金，即使到了黃金短缺的後期也能持續生產。',
 'thalassocracy':'把碼頭升級成能攻擊的海港，強化馬來在水圖的海上防守。',
 'tigui':'讓城鎮中心不必駐守村民就能自動放箭，提升馬利抵禦偷襲的能力。',
 'nomads':'民居被摧毀時人口上限不會跟著下降，降低蒙古遭騷擾時的損失，而且價格便宜。',
 'kamandaran':'讓弓兵系改用額外木材取代黃金，使波斯在黃金吃緊時仍能持續生產弓兵。',
 'carrack':'提升所有船隻的護甲，強化葡萄牙艦隊的耐久度。',
 'madrasah':'僧侶陣亡時會退回部分黃金，降低薩拉森以僧侶作戰的成本。',
 'orthodoxy':'大幅提升僧侶護甲，讓斯拉夫的僧侶更不容易被弓兵或騎兵擊殺。',
 'inquisition':'加快僧侶與傳教士的轉化速度，讓西班牙的轉化戰術更有效率。',
 'ironclad':'提高攻城器的近戰護甲，讓條頓的衝撞車與投石車更能抵擋近戰部隊的拆除。',
 'sipahi':'增加馬弓騎兵與標槍騎兵的生命值，強化土耳其的騎射部隊。',
 'chatras':'增加矛象伕的生命值，讓越南的戰象更耐打。',
 'chieftains':'讓步兵對騎兵與駱駝造成額外傷害，使維京步兵更能對抗敵方騎兵。',
 'stirrups':'加快斥候系、騎士系與保加利亞騎兵的攻擊速度，提升保加利亞騎兵的輸出。',
 'steppe-husbandry':'加快斥候系、草原騎兵與馬弓騎兵的訓練速度，方便庫曼迅速組成機動騎兵部隊。',
 'hill-forts':'延長城鎮中心的射程，強化立陶宛的家園防守。',
 'silk-armor':'提升輕騎兵與騎射單位的近戰與遠程護甲，讓韃靼騎兵更耐打。',
 'garland-wars':'提高步兵攻擊力，強化阿茲特克以步兵為主的後期部隊。',
 'maghrabi-camels':'讓駱駝部隊能自動回血，延長柏柏駱駝騎兵在戰場上的持續作戰能力。',
 'warwolf':'讓巨型投石機造成範圍傷害，可以用來轟擊密集的部隊；原作還讓它必定命中靜止目標。',
 'manipur-cavalry':'讓騎兵與飛鏢騎兵對建築造成更多傷害，方便緬甸以騎兵拆除敵方建築。',
 'logistica':'讓拜占庭聖騎兵帶有踐踏傷害並強化對步兵的攻擊，更能應付密集步兵。',
 'furor-celtica':'大幅提升攻城器的生命值，讓塞爾特的攻城部隊更難被摧毀。',
 'rocketry':'提升連弩兵與弩砲的攻擊，強化中國的遠程火力。',
 'torsion-engines':'擴大攻城器的範圍傷害，在狹窄地圖上對密集部隊特別有威脅。',
 'bearded-axe':'延長擲斧兵的射程，讓法蘭克這個特殊步兵能更安全地輸出。',
 'perfusion':'大幅加快兵營的生產與研究速度，讓哥德能迅速湧出大量步兵。',
 'atheism':'延長對手奇觀與聖物勝利的倒數時間，並讓間諜相關科技變便宜；屬於特定情境才用得上的科技。',
 'fabric-shields':'提升槍隊長、投石手與鷹勇士的護甲，強化印加的步兵核心部隊。',
 'shatagni':'延長火槍兵的射程，強化印度的火藥步兵。',
 'silk-road':'讓貿易車隊與貿易商旅的造價大減，方便義大利大規模經營貿易。',
 'kataparuto':'大幅加快巨型投石機的架設、拆收與射擊速度，提升日本的攻城效率。',
 'double-crossbow':'讓弩砲象與弩砲一次射出兩發，大幅提升高棉的範圍殺傷力。',
 'shinkichon':'延長投石車系的射程，讓朝鮮的攻城部隊能在更遠處開火。',
 'recurve-bow':'提升馬弓騎兵的攻擊與射程，強化馬扎爾的騎射打法。',
 'forced-levy':'讓兵營步兵改用食物取代黃金，使馬來在黃金耗盡的後期仍能大量生產步兵。',
 'farimba':'提升馬廄單位的攻擊力，讓馬利騎兵在後期更具殺傷力。',
 'el-dorado':'增加鷹勇士的生命值，讓馬雅的核心步兵更耐打。',
 'drill':'大幅加快攻城器的移動速度，讓蒙古的攻城部隊能快速轉移戰線。',
 'mahouts':'加快戰象的移動速度，彌補波斯戰象行動遲緩的弱點。',
 'arquebus':'提高火藥單位對移動目標的命中率，讓葡萄牙的火藥部隊更可靠。',
 'zealotry':'增加駱駝騎兵與阿拉伯奴隸兵的生命值，強化薩拉森的主力部隊。',
 'druzhina':'讓步兵攻擊時對周圍造成踐踏傷害，適合斯拉夫用來對付密集的敵方步兵。',
 'supremacy':'大幅強化村民的攻擊、護甲與生命值，讓西班牙村民在後期也能自保甚至參戰。',
 'crenellations':'延長城堡射程，並讓進駐其中的步兵也能放箭，打造條頓更強的城堡防線。',
 'artillery':'延長火砲的射程；原作還作用在火砲塔與火砲戰船上，強化土耳其的火藥攻城優勢。',
 'paper-money':'研究後立刻為自己與盟友帶來一筆黃金，是越南直接的經濟支援手段。',
 'berserkergang':'加快狂戰士的自我回血速度，讓維京的特殊步兵能持續作戰。',
 'bagains':'大幅提升民兵系的近戰護甲，讓保加利亞劍兵更能抵擋近戰部隊。',
 'cuman-mercenaries':'讓全隊可以在城堡免費訓練一批精銳欽察，為團隊迅速增加騎射戰力。',
 'tower-shields':'提升長槍兵系與散兵的遠程護甲，讓它們更能抵擋弓兵的射擊。',
 'timurid-siegecraft':'延長巨型投石機的射程並解鎖火焰駱駝，強化韃靼的攻城能力。',
 'hulche-javelineers':'讓散兵系每次攻擊多擲出一根長矛，大幅提升馬雅反弓兵部隊的火力。',
 'burgundian-vineyards':'把手上的食物轉換成黃金，並讓農夫種田時順帶產出少量黃金，為勃根地增加黃金來源。',
 'first-crusade':'讓城鎮中心一次性生出一批薩金特衛兵，可立即補強防守或發動攻勢，但整場只能使用一次。',
 'flemish-revolution':'把所有村民轉為佛萊明民兵，並開放在城鎮中心訓練；屬於放棄經濟、孤注一擲的終局手段。',
 'scutage':'依照自己與盟友擁有的軍事單位數量立即獲得黃金，軍隊越龐大收益越高。',
 'dark-age':'遊戲的起始時代，玩家只有少數村民、一座城鎮中心與一名偵察單位；此時以擴張經濟、累積村民為主，為升第二時代做準備。',
 'feudal-age':'在城鎮中心研究，需要先蓋好兩座指定建築；進入後解鎖靶場、馬廄、鐵匠鋪與市集，前期軍事衝突與快攻多從這裡展開。',
 'castle-age':'進入後可建造城堡、修道院、學院與攻城器，各文明的特殊單位與特色在此發揮，許多主力打法在這個時代成形。',
 'imperial-age':'最後一個時代，開放火藥單位、重型攻城器與世界奇觀，所有升級在此達到頂峰，大型決戰通常發生在這個階段。',
};
// ── Category 建築 ──────────────────────────────────────────────────────────────────────────────────────────────────
// aoetw.com's building catalogue (pages/building/*.vue of github.com/webrsb/aoetw, read 2026-10-01): its 32 pages with the
// site's names, group, age and owning civilization. kind: 'building' is one of this game's buildings (id = its kind),
// 'upgrade' a University technology that upgrades one (id = the technology, of = the building), 'other' a civilization
// building this game does not have. Text only; every number on the page comes from the simulation.
export const buildingsIntro='建築資料整理自 aoetw.com（世紀帝國 II 的繁體中文百科，內容以 HD／UserPatch 到早期決定版為準）。卡片上的造價、建造時間、生命、護甲、駐軍與箭矢都取自本作的模擬，是依本作比例自訂的 design_default，不是原作數據：建築生命大約是原作的六分之一，建造時間也配合本作的節奏縮短。';
export const buildingsNote='建築資料整理自 aoetw.com（HD／UserPatch 到早期決定版），說明已改用本作的單位、建築與時代名稱；數值一律取自本作的模擬，是 design_default，不是原作數據。標示「尚未實作」的建築目前不在遊戲裡。';
export const buildingsMissingText='aoetw 另收錄四座文明專屬建築：馬來的海港、保加利亞的營壘、葡萄牙的港灣大商站與西西里的城樓，這些文明都不在本作的原版十三文明之中。';
export type BuildingGroupDef={id:string;label:string;text:string};
// The site's four groups, in its order.
export const buildingGroups:readonly BuildingGroupDef[]=[
 {id:'economy',label:'經濟',text:'村民交付資源、增加人口與研究採集科技的據點，決定整個帝國的發展速度；貼近資源擺放，並隨採集點移動適時重建，村民就能少走冤枉路。'},
 {id:'military',label:'軍事',text:'訓練與升級各兵種的地方，步兵、遠程部隊、騎兵與攻城器各有專屬的產地。依對手的部隊組成決定先蓋哪一種，並放在方便集結出擊的位置。'},
 {id:'defense',label:'防禦',text:'城牆、城門、各式箭塔與城堡，能拖延敵軍、保護採集中的村民，有些還會射擊或生產部隊；布置在隘口或障礙物後方，並準備近戰部隊應付來拆的攻城器。'},
 {id:'other',label:'其他',text:'研究科技的鐵匠鋪與學院、宗教用途的修道院，以及另一條勝利途徑的世界奇觀；它們不採集也不作戰，卻提供左右戰局的升級。'},
];
// Why a reference building is not in this game.
export const buildingPendingReasons={civ:'本作只有 13 個原版文明'} as const;
export type AoetwBuilding={id:string;slug:string;name:string;nameEn:string;group:string;age:number;civ:string|null;kind:'building'|'upgrade'|'other';of:readonly string[]};
const bd=(id:string,slug:string,name:string,nameEn:string,group:string,age:number,kind:AoetwBuilding['kind']='building',of:readonly string[]=[],civ:string|null=null):AoetwBuilding=>({id,slug,name,nameEn,group,age,civ,kind,of});
export const aoetwBuildings:readonly AoetwBuilding[]=[
 bd('town-center','Town_Center','城鎮中心','Town Center','economy',1),bd('house','House','房屋','House','economy',1),bd('mill','Mill','磨坊','Mill','economy',1),
 bd('farm','Farm','農田','Farm','economy',1),bd('lumber-camp','Lumber_Camp','伐木場','Lumber Camp','economy',1),bd('mining-camp','Mining_Camp','採礦營地','Mining Camp','economy',1),
 bd('dock','Dock','碼頭','Dock','economy',1),bd('barracks','Barracks','軍營','Barracks','military',1),bd('palisade-wall','Palisade_Wall','木牆','Palisade Wall','defense',1),
 bd('palisade-gate','Palisade_Gate','木門','Palisade Gate','defense',1),bd('outpost','Outpost','哨站','Outpost','defense',1),bd('market','Market','市集','Market','economy',2),
 bd('blacksmith','Blacksmith','兵工廠','Blacksmith','other',2),bd('fish-trap','Fish_Trap','漁網','Fish Trap','economy',2),bd('archery-range','Archery_Range','射箭場','Archery Range','military',2),
 bd('stable','Stable','馬廄','Stable','military',2),bd('stone-wall','Stone_Wall','石牆','Stone Wall','defense',2),bd('gate','Gate','城門','Gate','defense',2),
 bd('watch-tower','Watch_Tower','瞭望箭塔','Watch Tower','defense',2),bd('monastery','Monastery','修道院','Monastery','other',3),bd('university','University','學院','University','other',3),
 bd('siege-workshop','Siege_Workshop','攻城器製造所','Siege Workshop','military',3),bd('castle','Castle','城堡','Castle','defense',3),
 bd('fortified-wall','Fortified_Wall','垛牆','Fortified Wall','defense',3,'upgrade',['stone-wall','gate']),bd('guard-tower','Guard_Tower','防禦箭塔','Guard Tower','defense',3,'upgrade',['watch-tower']),
 bd('harbor','Harbor','海港','Harbor','economy',3,'other',[],'馬來'),bd('krepost','Krepost','營壘','Krepost','defense',3,'other',[],'保加利亞'),
 bd('keep','Keep','大型箭塔','Keep','defense',4,'upgrade',['watch-tower']),bd('wonder','Wonder','世界奇觀','Wonder','other',4),bd('bombard-tower','Bombard_Tower','火砲塔','Bombard Tower','defense',4),
 bd('feitoria','Feitoriaicon_Feitoria','港灣大商站','Feitoria','economy',4,'other',[],'葡萄牙'),bd('donjon','Donjon','城樓','Donjon','defense',2,'other',[],'西西里'),
];
// One or two sentences per aoetw building page (paraphrased from it), with this game's names for units, buildings and ages.
export const buildingText:Readonly<Record<string,string>>={
 'town-center':'帝國的核心：訓練村民、收下所有資源，敵軍來襲時敲響鐘聲，讓村民躲進去一起射箭。開局各有一座，第三時代起可以在遠處的資源旁加蓋，縮短村民往返的路程。',
 house:'提供人口空間，是持續生產村民與軍隊的前提；被拆毀時人口上限也跟著下降。便宜又蓋得快，要提早補足，也常排成一列充當臨時的牆。',
 mill:'村民存放食物的地方，也研究增加農田產量的科技，耗盡的農田可以自動補種。蓋在果樹叢旁，之後的農田就圍著它擺放。',
 farm:'讓一名村民持續耕種的田，是中後期最穩定的食物來源，單位可以直接走過。貼著城鎮中心或磨坊擺放以縮短往返；農業科技研究完成後新蓋的田產量更高。',
 'lumber-camp':'村民交付木材的收集點，也研究提升伐木效率的科技。蓋在森林邊緣，砍伐線後退之後就換個更近的位置再蓋一座。',
 'mining-camp':'讓村民就近存放黃金與石頭，並提供開採相關的升級。蓋在金礦或石礦旁；開局資源吃緊時，通常先蓋磨坊與伐木場。',
 dock:'蓋在岸邊水面上，建造漁船、運輸船、貿易商船與各式戰船，也是漁船交付食物的地方，並研究海軍科技。在湖畔地圖上應及早建造以發展漁業，最好有箭塔或城堡掩護。',
 barracks:'訓練民兵系與長槍兵系等步兵的基本軍事建築，也是靶場與馬廄的前置條件，步兵相關的升級在這裡研究。',
 'palisade-wall':'便宜又快的木頭圍欄，拖出一整段時每一格就是一節牆。前期拿來封鎖缺口、拖延敵軍，或貼著己方箭塔圍一圈；後期防守要換成石牆。',
 'palisade-gate':'嵌在木牆裡的門：己方單位可以自由進出，敵軍則被擋在外面。可以直接蓋在己方的木牆上取代那一節，地基相當脆弱。',
 outpost:'沒有攻擊力的瞭望建築，便宜又蓋得快，用來提早發現來襲的敵軍或看住重要的資源點，只要花一點石頭。',
 market:'用黃金買賣食物、木材與石頭，雙方共用同一組行情，買得越多越貴、賣得越多越便宜；也生產貿易車隊，到對手的市集往返賺取黃金，距離越遠收入越多。',
 blacksmith:'不生產單位，卻提供步兵、騎兵與弓兵攻防的關鍵升級，也是攻城器工坊的前置建築。進攻前先補上護甲與攻擊，往往比多訓練幾個兵更有效。',
 'fish-trap':'蓋在水上的農田，只能由漁船建造與採集，食物交到碼頭。盡量緊鄰碼頭擺放；陸地空間不足或擅長漁業的文明特別好用。',
 'archery-range':'訓練弓兵、散兵與馬弓騎兵等遠程部隊，並研究強化遠程單位的科技；以弓兵為主力時，記得同步在鐵匠鋪補齊升級。',
 stable:'訓練與升級斥候系、騎士系與駱駝騎兵。騎兵移動快，適合襲擾對手的採集點，或衝去摧毀正在攻城的器械。',
 'stone-wall':'比木牆堅固得多的城牆，同樣拖出一整段。能延緩敵軍推進、讓牆後的遠程單位安全輸出；最好與森林或礦區相連封住通道，並配合城門進出。',
 gate:'嵌在石牆裡的門，己方單位能通過、敵人被擋在外面，可以直接蓋在己方石牆上取代那一節；研究垛牆後也一併強化。',
 'watch-tower':'基本的防禦塔，能在早期保護村莊，駐紮村民或弓兵還能多射幾支箭。除了守家也常用來塔攻：在對手的資源旁偷偷蓋塔壓制採集。',
 monastery:'訓練僧侶並研究宗教科技，存放聖物還會源源不絕地產生黃金。即使不打僧侶戰術也值得蓋一座，用來收集聖物並研究抵抗轉化的科技。',
 university:'研究強化建築、箭塔、城牆與攻城器的科技；化學也在這裡，它開放火藥單位與火砲塔。',
 'siege-workshop':'專門生產衝撞車、投石車、弩砲與火砲等攻城器，對建築有毀滅性的破壞力；需要先有鐵匠鋪。',
 castle:'中後期最強的據點：射出大量箭矢、可以駐軍，訓練各文明的特殊單位、巨型投石機與炸藥桶，並研究特殊科技。投石車與衝撞車是它的天敵，要派部隊在旁護衛。',
 wonder:'各文明的代表性建築，蓋好後開始倒數，守住它直到倒數結束就獲勝，被摧毀則倒數中止。動工前先備妥軍隊與防線，最好以多層城牆包圍。',
 'bombard-tower':'在學院研究火砲塔後才能建造的火藥防禦塔，砲彈威力極強但射速很慢，往往一發就能擊倒步兵與弓兵，對船隻也有加成。宜架在隘口或其他防禦建築的交叉火力內，並防範從射程外轟擊的攻城器。',
 'guard-tower':'在學院研究後，所有箭塔升級為更耐打、攻擊更強的防禦箭塔，對付步兵與弓兵很有效，但仍怕騎兵與攻城器。',
 keep:'第四時代在學院研究的頂級箭塔，生命與攻擊再提升；依然要搭配近戰部隊防範攻城器。',
 'fortified-wall':'在學院研究後，石牆升級為更厚實的垛牆，城門也一併強化，很適合守護世界奇觀或存放聖物的修道院。',
 harbor:'馬來研究特殊科技後取代碼頭的建築，兼具收集資源、造船與放箭攻擊的能力。',
 krepost:'保加利亞的縮小版城堡，能訓練保加利亞騎兵並提供人口，蓋得比城堡快、成本也低，但不能生產巨型投石機。',
 feitoria:'葡萄牙在最後一個時代的特殊建築，不需要村民就能持續產出多種資源，代價是佔用大量人口。',
 donjon:'西西里用來取代箭塔系的縮小版城堡，能訓練薩金特衛兵，並隨時代升級變得更堅固。',
};
// Parts of a reference building this game leaves out although the building is here.
export const buildingPartials:Readonly<Record<string,string>>={
 gate:'原作的城門可以上鎖，連己方也不能通過；本作的城門一律只擋敵軍',
 'palisade-gate':'原作的木門可以上鎖，連己方也不能通過；本作的木門一律只擋敵軍',
 'fish-trap':'原作的敵方漁船也能採集別人的魚網；本作只有擁有者能採集',
};
// ── Category 遊戲元素 (the 遊戲元素 round) ─────────────────────────────────────────────────────────────────────────
// aoetw.com's 遊戲元素 menu in its order, then the two element pages the menu leaves out (Conversion, Line of Sight).
// Prose only (no digits): every number on these pages is read from the simulation by apps/web/codex-elements.ts.
export type ElementProse={id:string;name:string;nameEn:string;refName:string|null;slug:string;menu:boolean;summary:string;text:string};
export const elementsIntro='遊戲元素整理自 aoetw.com 的「遊戲元素」選單：防禦類型、回血、駐軍、血量、攻擊、射速、開火間隔、擴散範圍、團隊加分、遺跡與嘲諷語音，另加選單沒有列出的招降與視野兩頁。每一頁先說明本作怎麼做，再列出取自模擬的表格；數字依本作比例自訂，是 design_default，不是原作數據。';
export const elementsNote='遊戲元素整理自 aoetw.com（HD／UserPatch 到早期決定版）；表格裡的每個數字都即時取自本作的模擬，以未加文明加成、依該兵種升級步驟的數值為準。距離以格計（一格是地圖上的一個方格），時間以本作的秒計。';
export const elementProse:readonly ElementProse[]=[
 {id:'armor',name:'防禦類型',nameEn:'Armor classes',refName:null,slug:'armor',menu:true,summary:'每個單位與建築屬於哪些類型，誰對它有加成。',
  text:'傷害先算攻擊減去對應的近戰或遠程護甲，不足時算作零；再把攻擊者對目標每個類型的加成各自扣掉目標在該類型的護甲後加上去，最後至少一點。多數單位的類型護甲是零，只表示它屬於這個類型；拜占庭聖騎兵、阿拉伯奴隸兵等少數單位有正的騎兵護甲，長槍兵系的加成打在牠們身上就打了折扣。建築也分成標準建築、石造防禦、城牆與城門、城堡等類型，攻城器與村民對不同類型的加成不一樣。'},
 {id:'regeneration',name:'回血',nameEn:'Regeneration',refName:null,slug:'elements/Regeneration',menu:true,summary:'不靠僧侶自己恢復生命的方式。',
  text:'本作只有維京的狂戰士天生會回血，研究狂戰士幫後更快。其他受傷的單位要靠僧侶治療，或躲進城鎮中心、箭塔、城堡與生產建築慢慢回復；城堡回得比城鎮中心和箭塔快一倍，修道院的草藥治療讓所有駐軍回得更快。攻城器與船隻不會回血，也不能被僧侶治療，只能由村民修理。'},
 {id:'garrison',name:'駐軍',nameEn:'Garrison',refName:null,slug:'elements/Garrison',menu:true,summary:'哪些建築與單位可以讓單位躲進去。',
  text:'城鎮中心、箭塔、火砲塔與城堡可以讓村民和徒步單位躲進去，村民與徒步弓兵還會增加射出的箭；鐘聲會把村民叫進最近的建築。兵營、靶場、馬廄、攻城器工坊、修道院與碼頭只收自己訓練的單位：把集結點設在建築本身，新兵就直接進駐，出來後不能再命令回去。運輸船載運陸上單位，衝撞車可以載步兵與徒步弓兵，步兵越多衝撞車越快、打建築越痛。建築受損到只剩少許生命時，裡面的單位全部被趕出來，也不能再進去。'},
 {id:'hit-points',name:'血量',nameEn:'Hit points',refName:null,slug:'elements/Hit_points',menu:true,summary:'生命值，以及受傷後怎麼補回來。',
  text:'生命歸零的單位陣亡、建築倒塌。單位的生命大致照原作，建築的生命大約是原作的六分之一，配合本作較短的對局。補回生命有三種方式：僧侶治療單位、駐軍時慢慢回復，以及村民修理建築、攻城器與船隻。修理要花錢，修滿一次大約是原價的一半，邊修邊扣；城鎮中心修理不花石頭但木材加倍。'},
 {id:'attack',name:'攻擊',nameEn:'Attack',refName:null,slug:'elements/Attack',menu:true,summary:'近戰與遠程兩種攻擊，以及攻擊加成。',
  text:'攻擊分近戰與遠程：近戰扣目標的近戰護甲，遠程扣遠程護甲。兵營、馬廄與多數攻城器打近戰，射箭場的單位、弩砲、戰船與所有會射箭的建築打遠程。加成照防禦類型計算，一個目標同時屬於幾個類型時，各類型的加成會一起算進去。本作沒有命中率：每一發都會打中。'},
 {id:'rate-of-fire',name:'射速',nameEn:'Rate of fire',refName:null,slug:'elements/Rate_of_Fire',menu:true,summary:'兩次攻擊之間的間隔。',
  text:'射速是兩次攻擊之間要等多久，數字越小打得越快。近戰的間隔照原作的秒數乘以一個比例，遠程照另一個比例換算成本作的節拍，所以兩者的相對快慢與原作一致。火戰船近距離連續噴火，是全遊戲最快的；攻城器與火藥單位最慢。拇指環、日本步兵與蒙古馬弓騎兵等科技與文明加成會讓間隔變短。'},
 {id:'frame-delay',name:'開火間隔',nameEn:'Frame delay',refName:null,slug:'elements/Frame_delay',menu:true,summary:'遠程單位對新目標的第一發要先瞄準多久。',
  text:'開火間隔只影響對新目標的第一發：遠程單位開始攻擊一個剛選上的目標時要先站定瞄準，之後的每一發就照射速。瞄準時只要一走動就得重來，所以邊打邊退的拉打戰術有代價，近戰單位追得上遠程單位。近戰單位與船隻沒有開火間隔。'},
 {id:'area-of-effect',name:'擴散範圍',nameEn:'Area of effect',refName:null,slug:'elements/Area_of_Effect',menu:true,summary:'一次傷害到好幾個目標的攻擊。',
  text:'投石車系與火砲的砲彈落地時，範圍內的單位都會受傷，連自己人也不例外（射擊者本身除外）；爆破船系、戰狼號等其他範圍攻擊只傷敵人。戰象踐踏目標旁的敵兵，拜占庭聖騎兵研究後勤後也會踐踏；弩砲的弩箭會貫穿，打到後方路線上的敵兵；裝甲衝撞車與重型衝撞車撞擊建築時，附近的敵方建築也一起受損。'},
 {id:'team-bonus',name:'團隊加分',nameEn:'Team bonus',refName:'團隊加分',slug:'elements/Team_Bonus',menu:true,summary:'原作與盟友共享的文明加成。',
  text:'原作的團隊加分會分享給同盟的所有玩家。本作是一對一，沒有盟友，所以團隊加分只對自己生效；每個文明的團隊加分照常列在文明頁，效果與一般加成一起計算。'},
 {id:'relic',name:'聖物',nameEn:'Relic',refName:'遺跡',slug:'elements/Relic',menu:true,summary:'僧侶搬進修道院後持續產生黃金。',
  text:'對戰圖上散落著聖物，只有僧侶能搬，搬著聖物的僧侶不能轉化。聖物放進修道院後會持續產生黃金，修道院被摧毀或轉化時聖物掉在原地。收集到地圖上所有的聖物後開始倒數，撐到倒數結束就獲勝。'},
 {id:'taunts',name:'嘲諷語音',nameEn:'Taunts',refName:null,slug:'elements/Taunts',menu:true,summary:'用編號送出的語音訊息。',
  text:'在戰場上按輸入鍵打開聊天列，輸入編號後再按一次就送出；編號要放在最前面，後面的文字會略過。雙方都看得到訊息，電腦也會在發現敵人、出兵或城鎮中心告急時嘲諷。本作沒有錄音，只在電腦上有中文語音時朗讀，括號內的聲音不朗讀；選單裡可以關掉朗讀。'},
 {id:'conversion',name:'招降',nameEn:'Conversion',refName:'招降',slug:'elements/Conversion',menu:false,summary:'僧侶把敵方單位變成自己的。',
  text:'僧侶走到射程內後開始招降，每一次嘗試約一秒：前幾次一定失敗，之後每次都有固定機會成功，到上限時保證成功。成功後僧侶的信仰歸零，要等一段時間才能再招降。研究救贖才能招降建築，研究贖罪才能招降僧侶；城鎮中心、城堡、修道院、農田、城牆與奇觀永遠不能招降。忠誠信仰與條頓的團隊加分讓單位更難被招降。'},
 {id:'line-of-sight',name:'視野',nameEn:'Line of sight',refName:null,slug:'elements/Line_of_Sight',menu:false,summary:'單位與建築能看多遠，以及戰爭迷霧。',
  text:'每個單位與建築都會揭開周圍的戰爭迷霧；看過的地方會記住當時看到的建築，但看不到之後的變化。被看不到的敵人打到時，會短暫看見攻擊者所在的位置。城鎮瞭望與城鎮巡邏讓建築看得更遠，一些文明的加成也會增加特定單位或建築的視野。'},
];
// What the reference has for each element that this game lacks, and why.
export const elementLacks:Readonly<Record<string,readonly {name:string;reason:string}[]>>={
 armor:[{name:'鷹勇士、傭兵、龜甲船等防禦類型',reason:'本作只有原版十三個文明，這些類型的單位不在遊戲裡'}],
 regeneration:[{name:'英雄回血',reason:'本作沒有戰役與英雄'},{name:'柏柏的駱駝回血（馬格拉比駱駝）',reason:'柏柏不在本作的文明裡'}],
 garrison:[{name:'攻城塔',reason:'本作照原版的單位表，攻城塔是後來的資料片才加入'},{name:'高棉的民居進駐',reason:'高棉不在本作的文明裡'},{name:'村民進駐衝撞車',reason:'本作照原版規則，只有步兵與徒步弓兵能上衝撞車'}],
 'hit-points':[{name:'攻城器修理改花黃金',reason:'本作的單位修理一律照原價各資源的一半計算'}],
 attack:[{name:'命中率與彈道學',reason:'本作每一發都會打中，沒有失準的彈道'}],
 'rate-of-fire':[{name:'風琴砲、熱那亞弩手等單位',reason:'本作只有原版十三個文明'}],
 'frame-delay':[],
 'area-of-effect':[{name:'斯拉夫步兵的踐踏、矛象伕、衣索比亞的扭力彈射器',reason:'這些文明不在本作'},{name:'投石車打倒樹木',reason:'本作的範圍傷害只打單位與建築'}],
 'team-bonus':[{name:'與盟友共享加成',reason:'本作是一對一，沒有盟友'},{name:'其他文明的團隊加分',reason:'本作只有原版十三個文明'}],
 relic:[{name:'與盟友一起達成聖物勝利',reason:'本作是一對一'},{name:'緬甸的聖物位置、阿茲特克的聖物加成',reason:'這些文明不在本作'}],
 taunts:[{name:'錄製的語音',reason:'本作不載入外部檔案，只用電腦本機的中文語音朗讀'}],
 conversion:[{name:'西班牙的異端審判與傳教士',reason:'西班牙不在本作的文明裡'},{name:'斥候系與鷹勇士的招降抗性等級',reason:'本作的招降只用次數，不分抗性等級'}],
 'line-of-sight':[{name:'製圖學（分享盟友視野）',reason:'本作是一對一，沒有盟友'},{name:'追蹤（步兵視野）',reason:'網站所在年代已併入第二時代'}],
};
// ── Category 戰術技巧 (the 戰術技巧 round) ──────────────────────────────────────────────────────────────────────────
// aoetw.com/ar (fetched 2026-10-02 from github.com/webrsb/aoetw): the openings and the micro techniques. Prose has no
// digits; the build-order steps, the computer's plan and every number come from packages/content/openings.ts and the
// simulation (apps/web/codex-tactics.ts).
export type TacticProse={id:string;name:string;nameEn:string;slug:string;group:'opening'|'micro';summary:string;text:string;
 // how: how this game does it (micro techniques only).
 how:string|null};
export const tacticsIntro='戰術技巧整理自 aoetw.com 的「戰術技巧」頁：基礎升級、阿拉伯地圖的主流打法與控兵技巧。每種打法列出網站的資訊框、照本作比例換算的流程、反制方法，以及電腦在本作怎麼打；控兵技巧說明網站的意思，再說明在本作怎麼做。網站的流程以兩百人口、升第二時代五百食物計算，本作的人口上限與升級費用不同，村民數約為網站的一半，是 design_default，不是原作數據。';
export const tacticsNote='戰術技巧整理自 aoetw.com（阿拉伯一對一，網站標示為未完成的頁面）；流程與電腦的打法取自本作的開局資料，命中率、彈道速度與姿態的數字即時取自模擬。距離以格計（一格是地圖上的一個方格），時間以本作的秒計。';
export const basicUpgradesText='網站目錄的「基礎升級」列了標準升封建、標準升城堡、封快升級教學與城快升級教學，但都沒有獨立的頁面：前兩項只是目錄上的文字，後兩項是兩段影片的標題。本作不收錄影片；各打法頁的流程就是照網站開局換算的升級步驟，練習升級可以從那裡開始。';
export const basicUpgradeItems=['標準升封建','標準升城堡','封快升級教學','城快升級教學'] as const;
export const tacticProse:readonly TacticProse[]=[
 // 主流打法, in the order of the site's list.
 {id:'armstower',name:'裝甲塔',nameEn:'Men-at-arms into towers',slug:'ar/armstower',group:'opening',how:null,summary:'重步兵掩護村民到對方資源點蓋箭塔，高風險高報酬。',
  text:'上第二時代後用重步兵掩護前置的村民，在對方的果樹、黃金或石頭旁蓋箭塔封鎖資源，再一座接一座地插下去，讓對方的經濟癱瘓。對方資源靠外、對方失誤，或對方想直接上城堡時最適合出手；對方的資源都在家裡時就不該打。箭塔缺乏保護時容易被村民拆掉，網站建議養成在塔下蓋牆的習慣。'},
 {id:'scrush',name:'肉馬開局',nameEn:'Scout rush',slug:'ar/scrush',group:'opening',how:null,summary:'第二時代出斥候騷擾，機動高、好上手、打法靈活。',
  text:'斥候是第二時代機動最強的兵種，殺村民快，也剋散兵與少量弓兵。上第二時代後蓋馬廄，出幾隻斥候騷擾對方的資源點，遇到前置塔攻可以配合村民強拆，對方龜家搶城堡也能前置斥候加塔。對方把家圍死、出很多長槍兵，或是打裝甲塔時，就要果斷轉散兵或弓兵。'},
 {id:'archerstar',name:'小弓開局',nameEn:'Archer opening',slug:'ar/archerstar',group:'opening',how:null,summary:'兩座靶場出弓手，不花食物，可以一路接上城堡時代。',
  text:'弓手不花食物，可以一邊進攻一邊存錢上城堡；成形慢但後勁大，上城堡後升級弩手繼續打，也比斥候不怕木牆。一開始一兩隻弓手幾乎沒有攻擊力，容易被斥候搶攻，所以通常先出一隻長槍兵。對手出散兵時，要適時調整經濟，混進長槍兵或散兵。'},
 {id:'armstar',name:'裝甲開局',nameEn:'Men-at-arms opening',slug:'ar/armstar',group:'opening',how:null,summary:'升第二時代時出民兵騷擾，上去後升級重步兵。',
  text:'點下第二時代就出三隻民兵去騷擾對方的經濟，可以擋下對方的前置與黑快，運氣好還能抓到正在蓋建築的村民，就算沒殺到人，也會讓對方的經濟大亂。上第二時代後民兵沒折損太多就研究重步兵，家裡改蓋靶場或馬廄，配弓兵或斥候繼續攻擊。重步兵怕弓兵，第二時代中後期因為走得慢逐漸沒用。'},
 {id:'brushtof',name:'黑快轉封',nameEn:'Drush into Feudal',slug:'ar/brushtof',group:'opening',how:null,summary:'黑暗時代派民兵騷擾，再以較好的經濟上第二時代。',
  text:'黑暗時代派三隻民兵騷擾，經濟配置到較多人口才升第二時代，既提早攻擊、讓對方手忙腳亂，又能正常上封建決戰，也能防止對方大圍家。上第二時代後民兵還多就轉重步兵，再看對方配兵轉長槍兵或弓兵；經濟較好，可以很快蓋兩座靶場加鐵匠鋪升級羽箭。控好黑暗時代的民兵，這個打法才成立。'},
 {id:'brushfc',name:'黑快搶城',nameEn:'Drush fast castle',slug:'ar/brushfc',group:'opening',how:null,summary:'民兵在前面爭取時間，家裡快速升到城堡時代。',
  text:'黑暗時代出三隻以上的民兵干擾對手，盡量拖延時間，自己趁機圍家、存錢，安全且快速地升上城堡時代，再用優勢的時代兵種取勝。地形要非常好才打，黃金和樹木不好守的空曠地圖不適合。發現對方很晚才上封建，通常就是在搶城，前置箭塔、家裡挖石頭是常見的反制；搶城很怕裝甲塔。'},
 {id:'towerrush',name:'純塔',nameEn:'Tower rush',slug:'ar/towerrush',group:'opening',how:null,summary:'只派村民前置蓋箭塔，不出其他兵種。',
  text:'不蓋兵營、不出兵，把省下的資源換成更多村民與箭塔：點封後派村民到對方家，在石頭或其他資源區同時起兩座塔互相掩護，再一座接一座地插下去。對方來拆塔時要立刻在塔下蓋木牆，很吃手速。對手資源都在外面時效果最好，地形好時就塔不到東西；反制是早點找到前置的村民，或者挖石頭、研究城鎮瞭望，以塔守塔。'},
 {id:'eglerush',name:'老鷹開局',nameEn:'Eagle scout opening',slug:'ar/eglerush',group:'opening',how:null,summary:'第二時代出鷹斥候，是中美洲文明的專屬打法。',
  text:'上第二時代後蓋兩座兵營出鷹斥候，適時搭配長槍兵或散兵騷擾對手；鷹斥候吃的食物少，可以很快上城堡升級鷹勇士。弓手成形後與把家圍死都能剋制它。這是中美洲三國的專屬打法，本作的原版文明都沒有鷹斥候，所以不能玩。'},
 {id:'fontrush',name:'前置槍矛',nameEn:'Forward spears and skirmishers',slug:'ar/fontrush',group:'opening',how:null,summary:'在對方附近前置兵營，用長槍兵與散兵壓迫。',
  text:'點封後派村民到對方附近前置兵營，上第二時代先出長槍兵，再蓋兩座靶場出散兵，村民持續在對方資源區插塔，用槍矛掩護推進，還算能剋制傳統的斥候與弓手開局。壓迫感很強，但風險高、報酬不如裝甲塔；黑暗民兵轉重步兵抓到前置的村民就能化解。網站的「矛兵」是本作的散兵，「槍兵」是長槍兵。'},
 {id:'bbrush',name:'黑暗爆民兵',nameEn:'Dark Age militia rush',slug:'ar/bbrush',group:'opening',how:null,summary:'停在黑暗時代不斷出民兵，用人海騷擾對手。',
  text:'提早蓋兵營，村民和民兵不斷生產，用人海戰術騷擾對手、牽制對方的封建進攻，自己一邊種田、圍牆，能上封建就上，短暫停留後跳城堡。自己升級大失誤時，例如打獵死了村民、被偷了野豬，乾脆留在黑暗時代打一波。缺點是很好防守，木牆就擋得住，對方上封建後出弓兵即可化解。'},
 // 控兵技巧, in the site's order.
 {id:'pull',name:'拉兵',nameEn:'Pulling back',slug:'ar',group:'micro',summary:'把被圍毆的兵拉走，讓敵人追著牠跑。',
  text:'對方圍攻你的兵時，把血少、被鎖定的那隻拉走，讓敵人追著牠跑卻打不到，其他兵趁機上前包圍；騎士五對五時，一隻被三隻追著往後拉，就變成四打二。遠程部隊互射時也能把被射的兵拉開，或讓牠在敵人面前左右移動，讓對方的箭落空；對方研究彈道學後效果就小了。',
  how:'選取被追的單位，右鍵把牠拉到後方，其他單位再右鍵攻擊追兵。本作的箭會飛一段時間，沒有彈道學時瞄準的是發射當下的位置，所以移動中的單位常常躲得掉；不還擊姿態讓單位不會停下來回擊，左右移動時也不會被拖住。'},
 {id:'surround',name:'包圍',nameEn:'Surrounding',slug:'ar',group:'micro',summary:'騎兵散開、繞到弓兵前方，擋住對方走位。',
  text:'遠程部隊會一邊走位一邊點射追來的近戰單位，只在後面追趕只會一隻隻被點掉。騎兵遇到整群弓兵時要分散隊形，預判對方的去向，衝到他們前面擋住走位、打亂隊形；衝進去前先用不還擊姿態加巡邏，就定位後再改回自動攻擊。',
  how:'選取騎兵切成不還擊姿態，用分散移動或巡邏繞到弓兵的前方；到位後切回攻擊姿態，騎兵就會自動找附近的敵人打。單位彼此不能穿過，擋在弓兵前面的騎兵會真的堵住他們的路。'},
 {id:'focus',name:'點射',nameEn:'Focus fire',slug:'ar',group:'micro',summary:'所有遠程兵集中火力，先打死一個目標。',
  text:'控弩手、馬弓騎兵等遠程兵的基本功：讓所有遠程兵一起攻擊同一個目標，打死再換下一個，把火力用到最大，最有效率地殺傷敵人。分散攻擊時每個目標都只受一點傷，敵人一隻也沒少，反擊的火力也就沒有減弱。',
  how:'框選所有遠程兵，右鍵同一個敵人；目標倒下後，攻擊姿態的單位會自動找最近的敵人。換新目標時遠程兵要重新瞄準，頻繁換目標會損失輸出；命中率不到百分之百的單位，集火時也會有幾發落空。'},
 {id:'clump',name:'合兵',nameEn:'Clumping',slug:'ar',group:'micro',summary:'讓遠程兵擠在一起，縮小受攻擊的面。',
  text:'讓遠程兵合在一起，受攻擊的表面最小、存活率較高。可以利用樹木之間、水岸邊或兩棟建築之間的屏障；空地上則用堅守位置加巡邏再停止，讓兵疊在一起。遇到敵方的投石車時，合兵會很吃虧。',
  how:'本作的單位一格只站一個，彼此不能重疊，做不到網站說的把兵疊在一起；能做的是把遠程兵帶到樹林或建築之間的窄處，用堅守姿態站好，只讓前排面對敵人。擠成一團時，投石車與火砲的爆炸會一次打中很多隻，自己的砲也會誤傷。'},
 {id:'spread',name:'分散',nameEn:'Spreading out',slug:'ar',group:'micro',summary:'散開閃躲攻擊，閃過再收合。',
  text:'閃躲對方攻擊時，用分散與集中的快捷鍵讓兵往兩側散開再收回；初期一群斥候躲避敵人的箭時很好用，遠程部隊閃躲投石車時更是必備。',
  how:'移動時選擇分散移動，單位之間會多空一格站開；投石車的石頭要飛一段時間，落在發射時瞄準的位置，看到它發射就散開，石頭就會落空或只打到少數。要收合時用一般移動即可。'},
 {id:'dodge',name:'閃躲',nameEn:'Dodging',slug:'ar',group:'micro',summary:'對方沒有彈道學時，橫向移動就能躲開箭。',
  text:'在對方研究彈道學之前，箭矢很容易閃躲：讓單位對著射擊者橫向移動，就能把傷害降到最低。初期斥候探圖經過敵人的城鎮中心被放箭時一定要用。',
  how:'本作的箭與砲彈都會飛。沒有彈道學時，箭瞄準發射當下目標所在的位置，飛到時目標已經走開就落空；研究彈道學後，弓兵、戰船與防禦建築會預判移動的方向。下表列出每種遠程單位的命中率、彈道速度與彈道學是否有效；沒命中的箭落在目標附近，可能打到旁邊的敵人。'},
 {id:'split',name:'分兵',nameEn:'Splitting',slug:'ar',group:'micro',summary:'被追時把被鎖定的兵拉開，其他兵回頭打。',
  text:'和分散、拉兵的道理相同：敵人追著我方單位跑時，把被鎖定的那隻拉開，其他單位向前攻擊，讓追兵一路被打死。初期斥候殺村民被長槍兵追趕時經常使用。',
  how:'把被追的斥候往遠處拉，其他斥候右鍵攻擊追兵；追兵會一直追原本的目標。防禦姿態的單位追不遠就回頭，攻擊姿態的會一路追下去，所以引誘對方之前先看清楚對方是哪一種。'},
 {id:'block',name:'卡位',nameEn:'Body blocking',slug:'ar',group:'micro',summary:'用單位的身體擋住敵人的去路。',
  text:'與包圍有點相關，但用途很多：斥候發現對方村民在打獵時，擋住村民的去路，讓野豬咬他；民兵追不上逃回城鎮的村民時，用斥候卡在前面，讓民兵追上去打倒村民。',
  how:'本作的單位彼此不能穿過，每個單位佔一格，擋在路上的單位真的會讓對方繞路或停下。把斥候移到對方逃跑方向的前方即可；窄路、樹林邊與建築之間最好卡。'},
];
// What the site's pages describe that this game cannot do, per page (no digits).
export const tacticLacks:Readonly<Record<string,readonly {name:string;reason:string}[]>>={
 armstower:[{name:'趕鹿',reason:'本作的鹿只會從打牠的獵人身邊逃開，趕不動'},{name:'網站點名的緬甸、阿茲特克、印加、馬扎爾',reason:'這些文明不在本作的原版文明裡'},{name:'電腦在塔下蓋牆',reason:'電腦不蓋牆，網站的建議只留在流程裡'}],
 scrush:[{name:'網站點名的匈人、馬扎爾、印度',reason:'這些文明不在本作的原版文明裡'}],
 archerstar:[{name:'網站點名的越南、衣索比亞、馬雅',reason:'這些文明不在本作的原版文明裡'}],
 armstar:[{name:'網站資訊框的匈人、馬扎爾',reason:'這些文明不在本作；而且這一欄是從肉馬開局複製來的'}],
 brushtof:[{name:'趕鹿',reason:'本作的鹿只會從打牠的獵人身邊逃開，趕不動'},{name:'網站資訊框的匈人',reason:'匈人不在本作的原版文明裡'}],
 brushfc:[{name:'趕鹿',reason:'本作的鹿只會從打牠的獵人身邊逃開，趕不動'},{name:'網站點名的匈人、馬雅、印加、阿茲特克',reason:'這些文明不在本作的原版文明裡'},{name:'電腦圍家',reason:'電腦不蓋牆，網站的建議只留在流程裡'}],
 towerrush:[{name:'趕鹿',reason:'本作的鹿只會從打牠的獵人身邊逃開，趕不動'},{name:'網站點名的朝鮮、西班牙、印加、馬來',reason:'這些文明不在本作的原版文明裡'}],
 eglerush:[{name:'鷹斥候與鷹勇士',reason:'中美洲三國的單位，本作的原版文明都沒有'}],
 fontrush:[{name:'趕鹿',reason:'本作的鹿只會從打牠的獵人身邊逃開，趕不動'},{name:'網站點名的匈人、緬甸、馬扎爾',reason:'這些文明不在本作的原版文明裡'}],
 bbrush:[{name:'網站提到的緬甸與西班牙城堡兵',reason:'這些文明不在本作的原版文明裡'},{name:'電腦圍牆',reason:'電腦不蓋牆，網站的建議只留在流程裡'}],
 pull:[],surround:[],focus:[],
 clump:[{name:'把兵疊在一起',reason:'本作一格只站一個單位，單位不能重疊'}],
 spread:[{name:'分散與集中的快捷鍵',reason:'本作用分散移動代替，收合用一般移動'}],
 dodge:[],split:[],block:[],
};
// 老鷹開局's infobox as the site gives it (aoetw.com/ar/eglerush); the opening cannot be played here.
export const eagleOpeningInfobox={age:2,power:'強',difficulty:'普',pros:'弱點少，但成形慢，可銜接城堡',cons:'成形慢，弓手一多就不怕老鷹，怕圍死',civs:'南美國（阿茲特克、馬雅、印加）'} as const;
// ── 科技樹 (the 科技樹 round) ───────────────────────────────────────────────────────────────────────────────────────
export const treeIntro='科技樹照 aoetw.com 各文明的科技樹頁排列：每座建築一塊，由上往下是黑暗、封建、城堡、帝王時代，同一欄由上往下是升級的先後。這個文明沒有的項目變暗並標「沒有」，本作沒有的參考項目（例如鷹斥候、攻城塔）可以顯示成淡色。對局中打開時，會標出你已研究、已擁有、正在進行，以及現在就能做的項目。';
export const treeNote='科技樹的排列取自 aoetw.com 的文明科技樹頁；每個項目能不能用、費用與前置都即時取自本作的規則，點項目會打開它在百科的那一頁。';
// Reference items the game lacks, placed in the site's tree by age (aoetw.com tree pages): the ages of each line's
// steps, and the technology a reference technology follows in its column.
export const treeRefAges:Readonly<Record<string,readonly number[]>>={'eagle-scout':[2,3,4],'battle-elephant':[3,4],'steppe-lancer':[3,4],'xolotl-warrior':[3],'siege-tower':[3]};
export const treeRefChains:Readonly<Record<string,string>>={banking:'coinage'};
// ── 地圖 (the 地圖 round) ─────────────────────────────────────────────────────────────────────────────────────────────
// aoetw.com's random-map list (maps/index.vue) with the site's descriptions (packages/content/maps.ts), the strategy each
// page suggests for the maps this game plays (condensed, no numbers: the summaries on the page carry the site's own),
// and why the rest are listed only.
export const mapsIntro='地圖照 aoetw.com 的隨機地圖列表，依資料片排列。本作做了原版《帝王世紀》與《征服者入侵》的地圖；每張可以玩的地圖都附一張由遊戲本身的地圖產生器畫出的預覽，資源數也從同一張生成的地圖數出來。之後資料片的地圖只列出網站的介紹。';
export const mapsNote='預覽固定用同一個種子；開局設定畫面可以換種子看別的生成結果。資源以離城鎮中心最近的一方計算，太遠的算中立。';
export const mapLaterReason='之後資料片的地圖：本作照原版與征服者入侵的地圖，這張只列出網站的介紹。';
export const mapPlannedReason='這一輪稍後加入（特殊開局或島嶼地圖）。';
export const mapStrategy:Readonly<Record<string,string>>={
 Arabia:'開闊、易攻難守、沒有水。木頭少，封建時代用箭塔封住對方木區（塔攻）很流行；經濟與初期強兵的文明吃香。',
 Archipelago:'資源有限，後期常打成便宜兵種的消耗戰。控海是關鍵，食物多半來自海上；早期可用運輸船攻上別的島並搶占它的資源，也要搶下資源豐富的小島。',
 Baltic:'以漁船為主要食物可以省下木材。分隔雙方的陸地狹長，適合用城牆擋住；隔開對手之後，用運輸船與戰船跨海進攻。',
 Black_Forest:'地圖封閉，宜及早圍牆、在家發展經濟。後期強力兵種與投石車有利，投石車可以砍樹開路繞到後方；也適合蓋世界奇觀。',
 Crater_Lake:'網站沒有這張圖的頁面。本作照原版的樣子：中央一座山，山頂的火山口是湖，可以上山捕魚；雙方分在山的兩側。',
 Coastal:'控制海域就有穩定的食物，也能沿海突襲。若失去制海權，就在封建晚期到城堡初期快攻騷擾對方的資源。',
 Continental:'快攻要靠海運，不容易成功。農田與漁船各半；重點在沿岸防禦，用攻城器、哨站與箭塔防止對方偷渡。',
 Fortress:'開局的石牆能擋住早期快攻，適合在城堡時代以前就專心發展，再插城堡或快速升級。留意自己的箭塔是否真的護住城牆。',
 Gold_Rush:'盡早控制中央，用城堡與箭塔守住黃金，並阻止對方採中間的黃金。中央有許多狼，派村民去之前要先清掉。',
 Highland:'用城牆圍住淺灘與陸橋；也要提防對方蓋碼頭、用運輸船偷渡。快攻與守家發展都可行。',
 Islands:'每人一座島，控海就是一切：發展海軍、搶下有金石的小島，早期也可以用運輸船登陸快攻。',
 Mediterranean:'控制中央海域：海上有大量食物，運輸船還能偷渡奇襲；同時要提防對方從海上登陸。',
 Migration:'沒有野豬，羊也離城鎮中心很遠，要派人去找。海軍強的文明吃香；要用運輸船把村民送到中央的大陸去搶金石。',
 Rivers:'築牆擋住淺灘，也要提防對方偷渡村民或軍隊；城堡蓋在河道交會的地方可以防船。',
 Team_Islands:'防止敵方運輸船登陸是勝負關鍵；世界奇觀是熱門的勝利方式。',
 Arena:'開局有城牆，城堡時代以前的快攻很難成功，適合快速升級；塔攻仍然可行。封鎖對方門外的金石，僧侶在這張圖特別強。',
 Ghost_Lake:'中央的冰面沒有資源、不能蓋建築，但可以走過去。利用樹叢圍家；中期強勢的文明比晚期文明好用。',
 Mongolia:'利用起伏的地形圍家擋快攻；站在高處作戰有攻擊加成，箭塔可以蓋在對方難以到達的懸崖上；也可以圍住懸崖小道裡的金石。',
 Nomad:'開局沒有城鎮中心：先探路，找到食物與大量金礦的地方再蓋，但別蓋得太晚。也可以在對方村民附近蓋城鎮中心，駐軍反擊。',
 Oasis:'在森林較薄的地方伐木，順便取得湖泊捕魚；目標是控制金、食物與石頭豐富的沙漠。',
 Salt_Marsh:'投資海軍控制水域；爆破船可以伏擊走過淺灘的單位，運輸船可以繞到後方奇襲。淺灘很難封鎖。',
 Scandinavia:'野豬比別的圖多一隻、鹿也多，開局食物充足；衝突多半在中間的黃金。石頭少，很難再蓋第二座城堡或更多城鎮中心。',
 Yucatan:'食物豐富，適合大規模戰鬥，晚期強勢的文明有利。叢林裡有美洲豹，牧羊與採果的村民要小心。'};
