// The 地圖 round: aoetw.com's random-map list (maps/index.vue, 2026-10-02), each map with the site's description
// condensed (scratchpad research, aoetw-maps.json). layout: the playable layout that implements it (null: listed only).
// planned: the layout id reserved for a map a later step of the round adds (special starts, island maps).
export type MapCatalogEntry={site:string|null;zh:string;en:string;expansion:string;page:boolean;layout:string|null;planned:string|null;summary:string};
export const mapExpansions:readonly {id:string;zh:string}[]=[{id:'aok',zh:'帝王世紀'},{id:'aoc',zh:'征服者入侵'},{id:'aof',zh:'失落的帝國'},{id:'ak',zh:'非洲王國'},{id:'aor',zh:'王者崛起'},{id:'de',zh:'決定版'}];
export const mapCatalog:readonly MapCatalogEntry[]=[
 {site:'Arabia',zh:'阿拉伯',en:'Arabia',expansion:'aok',page:true,layout:'arabia',planned:null,summary:'開放地圖，資源比其他圖稀少，易攻難守。木頭通常很少，早期封住對方木區即可取得優勢，箭塔（塔攻）戰術流行。資源固定為8羊2豬3或4鹿、3塊黃金、2塊石頭。現今比賽幾乎都以阿拉伯為主。'},
 {site:'Archipelago',zh:'群島',en:'Archipelago',expansion:'aok',page:true,layout:'archipelago',planned:null,summary:'由大海環繞的一系列小島組成，資源有限，後期常見垃圾兵（戰矛兵、重裝長槍兵、輕騎兵）戰爭。有些玩家獨占一島，有些共享一島。食物大多來自海上，水域控制重要；另有四個額外小島，兩個空島、兩個富含金木食石。'},
 {site:'Baltic',zh:'波羅的海',en:'Baltic',expansion:'aok',page:true,layout:'baltic',planned:null,summary:'四面陸地、中間為海的中等大小地圖，重視隊友與海陸軍協調。建議以漁船而非農田為主要食物來源以節省木材。分隔玩家的陸地狹長，適合圍牆；隔離對手後以運輸船與戰船跨海攻擊。'},
 {site:'Black_Forest',zh:'黑森林',en:'Black Forest',expansion:'aok',page:true,layout:'black-forest',planned:null,summary:'被大量樹木包覆的封閉地圖，可在家爆經濟，應盡早圍牆；比賽多設定為已探索。適合後期強力兵種（如重型投石車）的文明，常打到大後期，入門玩家喜愛。'},
 {site:'Crater_Lake',zh:'火山湖',en:'Crater Lake',expansion:'aok',page:false,layout:'crater-lake',planned:null,summary:''},
 {site:'Coastal',zh:'沿海',en:'Coastal',expansion:'aok',page:true,layout:'coastal',planned:null,summary:'一半水域一半陸地。陸上食物耗盡後應以漁船與戰船控制水域取得食物並可沿海突襲；失去制海權時可於封建晚期／城堡初期快攻騷擾對方資源。團戰中最靠海的玩家應盡快控海。'},
 {site:'Continental',zh:'大陸',en:'Continental',expansion:'aok',page:true,layout:'continental',planned:null,summary:'大片陸地被水域環繞，有時河流分隔雙方，地圖中間有一座孤立島嶼。木頭少且呈小叢分布，黃金較豐富，石頭與食物平均。快攻需海運不易成功；建議農田與漁船各半，重點在沿岸防禦（攻城武器、哨站、箭塔）。'},
 {site:'Fortress',zh:'堡壘',en:'Fortress',expansion:'aok',page:true,layout:'fortress',planned:null,summary:'與圍城類似，玩家開局有被石牆圍繞的城鎮，另有5片農田、4座瞭望箭塔、4棟房屋與1座軍營。各玩家箭塔配置相同，因此有的箭塔能護牆、有的毫無作用。插堡、帝快、城快皆適用。'},
 {site:'Gold_Rush',zh:'淘金潮',en:'Gold Rush',expansion:'aok',page:true,layout:'gold-rush',planned:null,summary:'玩家分布在地圖邊緣，只有少量黃金；地圖正中央沙漠有大量黃金，周圍有許多狼。必須盡早控制中央並以城堡、箭塔守住黃金；初期強勢文明與可一擊殺狼的馬扎爾有利。'},
 {site:'Highland',zh:'高地',en:'Highland',expansion:'aok',page:true,layout:'highland',planned:null,summary:'（頁面標題作「高原」）多懸崖、森林茂密，有一或多條河流穿過；河流有淺灘連接，也可能有小陸路。可圍牆擋住，但對方能以運輸船偷渡。快攻與龜經濟皆可，海陸兼強文明（西班牙、朝鮮、馬來、維京）有利。'},
 {site:'Islands',zh:'島嶼',en:'Islands',expansion:'aok',page:true,layout:'islands',planned:null,summary:'每位玩家獨占一座島，島上可能有鹿與一些綿羊；地形可能為沙漠、草原或美洲叢林。另有無人小島可能蘊藏豐富金石。海權極重要，應發展海軍、搶佔資源小島並可用運輸船快攻；馬來、薩拉森有優勢。'},
 {site:'Mediterranean',zh:'地中海',en:'Mediterranean',expansion:'aok',page:true,layout:'mediterranean',planned:null,summary:'陸地中間包圍一大片海，陸海比例非常不對稱，起始位置與海的距離影響策略。必須控制中央海域：既是龐大食物來源，也能以運輸船偷渡奇襲，同時要提防海上襲擊。'},
 {site:'Migration',zh:'移民',en:'Migration',expansion:'aok',page:true,layout:'migration',planned:null,summary:'頁面稱只出現在多人連線遊戲中。地圖上沒有野豬，綿羊離城鎮中心很遠，可派一名村民找羊。馬來、日本等海軍強盛文明表現不錯。'},
 {site:'Rivers',zh:'河流',en:'Rivers',expansion:'aok',page:true,layout:'rivers',planned:null,summary:'與高原相似，有許多河流分隔玩家，也有淺灘連接陸地。可築牆擋住淺灘，但仍需提防敵方偷渡村民或軍隊快攻。'},
 {site:'Team_Islands',zh:'團隊群島',en:'Team Islands',expansion:'aok',page:true,layout:'team-islands',planned:null,summary:'同盟玩家開局都在自己隊伍的島上，地圖主要由水域包圍但多數戰鬥在陸地。防止敵方運輸船登陸是關鍵；世界奇觀是熱門勝利方式（匈人無神論延長敵奇觀倒數100年）。海軍強盛文明（維京、波斯、朝鮮、義大利、薩拉森）有優勢。'},
 {site:'Arena',zh:'圍城',en:'Arena',expansion:'aoc',page:true,layout:'arena',planned:null,summary:'每位玩家有被圍牆圍住的城鎮，地圖中央為資源豐富的開放區域，整張地圖被樹環繞，唯一進攻路徑是中央開闊區。敵方門外的金或石是首要騷擾目標；小型半封閉區域可能有額外金石。適合城快、帝快，城堡前快攻因城牆不易成功，但塔攻仍可行。'},
 {site:'Ghost_Lake',zh:'鬼湖',en:'Ghost Lake',expansion:'aoc',page:true,layout:'ghost-lake',planned:null,summary:'結冰版的地中海，中央結冰區沒有資源也不能蓋建築。漿果與鹿比一般圖少，黃金、石礦和狼稍多，木頭呈小叢散落。可利用樹叢圍家，但靠近冰區的基地難圍；中期強盛文明（塞爾特、日本、朝鮮）優於晚期文明（西班牙）。'},
 {site:'Mongolia',zh:'蒙古高原',en:'Mongolia',expansion:'aoc',page:true,layout:'mongolia',planned:null,summary:'地形高低起伏，許多天然地形簡單圍起即可擋快攻，也有非常開闊難圍處。善用高地優勢（頁面寫高打低攻擊加成50%），箭塔可蓋在敵人難以到達的懸崖上。金石有時被包在懸崖小道上，圍起來可讓敵人無資源可用。'},
 {site:'Nomad',zh:'游牧',en:'Nomad',expansion:'aoc',page:true,layout:'nomad',planned:null,summary:'三面環海，有時中間有河流；地形為松樹草地的溫帶或棕櫚沙地的沙漠。玩家開局三名村民、沒有城鎮中心，要選擇有食物與大量金礦的點建城鎮中心，不能太晚。團隊可聯合村民早期突襲（高風險），或把基地建得很近，甚至在敵方村民附近蓋城鎮中心駐紮攻擊。'},
 {site:'Oasis',zh:'綠洲',en:'Oasis',expansion:'aoc',page:true,layout:'oasis',planned:null,summary:'中央有巨大水坑，周圍一圈巨大棕櫚樹林；中心外樹木有限、中心內非常豐富，森林覆蓋不對稱。森林較薄處是理想伐木點且可通往中央湖泊捕魚；目標是控制金、食物、石頭豐富的沙漠並利用綠洲資源。'},
 {site:'Salt_Marsh',zh:'鹽沼地',en:'Salt Marsh',expansion:'aoc',page:true,layout:'salt-marsh',planned:null,summary:'可能是王者崛起前第一個兩棲地圖，半水半陸，有許多淺灘、沼澤與可通行水域。樹木與水域提供天然屏障，但淺灘讓突襲難以封鎖。強烈建議投資海軍；爆破船可伏擊過淺灘的單位，運輸船可繞後奇襲。'},
 {site:'Scandinavia',zh:'斯堪地維亞',en:'Scandinavia',expansion:'aoc',page:true,layout:'scandinavia',planned:null,summary:'城鎮中心周圍有許多鹿，以及大多數地圖沒有的第三隻野豬；地圖邊緣有兩條極長、有魚的峽灣。木頭分散但豐富，黃金普通、石頭較少（難蓋第二座城堡或第三個城鎮中心），衝突多在爭奪中間的黃金。'},
 {site:'Yucatan',zh:'猶加敦',en:'Yucatan',expansion:'aoc',page:true,layout:'yucatan',planned:null,summary:'食物資源豐富，城鎮中心附近有更多鹿、綿羊及漿果叢，可進行大規模戰鬥；晚期強盛文明（西班牙、拜占庭）或後期強兵文明較有優勢。'},
 {site:'Acropolis',zh:'雅典衛城',en:'Acropolis',expansion:'aof',page:true,layout:null,planned:null,summary:'非常開放的地圖，中間有一小圈池塘。玩家在特殊的山丘上開局，灰色紋理斜坡無法建造任何建築，幾乎不可能圍好基地；必須下山爭奪黃金與石礦。'},
 {site:'Budapest',zh:'布達佩斯',en:'Budapest',expansion:'aof',page:true,layout:null,planned:null,summary:'玩家開局就有兩座相距不遠的城鎮中心，可產出更多村民；有城鎮中心或村民優勢的文明（波斯、印度、馬來、維京）茁壯，開局額外單位的文明（馬雅、中國、印加）也獲得兩倍初始單位。湖泊之間互不相連，海軍只需少量防守。'},
 {site:'Cenotes',zh:'岩坑池',en:'Cenotes',expansion:'aof',page:true,layout:null,planned:null,summary:'資源比多數地圖少，與阿拉伯相似但有沿岸魚的水池，懸崖讓防守比阿拉伯容易。強烈建議快攻與早期塔攻；木區分散難守，金石要好好保護。'},
 {site:'Land_of_Lakes',zh:'百湖之城',en:'Land of Lakes',expansion:'aof',page:true,layout:null,planned:null,summary:'玩家從半島一角開局，團戰同隊共享半島；地形平坦。大量互不相連的湖泊與池塘，在錯誤的湖訓練海軍可能徒勞；半島三面環湖易預判敵人進攻方向。遺跡在連接半島的狹窄峽谷中。'},
 {site:'Golden_Pit',zh:'金礦谷',en:'Golden Pit',expansion:'aof',page:true,layout:null,planned:null,summary:'四周綠意盎然、中央大坑乾燥貧瘠但有大量金礦，玩家被大坑隔開。坑緣為沙地斜坡，弓兵可藉高地優勢射擊；以城鎮中心、城堡、箭塔保護採金村民。'},
 {site:'Hideout',zh:'藏身之處',en:'Hideout',expansion:'aof',page:true,layout:null,planned:null,summary:'類似圍城，但城鎮被木牆而非石牆圍繞，資源在地圖外部，大部分木材在中央分隔玩家。木牆血少，建議再加一層木／石牆或房屋防封建快攻；後期可沿林線建城堡、箭塔封木，中型投石車可穿樹偷襲。'},
 {site:'Hill_Fort',zh:'山寨',en:'Hill Fort',expansion:'aof',page:false,layout:null,planned:null,summary:''},
 {site:'Lombardia',zh:'倫巴地',en:'Lombardia',expansion:'aof',page:true,layout:null,planned:null,summary:'樹木叢生、海拔變化大、地上有積雪；同隊玩家開局聚在同一側，敵人不易快攻，典型打法為城快或帝快。中間木材需爭奪，木區較小也較難圍基地。'},
 {site:'Steppe',zh:'乾草原',en:'Steppe',expansion:'aof',page:true,layout:null,planned:null,summary:'可說是金礦谷的游牧版，中央是大量可狩獵動物（鹿群）而非金礦。開局有3–4個可容納5人口的蒙古包與可畜養動物（依比賽可能是草尼馬、綿羊或乳牛），可自選城鎮中心位置。中央草原極平坦，周圍小丘，有時有永久凍土；在中央打獵的村民難以躲藏。'},
 {site:'Valley',zh:'峽谷',en:'Valley',expansion:'aof',page:true,layout:null,planned:null,summary:'有冰凍苔原、茂密叢林、開闊熱帶草原三種環境（以草原為主）。玩家在中央乾涸河床附近的微丘陵開局，敵我距離較近；乾河床不能建造任何建築，河床內水坑附近有大量可捕獵動物，開闊區域使圍牆與塔防效率低。'},
 {site:'Megarandom',zh:'超級隨機',en:'MegaRandom',expansion:'aof',page:true,layout:null,planned:null,summary:'永遠不知道會遇到什麼地圖，開局可能有矛兵、長槍兵、駱駝騎兵或火砲塔等單位。常面臨黃金短缺，市場很重要；偵察至關重要，地圖多半開放、中央常有森林或山脈等大型障礙。'},
 {site:'Hamburger',zh:'漢堡包',en:'Hamburger',expansion:'aof',page:true,layout:null,planned:null,summary:'玩家開局在中央島上，被一排樹木隔開，島上有巨大金石礦；島外護城河魚多。地圖外緣無食物但有許多金、石、木小區塊與遺跡，必須盡快往外發展；起始島只有一條木線，宜快速封建塔攻封木。'},
 {site:'Kilimanjaro',zh:'吉力馬札羅山',en:'Kilimanjaro',expansion:'ak',page:true,layout:null,planned:null,summary:'沒有特色的大草原，樹木少（相思樹），有些不含魚的池塘，金石大量。可獵斑馬／鴕鳥與大象，另有山羊可放牧；與阿拉伯相似，地形開闊易攻難守。'},
 {site:'Mountain_Pass',zh:'雪山地',en:'Mountain Pass',expansion:'ak',page:true,layout:null,planned:null,summary:'非洲王國唯一不在非洲的地圖，有積雪山頭、結冰池塘與森林，但大多是廣闊平地。開局類似游牧：沒有城鎮中心、村民散落各地、沒有斥候。沒有漿果或野豬，但有相當數量的綿羊和鹿；樹多、金石少。'},
 {site:'Nile_Delta',zh:'尼羅河三角洲',en:'Nile Delta',expansion:'ak',page:true,layout:null,planned:null,summary:'玩家開局在大河口最北端的小島（三角洲）上，島上只有4隻山羊和一些樹、幾乎沒有金石；須盡快用運輸船把村民送到資源豐富的外圍陸地。尼羅河魚多，海軍強勢文明吃香；野生動物有大象與鴕鳥。'},
 {site:'Serengeti',zh:'塞倫蓋提平原',en:'Serengeti',expansion:'ak',page:true,layout:null,planned:null,summary:'阿拉伯的非洲版本，資源比多數地圖少，易攻難守；營地外的金石是快攻首要目標。野生動物有斑馬、鴕鳥、大象與獅子，另有山羊放牧；地圖上有巨大岩柱。'},
 {site:'Socotra',zh:'索科特拉島',en:'Socotra',expansion:'ak',page:true,layout:null,planned:null,summary:'非常小的島嶼，完全被懸崖環繞，外為無資源的印度洋。玩家開局有3間房屋、13個村民和一個斥候；玩家彼此非常接近、樹線稀疏、資源稀少，戰鬥很早開始並決定勝負。有大象、斑馬、鴕鳥與龍血樹。'},
 {site:'Bog_Islands',zh:'禁閉島',en:'Bog Islands',expansion:'aor',page:true,layout:null,planned:null,summary:'（頁面標題作「沼澤」）玩家從被廣闊可通行、可建造淺灘圍繞的「島嶼」開始，中央是陸軍不能通過、魚多的水體。被視為水上的阿拉伯，海陸軍可互相支援，爆破船極佳。陸地被雨林覆蓋，淺灘上有更多金石；有犀牛、水牛與魚池。'},
 {site:'Mangrove_Jungle',zh:'紅樹林',en:'Mangrove Jungle',expansion:'aor',page:true,layout:null,planned:null,summary:'基地周圍除了鹿、水牛、犀牛外都被紅樹林包圍，沿淺灘可抵達敵營。礦產非常多但都被紅樹林圍住，需更多伐木工或中型投石車開路。'},
 {site:'Pacific_Islands',zh:'太平洋群島',en:'Pacific Islands',expansion:'aor',page:true,layout:null,planned:null,summary:'兩棲地形，玩家從自己的沙洲開始（團戰與隊友共享），四周有淺灘供陸海單位通行，爆破船好用。可說是巨大版沼澤，但陸地更多、淺灘更少；資源較少，有水牛、鹿、犀牛與老虎，木頭稀少且易受海上騷擾。'},
 {site:'Sandbank',zh:'沙洲',en:'Sandbank',expansion:'aor',page:true,layout:null,planned:null,summary:'兩棲地形，玩家從自己的沙洲開始，沙洲形狀不固定且有狹長峽灣；沙洲被寬闊河道與紅樹林隔開，需運輸船才能抵達敵島，邊緣淺灘陸軍可過。有水牛、鹿、犀牛與老虎；海上資源較少，但金石離城鎮很近，中央紅樹林區有珍貴礦產。'},
 {site:'Water_Nomad',zh:'水上游牧',en:'Water Nomad',expansion:'aor',page:true,layout:null,planned:null,summary:'兩棲地圖，少量陸地、許多可建造淺灘與深水；紅樹林、水牛、活海龜與魚多。開局如游牧但資源更多：沒有城鎮中心與斥候，有7位村民與6艘漁船。須集結散落村民與漁船並找多重資源點蓋城鎮中心；爆破船奇效，馬來、柏柏、日本好用。'},
 {site:'Alpine_Lakes',zh:'高山湖泊',en:'Alpine Lakes',expansion:'de',page:false,layout:null,planned:null,summary:''},
 {site:'Bogland',zh:'沼澤',en:'Bogland',expansion:'de',page:false,layout:null,planned:null,summary:''},
 {site:'Four_Lakes',zh:'四座湖泊',en:'Four Lakes',expansion:'de',page:true,layout:null,planned:null,summary:'開放地圖，佈滿木頭與以山羊為主的動物；四角各有一個魚多的湖泊。開放地圖戰術皆適用，熱門戰術是偷跑到敵方湖泊建碼頭出火艨艟騷擾漁船。開局資源大多為8羊2豬4鹿1果、2塊黃金與2塊石頭。'},
 {site:'Golden_Swamp',zh:'金沼澤',en:'Golden Swamp',expansion:'de',page:false,layout:null,planned:null,summary:''},
 {site:'Land_Nomad',zh:'陸地游牧',en:'Land Nomad',expansion:'de',page:false,layout:null,planned:null,summary:''},
 {site:'Mountain_Ridge',zh:'山脊',en:'Mountain Ridge',expansion:'de',page:false,layout:null,planned:null,summary:''},
 {site:'Ravines',zh:'山澗',en:'Ravines',expansion:'de',page:false,layout:null,planned:null,summary:''},
 {site:'Wolf_Hill',zh:'狼山',en:'Wolf Hill',expansion:'de',page:false,layout:null,planned:null,summary:''},
];
