import * as THREE from '../../vendor/three-0.186.0/three.module.js';
import {GLTFLoader} from '../../vendor/three-0.186.0/addons/loaders/GLTFLoader.js';
import {clone} from '../../vendor/three-0.186.0/addons/utils/SkeletonUtils.js';
import {IslandGame,RESOURCE_NAMES,STATE_NAMES,QUESTS} from './simulation.mjs';
const SAVE_KEY='tideborn-island-v1',colors=['#b99445','#528d9a','#b37254','#7d9852','#9b7ba0'];
let modelPromise;
export function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY));if(s?.version===1&&Number.isInteger(s.config?.seed)&&s.config.seed>=1&&s.config.seed<=999999&&s.config.radius>=80&&s.config.radius<=170&&s.config.height>=8&&s.config.height<=30)return s;}catch{}return null;}
export function mountGame(context,saved){
 const {scene,camera,config,graph,village,surface,controls}=context,game=new IslandGame(graph,village.facilities,config,saved),scale=config.radius/120,group=new THREE.Group();scene.add(group);
 let disposed=false,actors=[],lastUI=-1,lastSave=0,currentTab=null,toastTime=0,lastMessage='',lastFrame=0;
 document.body.classList.add('play');document.getElementById('gameUI')?.remove();document.getElementById('npcLabels')?.remove();
 const ui=document.createElement('div');ui.id='gameUI';ui.innerHTML=`<div class="game-hud"><div class="resources" aria-label="島嶼資源">${Object.entries(RESOURCE_NAMES).map(([key,name])=>`<div class="resource">${name}<b id="res-${key}">0</b></div>`).join('')}</div><div class="island-level"><strong id="levelText"></strong><progress id="xpBar" aria-label="島嶼經驗" max="40"></progress></div><div class="timebar"><span id="dayClock"></span><span class="save-status" id="saveStatus">自動儲存</span><button id="pauseGame" aria-pressed="false">暫停</button><button id="speedGame">1×</button><button id="terrainSettings" aria-expanded="false">地形</button></div></div><aside class="quest-panel" id="questPanel" aria-label="當前任務"><h2>島上的新生活</h2><div class="small">居民會自行工作與交貨。<br>製作木板、升級港灣，讓小島成長。</div><div id="questList"></div></aside><nav class="dockbar" aria-label="經營功能">${['居民','建造','農場','製作','市集','任務'].map(tab=>`<button data-tab="${tab}" aria-pressed="false">${tab}</button>`).join('')}</nav><section class="drawer" id="gameDrawer" aria-label="經營操作" hidden><button class="close" id="closeDrawer" aria-label="關閉面板">×</button><h2 id="drawerTitle"></h2><div id="drawerBody"></div></section><div id="gameToast" class="toast-game" role="status"></div>`;document.body.append(ui);
 const badges=document.createElement('div');badges.id='npcLabels';document.body.append(badges);
 const $=id=>document.getElementById(id);
 function showToast(message){$('gameToast').textContent=message;toastTime=3.5;}
 function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(game.snapshot()));$('saveStatus').textContent='已儲存';}catch{$('saveStatus').textContent='無法儲存';}}
 function quests(){return QUESTS.map(q=>{const value=Math.min(game.stats[q.id],q.target),done=game.claimed.includes(q.id);return `<div class="quest"><div class="row"><span>${q.title}</span><b>${value}/${q.target}</b></div><progress value="${value}" max="${q.target}" aria-label="${q.title}進度"></progress><small>＋${q.gold} 金幣 · ${q.xp} XP</small><button data-claim="${q.id}" ${done||value<q.target?'disabled':''}>${done?'已領取':'領獎'}</button></div>`;}).join('');}
 const action=(id,title,detail,label='執行',disabled=false)=>`<div class="recipe"><div>${title}<small>${detail}</small></div><button data-action="${id}" ${disabled?'disabled':''}>${label}</button></div>`;
 function drawer(){if(!currentTab)return;let html='';if(currentTab==='居民'){html='<p>家 → 工作 → 搬運 → 市集 → 家。途中相遇會停下交談；點選追蹤可近看骨架動畫。</p>'+game.agents.map(a=>`<div class="resident"><div><i class="swatch" style="background:${colors[a.id]}"></i>${a.name} · ${a.job}<small>${STATE_NAMES[a.state]}${a.cargo?` · 搬運 ${a.cargo.amount} ${RESOURCE_NAMES[a.cargo.resource]}`:''}</small></div><button data-follow="${a.id}">追蹤</button></div>`).join('');}
 if(currentTab==='建造')html='<p>隨島嶼等級解鎖新設施。建造會實際改變島上景觀與生產能力。</p>'+action('dock','升級碼頭','60 金幣 · 8 木材 · 3 魚｜每趟漁獲 +2',game.upgrades.dock?'已升級':'升級',game.upgrades.dock)+action('garden','Lv.2 溫室','50 金幣 · 8 木材 · 1 稀有材料｜每趟作物 +3',game.upgrades.garden?'已建成':game.level<2?'尚未解鎖':'建造',game.level<2||game.upgrades.garden)+action('bakery','Lv.3 麵包房','80 金幣 · 12 木材 · 2 稀有材料｜解鎖烘焙',game.upgrades.bakery?'已建成':game.level<3?'尚未解鎖':'建造',game.level<3||game.upgrades.bakery);
 if(currentTab==='農場')html=`<p>阿禾每次收成 ${game.upgrades.garden?8:5} 份作物，送抵市集才加入庫存。綿綿在牧場收集食物。你可以把農產製成餐點。</p>`+action('cook','蔬菜餐','3 作物 → 4 食物 · 3 XP','製作')+action('garden','農田溫室','Lv.2｜50 金幣 · 8 木材 · 1 稀有材料',game.upgrades.garden?'已建成':'建造',game.level<2||game.upgrades.garden);
 if(currentTab==='製作')html='<p>木工交付木材後，可製成任務木板。木板送出會消耗庫存。</p>'+action('boards','木板交付','4 木材 → 4 塊任務木板 · 4 XP','製作並送出')+action('cook','蔬菜餐','3 作物 → 4 食物 · 3 XP','製作')+action('bread','烘焙麵包','4 作物 → 8 食物 · 4 XP｜需麵包房','烘焙',!game.upgrades.bakery);
 if(currentTab==='市集')html='<p>居民抵達後會交貨；遇到其他居民時會面對面交易。也能使用下列固定價格買賣。</p>'+action('buyWood','購入木材','20 金幣 → 4 木材','購買')+action('sellFish','販售漁獲','2 魚 → 18 金幣 · 2 XP','販售')+action('sellCrops','販售作物','5 作物 → 15 金幣','販售');
 if(currentTab==='任務')html=`<p>完成目標後領取獎勵。已完成 ${game.claimed.length}/4 項任務。</p>`+quests();
 if($('drawerBody').innerHTML!==html){const focused=document.activeElement;const actionId=focused?.dataset?.action,claimId=focused?.dataset?.claim;$('drawerBody').innerHTML=html;if(actionId)$('drawerBody').querySelector(`[data-action="${actionId}"]`)?.focus();if(claimId)$('drawerBody').querySelector(`[data-claim="${claimId}"]`)?.focus();}
 }
 function refresh(){for(const[k,v]of Object.entries(game.resources))$('res-'+k).textContent=Math.floor(v);const min=game.level===1?0:game.level===2?40:100,max=game.level===1?40:game.level===2?100:200;$('levelText').textContent=`島嶼 Lv.${game.level} · ${game.xp} XP`;$('xpBar').max=max-min;$('xpBar').value=Math.min(max-min,game.xp-min);$('questList').innerHTML=quests();$('dayClock').textContent=`第 ${Math.floor(game.time/180)+1} 天 · ${String(6+Math.floor(game.time%180/15)).padStart(2,'0')}:00`;$('message').textContent=game.log[0];village.applyUpgrades(game.upgrades);drawer();}
 ui.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){currentTab=currentTab===b.dataset.tab?null:b.dataset.tab;$('gameDrawer').hidden=!currentTab;ui.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.tab===currentTab)));if(currentTab){$('drawerTitle').textContent=currentTab;drawer();}}
 if(b.id==='closeDrawer'){currentTab=null;$('gameDrawer').hidden=true;ui.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-pressed','false'));}
 if(b.dataset.action){game.action(b.dataset.action);showToast(game.log[0]);refresh();save();}
 if(b.dataset.claim){if(game.claim(b.dataset.claim)){showToast(game.log[0]);refresh();save();}}
 if(b.dataset.follow){const a=game.agents[Number(b.dataset.follow)],target=new THREE.Vector3(a.x,surface(a.x,a.z),a.z);controls.target.copy(target);camera.clearViewOffset();camera.zoom=1;camera.position.copy(target).add(new THREE.Vector3(28*scale,42*scale,42*scale));controls.minDistance=18*scale;camera.updateProjectionMatrix();controls.update();currentTab=null;$('gameDrawer').hidden=true;ui.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-pressed','false'));showToast(`${a.name} · ${a.job}｜${STATE_NAMES[a.state]}`);}
 if(b.id==='pauseGame'){game.paused=!game.paused;b.textContent=game.paused?'繼續':'暫停';b.setAttribute('aria-pressed',String(game.paused));}
 if(b.id==='speedGame'){game.speed=game.speed===1?3:game.speed===3?8:1;b.textContent=game.speed+'×';}
 if(b.id==='terrainSettings'){document.body.classList.toggle('settings-open');b.setAttribute('aria-expanded',String(document.body.classList.contains('settings-open')));}
 };
 const onKey=e=>{if(e.key==='Escape'){currentTab=null;$('gameDrawer').hidden=true;document.body.classList.remove('settings-open');$('terrainSettings').setAttribute('aria-expanded','false');ui.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-pressed','false'));}};window.addEventListener('keydown',onKey);window.addEventListener('pagehide',save);
 modelPromise??=new GLTFLoader().loadAsync(new URL('../../assets/tideborn-island/villager.gltf',import.meta.url).href);
 const ready=modelPromise.then(gltf=>{if(disposed)return;actors=game.agents.map(a=>{const root=new THREE.Group(),model=clone(gltf.scene);root.add(model);root.scale.setScalar(scale*1.5);group.add(root);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.frustumCulled=false;o.material=o.material.clone();if(o.material.name==='cloth')o.material.color.set(colors[a.id]);}});const mixer=new THREE.AnimationMixer(model),actions=Object.fromEntries(gltf.animations.map(clip=>[clip.name,mixer.clipAction(clip)]));actions.idle.play();
 const cargo=new THREE.Mesh(new THREE.BoxGeometry(.85,.65,.7),new THREE.MeshLambertMaterial({color:'#b88953'}));cargo.position.set(0,1.35,.65);root.add(cargo);cargo.visible=false;
 const pile=new THREE.Mesh(new THREE.BoxGeometry(1.5,1,1.5),new THREE.MeshLambertMaterial({color:'#bb9366'}));const work=graph.nodes.find(n=>n.id===a.work);pile.position.set(work.x+2*scale,surface(work.x,work.z)+.6*scale,work.z);pile.scale.setScalar(scale);group.add(pile);
 const badge=document.createElement('div');badge.className='npc-badge';badges.append(badge);return {root,mixer,actions,lastCargo:!!a.cargo,animation:'idle',cargo,pile,badge};});refresh();return gltf;}).catch(error=>{if(!disposed)showToast('村民模型載入失敗，請重新整理。');throw error;});
 refresh();
 function update(time){const dt=lastFrame?Math.min((time-lastFrame)/1000,.1):0;lastFrame=time;game.step(dt);const elapsed=game.paused?0:dt*game.speed;for(const a of game.agents){const actor=actors[a.id];if(!actor)continue;const marketOffset=a.state==='exchange'?(a.id<a.partner?-1.3:1.3)*scale:0;actor.root.position.set(a.x+marketOffset,Number.isFinite(a.y)?a.y:surface(a.x,a.z)+.3,a.z);actor.root.rotation.y=a.heading||0;
 if(a.partner!==null){const partner=game.agents[a.partner];const partnerOffset=a.state==='exchange'?-marketOffset:0;actor.root.rotation.y=Math.atan2(partner.x+partnerOffset-actor.root.position.x,partner.z-actor.root.position.z);}
 const animation=['toWork','toMarket','toHome'].includes(a.state)?'walk':a.state==='work'?'work':'idle';if(actor.animation!==animation){actor.actions[actor.animation].fadeOut(.15);actor.actions[animation].reset().fadeIn(.15).play();actor.animation=animation;}actor.mixer.update(elapsed);if(actor.lastCargo&&!a.cargo){const delivered=actor.cargo;group.attach(delivered);const depot=graph.nodes.find(n=>n.id===game.market),slot=(game.stats.deliveries-1)%8;delivered.position.set(depot.x+(3+slot%4)*scale,surface(depot.x,depot.z)+(.5+Math.floor(slot/4))*scale,depot.z-2*scale);delivered.scale.setScalar(scale*1.5);delivered.visible=true;delivered.userData.delivery=true;const old=group.children.filter(o=>o.userData.delivery);if(old.length>8){const oldest=old[0];group.remove(oldest);oldest.geometry.dispose();oldest.material.dispose();}actor.cargo=new THREE.Mesh(new THREE.BoxGeometry(.85,.65,.7),new THREE.MeshLambertMaterial({color:'#b88953'}));actor.cargo.position.set(0,1.35,.65);actor.root.add(actor.cargo);}actor.lastCargo=!!a.cargo;actor.cargo.visible=!!a.cargo;actor.pile.visible=(game.stock[a.id]||0)>0;actor.pile.scale.y=scale*Math.min(1,(game.stock[a.id]||0)/a.amount);const p=actor.root.position.clone();p.y+=5*scale;p.project(camera);actor.badge.style.left=(p.x*.5+.5)*innerWidth+'px';actor.badge.style.top=(-p.y*.5+.5)*innerHeight+'px';actor.badge.hidden=p.z>1||p.z<-1;actor.badge.textContent=`${a.name} ${a.state==='talk'?'···':a.state==='exchange'?'⇄':a.cargo?'▣':''}`;actor.badge.dataset.active=String(a.state==='talk'||a.state==='exchange');}
 if(time-lastUI>600){refresh();lastUI=time;}if(time-lastSave>5000){save();lastSave=time;}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('gameToast').textContent='';}if(lastMessage!==game.log[0])lastMessage=game.log[0];}
 return {game,group,ready,update,save,get actors(){return actors;},destroy(){disposed=true;window.removeEventListener('pagehide',save);window.removeEventListener('keydown',onKey);scene.remove(group);const geometry=new Set(),materials=new Set();group.traverse(o=>{if(o.geometry&&!o.isSkinnedMesh)geometry.add(o.geometry);if(o.material)materials.add(o.material);});geometry.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());actors.forEach(a=>a.mixer.stopAllAction());badges.remove();ui.remove();}};
}
